STRINGIFY(

$genType cos($genType y);
$genHType cos($genHType y);
float3 cross(float3 x, float3 y);
float dot($genType x, $genType y);
$genType mix($genType x, $genType y, float t);
float2x2 inverse(float2x2 m);
float3x3 inverse(float3x3 m);
float4x4 inverse(float4x4 m);
$genType normalize($genType x);
$genHType normalize($genHType x);
$genType radians($genType degrees);
$genHType radians($genHType degrees);
$genType sin($genType x);
$genHType sin($genHType x);
$genType sqrt($genType x);
$genHType sqrt($genHType x);
$genType tan($genType x);
$genHType tan($genHType x);

)
