### Compilation failed:

error: 1: only one backend qualifier can be used
layout (
^^^^^^^^...
error: 1: only one pixel format qualifier can be used
layout (
^^^^^^^^...
error: 1: layout qualifier 'origin_upper_left' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'push_constant' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'blend_support_all_equations' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'color' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'location' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'offset' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'binding' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'index' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'set' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'builtin' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'input_attachment_index' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'vulkan' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'metal' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'webgpu' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'direct3d' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'rgba8' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'rgba32f' is not permitted here
layout (
^^^^^^^^...
error: 1: layout qualifier 'r32f' is not permitted here
layout (
^^^^^^^^...
error: 23: only one backend qualifier can be used
layout (
^^^^^^^^...
error: 23: only one pixel format qualifier can be used
layout (
^^^^^^^^...
error: 23: layout qualifier 'origin_upper_left' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'push_constant' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'blend_support_all_equations' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'color' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'location' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'offset' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'binding' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'index' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'set' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'builtin' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'input_attachment_index' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'vulkan' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'metal' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'webgpu' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'direct3d' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'rgba8' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'rgba32f' is not permitted here
layout (
^^^^^^^^...
error: 23: layout qualifier 'r32f' is not permitted here
layout (
^^^^^^^^...
40 errors
