SOURCE := \
    BitmapCopyTest.cpp \
    BitmapGetColorTest.cpp \
    BlitRowTest.cpp \
    ClampRangeTest.cpp \
    ClipCubicTest.cpp \
    ClipStackTest.cpp \
    ClipperTest.cpp \
    ColorFilterTest.cpp \
    ColorTest.cpp \
    DequeTest.cpp \
    DrawBitmapRectTest.cpp \
    FillPathTest.cpp \
    FlateTest.cpp \
    GeometryTest.cpp \
    InfRectTest.cpp \
    MathTest.cpp \
    MatrixTest.cpp \
    MetaDataTest.cpp \
    PackBitsTest.cpp \
    PaintTest.cpp \
    ParsePathTest.cpp \
    PathCoverageTest.cpp \
    PathMeasureTest.cpp \
    PathTest.cpp \
    Reader32Test.cpp \
    RefDictTest.cpp \
    RegionTest.cpp \
    Sk64Test.cpp \
    skia_test.cpp \
    SortTest.cpp \
    SrcOverTest.cpp \
    StreamTest.cpp \
    StringTest.cpp \
    Test.cpp \
    TestSize.cpp \
    UtilsTest.cpp \
    Writer32Test.cpp \
    XfermodeTest.cpp
