#!/usr/bin/env python
#
# Copyright 2016 Google Inc.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import collections
import os
import sys

# We'll recursively search each include directory for headers,
# then write them to skia.h with a small blacklist.

# We'll also write skia.h.deps, which Ninja uses to track dependencies. It's the
# very same mechanism Ninja uses to know which .h files affect which .cpp files.

skia_h       = sys.argv[1]
include_dirs = sys.argv[2:]

blacklist = {
  "GrGLConfig_chrome.h",
  "SkFontMgr_fontconfig.h",
}

Header = collections.namedtuple('Header', ['absolute', 'include'])

headers = {}
for include_dir in include_dirs:
  for root, _, filenames in os.walk(include_dir):
    for filename in filenames:
      if not filename.endswith('.h') or filename in blacklist:
        continue
      absolute_path = os.path.join(root, filename)
      statinfo = os.stat(absolute_path)
      key = str(statinfo.st_ino) + ":" + str(statinfo.st_dev)
      include_path = os.path.relpath(absolute_path, include_dir)
      if key not in headers or len(include_path) < len(headers[key].include):
        headers[key] = Header(absolute_path, include_path)

headers = headers.values()
headers.sort(key=lambda a: a.include)

with open(skia_h, "w") as f:
  f.write('// skia.h generated by GN.\n')
  f.write('#ifndef skia_h_DEFINED\n')
  f.write('#define skia_h_DEFINED\n')
  for header in headers:
    f.write('#include "' + header.include + '"\n')
  f.write('#endif//skia_h_DEFINED\n')

with open(skia_h + '.deps', "w") as f:
  f.write(skia_h + ':')
  for header in headers:
    f.write(' ' + header.absolute)
  f.write('\n')

# Temporary: during development this file wrote skia.h.d, not skia.h.deps,
# and I think we have some bad versions of those files laying around.
if os.path.exists(skia_h + '.d'):
  os.remove(skia_h + '.d')
