#!/usr/bin/env python
#
# Copyright 2016 Google Inc.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Generate Android.bp for Skia from GN configuration.

import string

t = string.Template('''// This file is autogenerated by gn_to_bp.py.

cc_library {
  name: "libskia",
  cflags: [
    "-fPIC",                     // TODO: Is this not the default?
    "-U_FORTIFY_SOURCE",
    "-D_FORTIFY_SOURCE=1",
    "-DSKIA_IMPLEMENTATION=1",
    "-DqDNGBigEndian=0",
    "-Wno-unused-parameter",
    "-Wno-clobbered",
    "-Wno-error",               // TODO: why even show the warnings?
  ],
  cppflags: [
    "-std=c++11",
    "-fexceptions",
    "-fno-threadsafe-statics",
  ],

  export_include_dirs: $export_includes,
  local_include_dirs: $local_includes,
  srcs: $srcs,

  arch: {
    arm: {
      instruction_set: "thumb",   // TODO: Is this not the default?
      srcs: $arm_srcs,
      armv7_a_neon: {
        srcs: $arm_neon_srcs,
      },
    },
    arm64: {
      srcs: $arm64_srcs,
    },

    mips: {
      cflags: ["-EL"],       // TODO: Is this not the default?
      srcs: $mips_srcs,
    }
    mips64: {
      cflags: ["-EL"],       // TODO: Is this not the default?
      srcs: $mips64_srcs,
    }

    x86: {
      cflags: [
        "-msse2",            // TODO: Is this not the default?
        "-mfpmath=sse",      // TODO: Is this not the default?
      ],
      srcs: $x86_srcs,
    },
    x86_64: {
      srcs: $x86_64_srcs,
    },
  }

  shared_libs: [
      "libEGL",
      "libGLESv2",
      "libdng_sdk",
      "libexpat",
      "libft2",
      "libicui18n",
      "libicuuc",
      "libjpeg",
      "liblog",
      "libpiex",
      "libpng",
      "libz",
  ],
  static_libs: [
      "libgif",
      "libsfntly",
      "libwebp-decode",
      "libwebp-encode",
  ],
  include_dirs: [
      "external/dng_sdk",
      "external/expat/lib",
      "external/freetype/include",
      "external/giflib",
      "external/libjpeg-turbo",
      "external/libpng",
      "external/piex",
      "external/sfntly/cpp/src",
      "external/webp/include",
      "external/zlib",
  ],
''')

def to_str(lst):
  return repr(lst).replace("'", '"')

# TODO: load these from GN
print t.substitute({
  'export_includes': to_str([]),
  'local_includes': to_str([]),
  'srcs': to_str([]),
  'arm_srcs': to_str([ 'foo.cpp', 'bar.cpp' ]),
  'arm_neon_srcs': to_str([ 'baz.cpp' ]),
  'arm64_srcs': to_str([]),
  'mips_srcs': to_str([]),
  'mips64_srcs': to_str([]),
  'x86_srcs': to_str([]),
  'x86_64_srcs': to_str([]),
})
