
out vec4 sk_FragColor;
void main() {
    sk_FragColor.x = 34.0;
    sk_FragColor.x = 30.0;
    sk_FragColor.x = 64.0;
    sk_FragColor.x = 16.0;
    sk_FragColor.x = 19.0;
    sk_FragColor.x = 1.0;
    sk_FragColor.x = -2.0;
    sk_FragColor.x = 3.0;
    sk_FragColor.x = -4.0;
    sk_FragColor.x = 5.0;
    sk_FragColor.x = -6.0;
    sk_FragColor.x = 7.0;
    sk_FragColor.x = -8.0;
    sk_FragColor.x = 9.0;
    sk_FragColor.x = -10.0;
    sk_FragColor.x = 11.0;
    sk_FragColor.x = -12.0;
    sk_FragColor.x = sqrt(1.0);
    sk_FragColor.x = sqrt(2.0);
    sk_FragColor.x = sqrt(3.0);
    sk_FragColor.x = 0.0;
    sk_FragColor.x = sqrt(5.0);
    sk_FragColor.x = sqrt(6.0);
    sk_FragColor.x = 0.0;
    sk_FragColor.x = sqrt(8.0);
    sk_FragColor.x = 0.0;
    sk_FragColor.x += 1.0;
    sk_FragColor.x -= 1.0;
    sk_FragColor.x *= 2.0;
    sk_FragColor.x /= 2.0;
}
