

/**************************************************************************************************
 *** This file was autogenerated from GrChildProcessorFieldAccess.fp; do not modify.
 **************************************************************************************************/
#ifndef GrChildProcessorFieldAccess_DEFINED
#define GrChildProcessorFieldAccess_DEFINED

#include "include/core/SkM44.h"
#include "include/core/SkTypes.h"


#include "src/gpu/GrFragmentProcessor.h"

class GrChildProcessorFieldAccess : public GrFragmentProcessor {
public:
    static std::unique_ptr<GrFragmentProcessor> Make(std::unique_ptr<GrFragmentProcessor> child) {
        return std::unique_ptr<GrFragmentProcessor>(new GrChildProcessorFieldAccess(std::move(child)));
    }
    GrChildProcessorFieldAccess(const GrChildProcessorFieldAccess& src);
    std::unique_ptr<GrFragmentProcessor> clone() const override;
    const char* name() const override { return "ChildProcessorFieldAccess"; }
private:
    GrChildProcessorFieldAccess(std::unique_ptr<GrFragmentProcessor> child)
    : INHERITED(kGrChildProcessorFieldAccess_ClassID, kNone_OptimizationFlags) {
        SkASSERT(child);        this->registerChild(std::move(child), SkSL::SampleUsage::PassThrough());    }
    GrGLSLFragmentProcessor* onCreateGLSLInstance() const override;
    void onGetGLSLProcessorKey(const GrShaderCaps&, GrProcessorKeyBuilder*) const override;
    bool onIsEqual(const GrFragmentProcessor&) const override;
#if GR_TEST_UTILS
    SkString onDumpInfo() const override;
#endif
    GR_DECLARE_FRAGMENT_PROCESSOR_TEST
    using INHERITED = GrFragmentProcessor;
};
#endif
