

/**************************************************************************************************
 *** This file was autogenerated from GrNullableChildProcessor.fp; do not modify.
 **************************************************************************************************/
#ifndef GrNullableChildProcessor_DEFINED
#define GrNullableChildProcessor_DEFINED

#include "include/core/SkM44.h"
#include "include/core/SkTypes.h"


#include "src/gpu/GrFragmentProcessor.h"

class GrNullableChildProcessor : public GrFragmentProcessor {
public:
    static std::unique_ptr<GrFragmentProcessor> Make(std::unique_ptr<GrFragmentProcessor> child) {
        return std::unique_ptr<GrFragmentProcessor>(new GrNullableChildProcessor(std::move(child)));
    }
    GrNullableChildProcessor(const GrNullableChildProcessor& src);
    std::unique_ptr<GrFragmentProcessor> clone() const override;
    const char* name() const override { return "NullableChildProcessor"; }
private:
    GrNullableChildProcessor(std::unique_ptr<GrFragmentProcessor> child)
    : INHERITED(kGrNullableChildProcessor_ClassID, kNone_OptimizationFlags) {
        this->registerChild(std::move(child), SkSL::SampleUsage::PassThrough());    }
    GrGLSLFragmentProcessor* onCreateGLSLInstance() const override;
    void onGetGLSLProcessorKey(const GrShaderCaps&, GrProcessorKeyBuilder*) const override;
    bool onIsEqual(const GrFragmentProcessor&) const override;
#if GR_TEST_UTILS
    SkString onDumpInfo() const override;
#endif
    GR_DECLARE_FRAGMENT_PROCESSOR_TEST
    using INHERITED = GrFragmentProcessor;
};
#endif
