{
  'targets': [
    {
      'target_name': 'effects',
      'type': 'static_library',
      'include_dirs': [
        '../include/effects',
        '../src/core',
      ],
      'sources': [
        '../include/effects/Sk1DPathEffect.h',
        '../include/effects/Sk2DPathEffect.h',
        '../include/effects/SkAvoidXfermode.h',
        '../include/effects/SkArithmeticMode.h',
        '../include/effects/SkBlurDrawLooper.h',
        '../include/effects/SkBlurImageFilter.h',
        '../include/effects/SkBlurMaskFilter.h',
        '../include/effects/SkColorMatrix.h',
        '../include/effects/SkColorMatrixFilter.h',
        '../include/effects/SkCornerPathEffect.h',
        '../include/effects/SkDashPathEffect.h',
        '../include/effects/SkDiscretePathEffect.h',
        '../include/effects/SkDrawExtraPathEffect.h',
        '../include/effects/SkEmbossMaskFilter.h',
        '../include/effects/SkGradientShader.h',
        '../include/effects/SkKernel33MaskFilter.h',
        '../include/effects/SkLayerDrawLooper.h',
        '../include/effects/SkLayerRasterizer.h',
        '../include/effects/SkLightingImageFilter.h',
        '../include/effects/SkMorphologyImageFilter.h',
        '../include/effects/SkPaintFlagsDrawFilter.h',
        '../include/effects/SkPixelXorXfermode.h',
        '../include/effects/SkPorterDuff.h',
        '../include/effects/SkStippleMaskFilter.h',
        '../include/effects/SkTableColorFilter.h',
        '../include/effects/SkTableMaskFilter.h',
        '../include/effects/SkTransparentShader.h',
        '../include/effects/SkMagnifierImageFilter.h',

        '../src/effects/Sk1DPathEffect.cpp',
        '../src/effects/Sk2DPathEffect.cpp',
        '../src/effects/SkAvoidXfermode.cpp',
        '../src/effects/SkArithmeticMode.cpp',
        '../src/effects/SkBlurDrawLooper.cpp',
        '../src/effects/SkBlurMask.cpp',
        '../src/effects/SkBlurMask.h',
        '../src/effects/SkBlurImageFilter.cpp',
        '../src/effects/SkBlurMaskFilter.cpp',
        '../src/effects/SkColorFilters.cpp',
        '../src/effects/SkColorMatrix.cpp',
        '../src/effects/SkColorMatrixFilter.cpp',
        '../src/effects/SkCornerPathEffect.cpp',
        '../src/effects/SkDashPathEffect.cpp',
        '../src/effects/SkDiscretePathEffect.cpp',
        '../src/effects/SkEmbossMask.cpp',
        '../src/effects/SkEmbossMask.h',
        '../src/effects/SkEmbossMask_Table.h',
        '../src/effects/SkEmbossMaskFilter.cpp',
        '../src/effects/SkKernel33MaskFilter.cpp',
        '../src/effects/SkLayerDrawLooper.cpp',
        '../src/effects/SkLayerRasterizer.cpp',
        '../src/effects/SkLightingImageFilter.cpp',
        '../src/effects/SkMorphologyImageFilter.cpp',
        '../src/effects/SkPaintFlagsDrawFilter.cpp',
        '../src/effects/SkPixelXorXfermode.cpp',
        '../src/effects/SkPorterDuff.cpp',
        '../src/effects/SkStippleMaskFilter.cpp',
        '../src/effects/SkTableColorFilter.cpp',
        '../src/effects/SkTableMaskFilter.cpp',
        '../src/effects/SkTestImageFilters.cpp',
        '../src/effects/SkTransparentShader.cpp',
        '../src/effects/SkMagnifierImageFilter.cpp',

        '../src/effects/gradients/SkBitmapCache.cpp',
        '../src/effects/gradients/SkBitmapCache.h',
        '../src/effects/gradients/SkClampRange.cpp',
        '../src/effects/gradients/SkClampRange.h',
        '../src/effects/gradients/SkRadialGradient_Table.h',
        '../src/effects/gradients/SkGradientShader.cpp',
        '../src/effects/gradients/SkGradientShaderPriv.h',
        '../src/effects/gradients/SkLinearGradient.cpp',
        '../src/effects/gradients/SkLinearGradient.h',
        '../src/effects/gradients/SkRadialGradient.cpp',
        '../src/effects/gradients/SkRadialGradient.h',
        '../src/effects/gradients/SkTwoPointRadialGradient.cpp',
        '../src/effects/gradients/SkTwoPointRadialGradient.h',
        '../src/effects/gradients/SkTwoPointConicalGradient.cpp',
        '../src/effects/gradients/SkTwoPointConicalGradient.h',
        '../src/effects/gradients/SkSweepGradient.cpp',
        '../src/effects/gradients/SkSweepGradient.h',
      ],
      'direct_dependent_settings': {
        'include_dirs': [
          '../include/effects',
        ],
      },
      'dependencies': [
        'core.gyp:core',
      ],
      'conditions': [
        ['skia_gpu == 1', {
          'include_dirs': [
            '../src/gpu',
          ],
          'dependencies': [
            'gpu.gyp:gr',
          ],
        }],
      ],
    },
  ],
}

# Local Variables:
# tab-width:2
# indent-tabs-mode:nil
# End:
# vim: set expandtab tabstop=2 shiftwidth=2:
