#!/bin/bash

# fiddle_ninja simply builds a Release version of the 
# provided fiddle into the local skia tree's out/Release
# directory.
#
# This script must be run after fiddle_gyp

[ -z $SKIA_ROOT ] && SKIA_ROOT="/skia_build/skia"

PATH=$PATH:/skia_build/depot_tools

ninja -C $SKIA_ROOT/out/Release $1

