layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (webgpu, rgba8, set=1, binding=0) writeonly texture2D texRGBA;
layout (webgpu, r32f,  set=1, binding=1) writeonly texture2D texRed;

noinline void use_texture(layout(rgba8) writeonly texture2D passedInTexRGBA,
                          layout(r32f)  writeonly texture2D passedInTexRed) {
    // TODO: make changes to textures
}

void main() {
    use_texture(texRGBA, texRed);
}
