
out vec4 sk_FragColor;
uniform vec4 colorRed;
uniform vec4 colorGreen;
uniform float unknownInput;
bool test_b() {
    int unknown = int(unknownInput);
    bool ok = true;
    int x = 34;
    ok = ok && x == 34;
    x = 30;
    ok = ok && x == 30;
    x = 64;
    ok = ok && x == 64;
    x = 16;
    ok = ok && x == 16;
    x = 1;
    ok = ok && x == 1;
    x = -2;
    ok = ok && x == -2;
    x = 3;
    ok = ok && x == 3;
    x = -4;
    ok = ok && x == -4;
    x = 5;
    ok = ok && x == 5;
    x = -6;
    ok = ok && x == -6;
    x = 7;
    ok = ok && x == 7;
    x = -8;
    ok = ok && x == -8;
    x = 9;
    ok = ok && x == 9;
    x = -10;
    ok = ok && x == -10;
    x = 11;
    ok = ok && x == 11;
    x = -12;
    ok = ok && x == -12;
    x = unknown;
    ok = ok && x == unknown;
    x = unknown;
    ok = ok && x == unknown;
    x = unknown;
    ok = ok && x == unknown;
    x = 0;
    ok = ok && x == 0;
    x = unknown;
    ok = ok && x == unknown;
    x = unknown;
    ok = ok && x == unknown;
    x = 0;
    ok = ok && x == 0;
    x = unknown;
    ok = ok && x == unknown;
    x = 0 / unknown;
    ok = ok && x == 0;
    x += 1;
    ok = ok && x == 1;
    ok = ok && x == 1;
    x -= 2;
    ok = ok && x == -1;
    ok = ok && x == -1;
    ok = ok && x == -1;
    x *= 2;
    ok = ok && x == -2;
    ok = ok && x == -2;
    x /= 2;
    ok = ok && x == -1;
    return ok;
}
vec4 main() {
    return test_b() ? colorGreen : colorRed;
}
