#ifndef __DEFINED__SkPdfEnums
#define __DEFINED__SkPdfEnums

enum SkPdfObjectType {
  kObject_SkPdfObjectType,
  kArray_SkPdfObjectType,
  kBoolean_SkPdfObjectType,
  kDictionary_SkPdfObjectType,
  kALinkAnnotationDictionary_SkPdfObjectType,
  kActionDictionary_SkPdfObjectType,
  kAlternateImageDictionary_SkPdfObjectType,
  kAnnotationActionsDictionary_SkPdfObjectType,
  kAnnotationDictionary_SkPdfObjectType,
  kAppearanceCharacteristicsDictionary_SkPdfObjectType,
  kAppearanceDictionary_SkPdfObjectType,
  kApplicationDataDictionary_SkPdfObjectType,
  kArtifactsDictionary_SkPdfObjectType,
  kAttributeObjectDictionary_SkPdfObjectType,
  kBeadDictionary_SkPdfObjectType,
  kBlockLevelStructureElementsDictionary_SkPdfObjectType,
  kBorderStyleDictionary_SkPdfObjectType,
  kBoxColorInformationDictionary_SkPdfObjectType,
  kBoxStyleDictionary_SkPdfObjectType,
  kCIDFontDescriptorDictionary_SkPdfObjectType,
  kCIDFontDictionary_SkPdfObjectType,
  kCIDSystemInfoDictionary_SkPdfObjectType,
  kCMapDictionary_SkPdfObjectType,
  kCalgrayColorSpaceDictionary_SkPdfObjectType,
  kCalrgbColorSpaceDictionary_SkPdfObjectType,
  kCatalogDictionary_SkPdfObjectType,
  kCcittfaxdecodeFilterDictionary_SkPdfObjectType,
  kCheckboxFieldDictionary_SkPdfObjectType,
  kChoiceFieldDictionary_SkPdfObjectType,
  kComponentsWithMetadataDictionary_SkPdfObjectType,
  kDctdecodeFilterDictionary_SkPdfObjectType,
  kDeviceNColorSpaceDictionary_SkPdfObjectType,
  kDocumentCatalogActionsDictionary_SkPdfObjectType,
  kDocumentInformationDictionary_SkPdfObjectType,
  kEmbeddedFileParameterDictionary_SkPdfObjectType,
  kEmbeddedFileStreamDictionary_SkPdfObjectType,
  kEmbeddedFontStreamDictionary_SkPdfObjectType,
  kEncodingDictionary_SkPdfObjectType,
  kEncryptedEmbeddedFileStreamDictionary_SkPdfObjectType,
  kEncryptionCommonDictionary_SkPdfObjectType,
  kFDFCatalogDictionary_SkPdfObjectType,
  kFDFDictionary_SkPdfObjectType,
  kFDFFieldDictionary_SkPdfObjectType,
  kFDFFileAnnotationDictionary_SkPdfObjectType,
  kFDFNamedPageReferenceDictionary_SkPdfObjectType,
  kFDFPageDictionary_SkPdfObjectType,
  kFDFTemplateDictionary_SkPdfObjectType,
  kFDFTrailerDictionary_SkPdfObjectType,
  kFieldDictionary_SkPdfObjectType,
  kFileAttachmentAnnotationDictionary_SkPdfObjectType,
  kFileSpecificationDictionary_SkPdfObjectType,
  kFileTrailerDictionary_SkPdfObjectType,
  kFontDescriptorDictionary_SkPdfObjectType,
  kFontDictionary_SkPdfObjectType,
  kType0FontDictionary_SkPdfObjectType,
  kType1FontDictionary_SkPdfObjectType,
  kMultiMasterFontDictionary_SkPdfObjectType,
  kTrueTypeFontDictionary_SkPdfObjectType,
  kType3FontDictionary_SkPdfObjectType,
  kType1FontDictionary__End_SkPdfObjectType,
  kFontDictionary__End_SkPdfObjectType,
  kFormFieldActionsDictionary_SkPdfObjectType,
  kFreeTextAnnotationDictionary_SkPdfObjectType,
  kFunctionCommonDictionary_SkPdfObjectType,
  kGoToActionDictionary_SkPdfObjectType,
  kGraphicsStateDictionary_SkPdfObjectType,
  kGroupAttributesDictionary_SkPdfObjectType,
  kHideActionDictionary_SkPdfObjectType,
  kIccProfileStreamDictionary_SkPdfObjectType,
  kIconFitDictionary_SkPdfObjectType,
  kImportDataActionDictionary_SkPdfObjectType,
  kInkAnnotationDictionary_SkPdfObjectType,
  kInlineLevelStructureElementsDictionary_SkPdfObjectType,
  kInteractiveFormDictionary_SkPdfObjectType,
  kJavascriptActionDictionary_SkPdfObjectType,
  kJavascriptDictionary_SkPdfObjectType,
  kJbig2DecodeFilterDictionary_SkPdfObjectType,
  kLabColorSpaceDictionary_SkPdfObjectType,
  kLaunchActionDictionary_SkPdfObjectType,
  kLineAnnotationDictionary_SkPdfObjectType,
  kListAttributeDictionary_SkPdfObjectType,
  kLzwdecodeAndFlatedecodeFiltersDictionary_SkPdfObjectType,
  kMacOsFileInformationDictionary_SkPdfObjectType,
  kMarkInformationDictionary_SkPdfObjectType,
  kMarkedContentReferenceDictionary_SkPdfObjectType,
  kMarkupAnnotationsDictionary_SkPdfObjectType,
  kMetadataStreamDictionary_SkPdfObjectType,
  kMovieActionDictionary_SkPdfObjectType,
  kMovieActivationDictionary_SkPdfObjectType,
  kMovieAnnotationDictionary_SkPdfObjectType,
  kMovieDictionary_SkPdfObjectType,
  kNameDictionary_SkPdfObjectType,
  kNameTreeNodeDictionary_SkPdfObjectType,
  kNamedActionsDictionary_SkPdfObjectType,
  kNumberTreeNodeDictionary_SkPdfObjectType,
  kObjectReferenceDictionary_SkPdfObjectType,
  kOpiVersionDictionary_SkPdfObjectType,
  kOutlineDictionary_SkPdfObjectType,
  kOutlineItemDictionary_SkPdfObjectType,
  kPDF_XOutputIntentDictionary_SkPdfObjectType,
  kPSXobjectDictionary_SkPdfObjectType,
  kPageLabelDictionary_SkPdfObjectType,
  kPageObjectActionsDictionary_SkPdfObjectType,
  kPageObjectDictionary_SkPdfObjectType,
  kPagePieceDictionary_SkPdfObjectType,
  kPageTreeNodeDictionary_SkPdfObjectType,
  kPopUpAnnotationDictionary_SkPdfObjectType,
  kPrinterMarkAnnotationDictionary_SkPdfObjectType,
  kPrinterMarkFormDictionary_SkPdfObjectType,
  kRadioButtonFieldDictionary_SkPdfObjectType,
  kReferenceDictionary_SkPdfObjectType,
  kRemoteGoToActionDictionary_SkPdfObjectType,
  kResetFormActionDictionary_SkPdfObjectType,
  kResourceDictionary_SkPdfObjectType,
  kRubberStampAnnotationDictionary_SkPdfObjectType,
  kSeparationDictionary_SkPdfObjectType,
  kShadingDictionary_SkPdfObjectType,
  kType1ShadingDictionary_SkPdfObjectType,
  kType2ShadingDictionary_SkPdfObjectType,
  kType3ShadingDictionary_SkPdfObjectType,
  kType4ShadingDictionary_SkPdfObjectType,
  kType5ShadingDictionary_SkPdfObjectType,
  kType6ShadingDictionary_SkPdfObjectType,
  kShadingDictionary__End_SkPdfObjectType,
  kSignatureDictionary_SkPdfObjectType,
  kSoftMaskDictionary_SkPdfObjectType,
  kSoftMaskImageDictionary_SkPdfObjectType,
  kSoundActionDictionary_SkPdfObjectType,
  kSoundAnnotationDictionary_SkPdfObjectType,
  kSoundObjectDictionary_SkPdfObjectType,
  kSourceInformationDictionary_SkPdfObjectType,
  kSquareOrCircleAnnotation_SkPdfObjectType,
  kStandardSecurityHandlerDictionary_SkPdfObjectType,
  kStandardStructureDictionary_SkPdfObjectType,
  kStreamCommonDictionary_SkPdfObjectType,
  kStructureElementAccessDictionary_SkPdfObjectType,
  kStructureElementDictionary_SkPdfObjectType,
  kStructureTreeRootDictionary_SkPdfObjectType,
  kSubmitFormActionDictionary_SkPdfObjectType,
  kTableAttributesDictionary_SkPdfObjectType,
  kTextAnnotationDictionary_SkPdfObjectType,
  kTextFieldDictionary_SkPdfObjectType,
  kThreadActionDictionary_SkPdfObjectType,
  kThreadDictionary_SkPdfObjectType,
  kTransitionDictionary_SkPdfObjectType,
  kTransparencyGroupDictionary_SkPdfObjectType,
  kTrapNetworkAnnotationDictionary_SkPdfObjectType,
  kTrapNetworkAppearanceStreamDictionary_SkPdfObjectType,
  kType0FunctionDictionary_SkPdfObjectType,
  kType10HalftoneDictionary_SkPdfObjectType,
  kType16HalftoneDictionary_SkPdfObjectType,
  kType1HalftoneDictionary_SkPdfObjectType,
  kType1PatternDictionary_SkPdfObjectType,
  kType2FunctionDictionary_SkPdfObjectType,
  kType2PatternDictionary_SkPdfObjectType,
  kType3FunctionDictionary_SkPdfObjectType,
  kType5HalftoneDictionary_SkPdfObjectType,
  kType6HalftoneDictionary_SkPdfObjectType,
  kURIActionDictionary_SkPdfObjectType,
  kURIDictionary_SkPdfObjectType,
  kURLAliasDictionary_SkPdfObjectType,
  kVariableTextFieldDictionary_SkPdfObjectType,
  kViewerPreferencesDictionary_SkPdfObjectType,
  kWebCaptureCommandDictionary_SkPdfObjectType,
  kWebCaptureCommandSettingsDictionary_SkPdfObjectType,
  kWebCaptureDictionary_SkPdfObjectType,
  kWebCaptureImageSetDictionary_SkPdfObjectType,
  kWebCaptureInformationDictionary_SkPdfObjectType,
  kWebCapturePageSetDictionary_SkPdfObjectType,
  kWidgetAnnotationDictionary_SkPdfObjectType,
  kWindowsLaunchActionDictionary_SkPdfObjectType,
  kXObjectDictionary_SkPdfObjectType,
  kImageDictionary_SkPdfObjectType,
  kType1FormDictionary_SkPdfObjectType,
  kXObjectDictionary__End_SkPdfObjectType,
  kDictionary__End_SkPdfObjectType,
  kInteger_SkPdfObjectType,
  kNumber_SkPdfObjectType,
  kInteger__End_SkPdfObjectType,
  kName_SkPdfObjectType,
  kNull_SkPdfObjectType,
  kReference_SkPdfObjectType,
  kStream_SkPdfObjectType,
  kString_SkPdfObjectType,
  kHexString_SkPdfObjectType,
  kString__End_SkPdfObjectType,
  kObject__End_SkPdfObjectType,
};

class SkPdfObject;
class SkPdfNull;
class SkPdfBoolean;
class SkPdfInteger;
class SkPdfNumber;
class SkPdfName;
class SkPdfReference;
class SkPdfArray;
class SkPdfString;
class SkPdfHexString;
class SkPdfDictionary;
class SkPdfStream;
class SkPdfXObjectDictionary;
class SkPdfFontDictionary;
class SkPdfTrueTypeFontDictionary;
class SkPdfStreamCommonDictionary;
class SkPdfLzwdecodeAndFlatedecodeFiltersDictionary;
class SkPdfCcittfaxdecodeFilterDictionary;
class SkPdfJbig2DecodeFilterDictionary;
class SkPdfDctdecodeFilterDictionary;
class SkPdfFileTrailerDictionary;
class SkPdfEncryptionCommonDictionary;
class SkPdfStandardSecurityHandlerDictionary;
class SkPdfCatalogDictionary;
class SkPdfPageTreeNodeDictionary;
class SkPdfPageObjectDictionary;
class SkPdfNameDictionary;
class SkPdfResourceDictionary;
class SkPdfNameTreeNodeDictionary;
class SkPdfNumberTreeNodeDictionary;
class SkPdfFunctionCommonDictionary;
class SkPdfType0FunctionDictionary;
class SkPdfType2FunctionDictionary;
class SkPdfType3FunctionDictionary;
class SkPdfFileSpecificationDictionary;
class SkPdfEmbeddedFileStreamDictionary;
class SkPdfEmbeddedFileParameterDictionary;
class SkPdfMacOsFileInformationDictionary;
class SkPdfGraphicsStateDictionary;
class SkPdfCalgrayColorSpaceDictionary;
class SkPdfCalrgbColorSpaceDictionary;
class SkPdfLabColorSpaceDictionary;
class SkPdfIccProfileStreamDictionary;
class SkPdfDeviceNColorSpaceDictionary;
class SkPdfType1PatternDictionary;
class SkPdfType2PatternDictionary;
class SkPdfShadingDictionary;
class SkPdfType1ShadingDictionary;
class SkPdfType2ShadingDictionary;
class SkPdfType3ShadingDictionary;
class SkPdfType4ShadingDictionary;
class SkPdfType5ShadingDictionary;
class SkPdfType6ShadingDictionary;
class SkPdfImageDictionary;
class SkPdfAlternateImageDictionary;
class SkPdfType1FormDictionary;
class SkPdfGroupAttributesDictionary;
class SkPdfReferenceDictionary;
class SkPdfPSXobjectDictionary;
class SkPdfType1FontDictionary;
class SkPdfType3FontDictionary;
class SkPdfEncodingDictionary;
class SkPdfCIDSystemInfoDictionary;
class SkPdfCIDFontDictionary;
class SkPdfCMapDictionary;
class SkPdfType0FontDictionary;
class SkPdfFontDescriptorDictionary;
class SkPdfCIDFontDescriptorDictionary;
class SkPdfEmbeddedFontStreamDictionary;
class SkPdfType1HalftoneDictionary;
class SkPdfType6HalftoneDictionary;
class SkPdfType10HalftoneDictionary;
class SkPdfType16HalftoneDictionary;
class SkPdfType5HalftoneDictionary;
class SkPdfSoftMaskDictionary;
class SkPdfSoftMaskImageDictionary;
class SkPdfTransparencyGroupDictionary;
class SkPdfViewerPreferencesDictionary;
class SkPdfOutlineDictionary;
class SkPdfOutlineItemDictionary;
class SkPdfPageLabelDictionary;
class SkPdfThreadDictionary;
class SkPdfBeadDictionary;
class SkPdfTransitionDictionary;
class SkPdfAnnotationDictionary;
class SkPdfBorderStyleDictionary;
class SkPdfAppearanceDictionary;
class SkPdfTextAnnotationDictionary;
class SkPdfALinkAnnotationDictionary;
class SkPdfFreeTextAnnotationDictionary;
class SkPdfLineAnnotationDictionary;
class SkPdfSquareOrCircleAnnotation;
class SkPdfMarkupAnnotationsDictionary;
class SkPdfRubberStampAnnotationDictionary;
class SkPdfInkAnnotationDictionary;
class SkPdfPopUpAnnotationDictionary;
class SkPdfFileAttachmentAnnotationDictionary;
class SkPdfSoundAnnotationDictionary;
class SkPdfMovieAnnotationDictionary;
class SkPdfWidgetAnnotationDictionary;
class SkPdfActionDictionary;
class SkPdfAnnotationActionsDictionary;
class SkPdfPageObjectActionsDictionary;
class SkPdfFormFieldActionsDictionary;
class SkPdfDocumentCatalogActionsDictionary;
class SkPdfGoToActionDictionary;
class SkPdfRemoteGoToActionDictionary;
class SkPdfLaunchActionDictionary;
class SkPdfWindowsLaunchActionDictionary;
class SkPdfThreadActionDictionary;
class SkPdfURIActionDictionary;
class SkPdfURIDictionary;
class SkPdfSoundActionDictionary;
class SkPdfMovieActionDictionary;
class SkPdfHideActionDictionary;
class SkPdfNamedActionsDictionary;
class SkPdfInteractiveFormDictionary;
class SkPdfFieldDictionary;
class SkPdfVariableTextFieldDictionary;
class SkPdfAppearanceCharacteristicsDictionary;
class SkPdfCheckboxFieldDictionary;
class SkPdfRadioButtonFieldDictionary;
class SkPdfTextFieldDictionary;
class SkPdfChoiceFieldDictionary;
class SkPdfSignatureDictionary;
class SkPdfSubmitFormActionDictionary;
class SkPdfResetFormActionDictionary;
class SkPdfImportDataActionDictionary;
class SkPdfJavascriptActionDictionary;
class SkPdfFDFTrailerDictionary;
class SkPdfFDFCatalogDictionary;
class SkPdfFDFDictionary;
class SkPdfEncryptedEmbeddedFileStreamDictionary;
class SkPdfJavascriptDictionary;
class SkPdfFDFFieldDictionary;
class SkPdfIconFitDictionary;
class SkPdfFDFPageDictionary;
class SkPdfFDFTemplateDictionary;
class SkPdfFDFNamedPageReferenceDictionary;
class SkPdfFDFFileAnnotationDictionary;
class SkPdfSoundObjectDictionary;
class SkPdfMovieDictionary;
class SkPdfMovieActivationDictionary;
class SkPdfDocumentInformationDictionary;
class SkPdfMetadataStreamDictionary;
class SkPdfComponentsWithMetadataDictionary;
class SkPdfPagePieceDictionary;
class SkPdfApplicationDataDictionary;
class SkPdfStructureTreeRootDictionary;
class SkPdfStructureElementDictionary;
class SkPdfMarkedContentReferenceDictionary;
class SkPdfObjectReferenceDictionary;
class SkPdfStructureElementAccessDictionary;
class SkPdfAttributeObjectDictionary;
class SkPdfMarkInformationDictionary;
class SkPdfArtifactsDictionary;
class SkPdfStandardStructureDictionary;
class SkPdfBlockLevelStructureElementsDictionary;
class SkPdfInlineLevelStructureElementsDictionary;
class SkPdfListAttributeDictionary;
class SkPdfTableAttributesDictionary;
class SkPdfWebCaptureInformationDictionary;
class SkPdfWebCaptureDictionary;
class SkPdfWebCapturePageSetDictionary;
class SkPdfWebCaptureImageSetDictionary;
class SkPdfSourceInformationDictionary;
class SkPdfURLAliasDictionary;
class SkPdfWebCaptureCommandDictionary;
class SkPdfWebCaptureCommandSettingsDictionary;
class SkPdfBoxColorInformationDictionary;
class SkPdfBoxStyleDictionary;
class SkPdfPrinterMarkAnnotationDictionary;
class SkPdfPrinterMarkFormDictionary;
class SkPdfSeparationDictionary;
class SkPdfPDF_XOutputIntentDictionary;
class SkPdfTrapNetworkAnnotationDictionary;
class SkPdfTrapNetworkAppearanceStreamDictionary;
class SkPdfOpiVersionDictionary;
class SkPdfMultiMasterFontDictionary;

#endif  // __DEFINED__SkPdfEnums
