# This shows an example invocation presuming the user has built canvaskit locally.
frames_load_lego_with_local:
	node perf-with-puppeteer.js --canvaskit_js ../../out/canvaskit_wasm/canvaskit.js \
	--canvaskit_wasm ../../out/canvaskit_wasm/canvaskit.wasm --use_gpu \
	--input ../../modules/canvaskit/perf/assets/lego_loader.json \
	--bench_html canvaskit-skottie-frames-load.html
