
out vec4 sk_FragColor;
void fn6() {
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    false;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    false;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    false;
}
void fn7() {
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    sk_FragColor.x = 0.0;
    false;
    fn6();
    fn6();
}
void fn8() {
    fn7();
    fn7();
    fn7();
}
void fn9() {
    fn8();
    fn8();
    fn8();
}
void fnA() {
    fn9();
    fn9();
    fn9();
}
void fnB() {
    fnA();
    fnA();
    fnA();
}
void fnC() {
    fnB();
    fnB();
    fnB();
}
void fnD() {
    fnC();
    fnC();
    fnC();
}
void fnE() {
    fnD();
    fnD();
    fnD();
}
void fnF() {
    fnE();
    fnE();
    fnE();
}
void fnG() {
    fnF();
    fnF();
    fnF();
}
void fnH() {
    fnG();
    fnG();
    fnG();
}
void fnI() {
    fnH();
    fnH();
    fnH();
}
void fnJ() {
    fnI();
    fnI();
    fnI();
}
void fnK() {
    fnJ();
    fnJ();
    fnJ();
}
void fnL() {
    fnK();
    fnK();
    fnK();
}
void fnM() {
    fnL();
    fnL();
    fnL();
}
void fnN() {
    fnM();
    fnM();
    fnM();
}
void main() {
    fnN();
}
