SOURCE := \
    Sk64.cpp \
    SkAlphaRuns.cpp \
    SkBitmap.cpp \
    SkBitmapProcShader.cpp \
    SkBitmapProcState.cpp \
    SkBitmapProcState_matrixProcs.cpp \
    SkBitmapSampler.cpp \
    SkBitmap_scroll.cpp \
    SkBlitRow_D16.cpp \
    SkBlitRow_D4444.cpp \
    SkBlitter.cpp \
    SkBlitter_4444.cpp \
    SkBlitter_A1.cpp \
    SkBlitter_A8.cpp \
    SkBlitter_ARGB32.cpp \
    SkBlitter_RGB16.cpp \
    SkBlitter_Sprite.cpp \
    SkBuffer.cpp \
    SkCanvas.cpp \
    SkChunkAlloc.cpp \
    SkColor.cpp \
    SkColorFilter.cpp \
    SkColorTable.cpp \
    SkComposeShader.cpp \
    SkCordic.cpp \
    SkCubicClipper.cpp \
    SkDebug.cpp \
    SkDebug_stdio.cpp \
    SkDeque.cpp \
    SkDevice.cpp \
    SkDither.cpp \
    SkDraw.cpp \
    SkEdge.cpp \
    SkFilterProc.cpp \
    SkFlattenable.cpp \
    SkFloat.cpp \
    SkFloatBits.cpp \
    SkGeometry.cpp \
    SkGlobals.cpp \
    SkGlyphCache.cpp \
    SkGraphics.cpp \
    SkMMapStream.cpp \
    SkMask.cpp \
    SkMaskFilter.cpp \
    SkMath.cpp \
    SkMatrix.cpp \
    SkMemory_stdlib.cpp \
    SkPackBits.cpp \
    SkPaint.cpp \
    SkPath.cpp \
    SkPathEffect.cpp \
    SkPathHeap.cpp \
    SkPathMeasure.cpp \
    SkPicture.cpp \
    SkPictureFlat.cpp \
    SkPicturePlayback.cpp \
    SkPictureRecord.cpp \
    SkPixelRef.cpp \
    SkPoint.cpp \
    SkPtrRecorder.cpp \
    SkQuadClipper.cpp \
    SkRasterizer.cpp \
    SkRect.cpp \
    SkRefCnt.cpp \
    SkRegion.cpp \
    SkRegion_path.cpp \
    SkScalerContext.cpp \
    SkScan.cpp \
    SkScan_AntiPath.cpp \
    SkScan_Antihair.cpp \
    SkScan_Hairline.cpp \
    SkScan_Path.cpp \
    SkShader.cpp \
    SkSpriteBlitter_ARGB32.cpp \
    SkSpriteBlitter_RGB16.cpp \
    SkStream.cpp \
    SkString.cpp \
    SkStroke.cpp \
    SkStrokerPriv.cpp \
    SkTSearch.cpp \
    SkTypeface.cpp \
    SkUnPreMultiply.cpp \
    SkUtils.cpp \
    SkWriter32.cpp \
    SkXfermode.cpp
