               OpCapability Shader
          %5 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %sk_LocalInvocationID
               OpExecutionMode %main LocalSize 64 1 1

               ; Debug Information
               OpName %ssbo "ssbo"                  ; id %9
               OpMemberName %ssbo 0 "globalCounter"
               OpName %sk_LocalInvocationID "sk_LocalInvocationID"  ; id %11
               OpName %localCounter "localCounter"                  ; id %14
               OpName %main "main"                                  ; id %6

               ; Annotations
               OpMemberDecorate %ssbo 0 Offset 0
               OpMemberDecorate %ssbo 0 RelaxedPrecision
               OpDecorate %ssbo BufferBlock
               OpDecorate %7 Binding 0
               OpDecorate %7 DescriptorSet 0
               OpDecorate %sk_LocalInvocationID BuiltIn LocalInvocationId

               ; Types, variables and constants
        %int = OpTypeInt 32 1
%_ptr_Input_int = OpTypePointer Input %int
       %uint = OpTypeInt 32 0
       %ssbo = OpTypeStruct %uint                   ; BufferBlock
%_ptr_Uniform_ssbo = OpTypePointer Uniform %ssbo
          %7 = OpVariable %_ptr_Uniform_ssbo Uniform    ; Binding 0, DescriptorSet 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%sk_LocalInvocationID = OpVariable %_ptr_Input_v3uint Input     ; BuiltIn LocalInvocationId
%_ptr_Workgroup_uint = OpTypePointer Workgroup %uint
%localCounter = OpVariable %_ptr_Workgroup_uint Workgroup
       %void = OpTypeVoid
         %17 = OpTypeFunction %void
     %uint_0 = OpConstant %uint 0
       %bool = OpTypeBool
     %uint_2 = OpConstant %uint 2
   %uint_264 = OpConstant %uint 264
     %uint_1 = OpConstant %uint 1
    %uint_10 = OpConstant %uint 10
     %uint_5 = OpConstant %uint 5
      %int_0 = OpConstant %int 0
%_ptr_Uniform_uint = OpTypePointer Uniform %uint


               ; Function main
       %main = OpFunction %void None %17

         %18 = OpLabel
         %19 =   OpLoad %v3uint %sk_LocalInvocationID
         %20 =   OpCompositeExtract %uint %19 0
         %22 =   OpIEqual %bool %20 %uint_0
                 OpSelectionMerge %25 None
                 OpBranchConditional %22 %24 %25

         %24 =     OpLabel
                     OpAtomicStore %localCounter %uint_2 %uint_0 %uint_0
                     OpBranch %25

         %25 = OpLabel
                 OpControlBarrier %uint_2 %uint_2 %uint_264
         %29 =   OpAtomicIAdd %uint %localCounter %uint_2 %uint_0 %uint_1
         %31 =   OpAtomicUMin %uint %localCounter %uint_2 %uint_0 %uint_10
         %33 =   OpAtomicUMax %uint %localCounter %uint_2 %uint_0 %uint_5
                 OpControlBarrier %uint_2 %uint_2 %uint_264
         %35 =   OpLoad %v3uint %sk_LocalInvocationID
         %36 =   OpCompositeExtract %uint %35 0
         %37 =   OpIEqual %bool %36 %uint_0
                 OpSelectionMerge %39 None
                 OpBranchConditional %37 %38 %39

         %38 =     OpLabel
         %42 =       OpAccessChain %_ptr_Uniform_uint %7 %int_0
         %44 =       OpAtomicLoad %uint %localCounter %uint_2 %uint_0
         %40 =       OpAtomicIAdd %uint %42 %uint_1 %uint_0 %44
                     OpBranch %39

         %39 = OpLabel
                 OpReturn
               OpFunctionEnd
