               OpCapability Shader
          %5 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 64 1 1

               ; Debug Information
               OpName %main "main"                  ; id %6

               ; Types, variables and constants
        %int = OpTypeInt 32 1
%_ptr_Input_int = OpTypePointer Input %int
       %void = OpTypeVoid
          %8 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
     %uint_2 = OpConstant %uint 2
   %uint_264 = OpConstant %uint 264
    %uint_72 = OpConstant %uint 72


               ; Function main
       %main = OpFunction %void None %8

          %9 = OpLabel
                 OpControlBarrier %uint_2 %uint_2 %uint_264
                 OpControlBarrier %uint_2 %uint_2 %uint_72
                 OpReturn
               OpFunctionEnd
