               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 64 1 1

               ; Debug Information
               OpName %main "main"                  ; id %2

               ; Types, variables and constants
       %void = OpTypeVoid
          %4 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
     %uint_2 = OpConstant %uint 2
   %uint_264 = OpConstant %uint 264
    %uint_72 = OpConstant %uint 72


               ; Function main
       %main = OpFunction %void None %4

          %5 = OpLabel
                 OpControlBarrier %uint_2 %uint_2 %uint_264
                 OpControlBarrier %uint_2 %uint_2 %uint_72
                 OpReturn
               OpFunctionEnd
