               OpCapability ImageQuery
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %sk_GlobalInvocationID
               OpExecutionMode %main LocalSize 16 16 1
               OpName %sk_GlobalInvocationID "sk_GlobalInvocationID"
               OpName %src "src"
               OpName %dest "dest"
               OpName %desaturate_vTT "desaturate_vTT"
               OpName %color "color"
               OpName %main "main"
               OpDecorate %sk_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %src Binding 0
               OpDecorate %src DescriptorSet 0
               OpDecorate %dest Binding 1
               OpDecorate %dest DescriptorSet 0
               OpDecorate %color RelaxedPrecision
               OpDecorate %21 RelaxedPrecision
               OpDecorate %22 RelaxedPrecision
               OpDecorate %26 RelaxedPrecision
               OpDecorate %27 RelaxedPrecision
               OpDecorate %33 RelaxedPrecision
               OpDecorate %34 RelaxedPrecision
               OpDecorate %35 RelaxedPrecision
               OpDecorate %36 RelaxedPrecision
               OpDecorate %47 RelaxedPrecision
               OpDecorate %55 RelaxedPrecision
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%sk_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input
      %float = OpTypeFloat 32
         %10 = OpTypeImage %float 2D 0 0 0 2 Rgba32f
%_ptr_UniformConstant_10 = OpTypePointer UniformConstant %10
        %src = OpVariable %_ptr_UniformConstant_10 UniformConstant
       %dest = OpVariable %_ptr_UniformConstant_10 UniformConstant
       %void = OpTypeVoid
         %14 = OpTypeFunction %void %_ptr_UniformConstant_10 %_ptr_UniformConstant_10
    %v4float = OpTypeVector %float 4
%_ptr_Function_v4float = OpTypePointer Function %v4float
     %v2uint = OpTypeVector %uint 2
    %v3float = OpTypeVector %float 3
%float_0_219999999 = OpConstant %float 0.219999999
%float_0_670000017 = OpConstant %float 0.670000017
%float_0_109999999 = OpConstant %float 0.109999999
         %32 = OpConstantComposite %v3float %float_0_219999999 %float_0_670000017 %float_0_109999999
         %39 = OpTypeFunction %void
       %bool = OpTypeBool
      %false = OpConstantFalse %bool
%desaturate_vTT = OpFunction %void None %14
         %15 = OpFunctionParameter %_ptr_UniformConstant_10
         %16 = OpFunctionParameter %_ptr_UniformConstant_10
         %17 = OpLabel
      %color = OpVariable %_ptr_Function_v4float Function
         %22 = OpLoad %10 %15
         %23 = OpLoad %v3uint %sk_GlobalInvocationID
         %24 = OpVectorShuffle %v2uint %23 %23 0 1
         %21 = OpImageRead %v4float %22 %24
               OpStore %color %21
         %27 = OpVectorShuffle %v3float %21 %21 0 1 2
         %26 = OpDot %float %27 %32
         %33 = OpCompositeConstruct %v3float %26 %26 %26
         %34 = OpLoad %v4float %color
         %35 = OpVectorShuffle %v4float %34 %33 4 5 6 3
               OpStore %color %35
         %36 = OpLoad %10 %16
         %37 = OpLoad %v3uint %sk_GlobalInvocationID
         %38 = OpVectorShuffle %v2uint %37 %37 0 1
               OpImageWrite %36 %38 %35
               OpReturn
               OpFunctionEnd
       %main = OpFunction %void None %39
         %40 = OpLabel
         %43 = OpLoad %v3uint %sk_GlobalInvocationID
         %44 = OpCompositeExtract %uint %43 0
         %47 = OpLoad %10 %src
         %46 = OpImageQuerySize %v2uint %47
         %45 = OpCompositeExtract %uint %46 0
         %48 = OpULessThan %bool %44 %45
               OpSelectionMerge %50 None
               OpBranchConditional %48 %49 %50
         %49 = OpLabel
         %51 = OpLoad %v3uint %sk_GlobalInvocationID
         %52 = OpCompositeExtract %uint %51 1
         %55 = OpLoad %10 %src
         %54 = OpImageQuerySize %v2uint %55
         %53 = OpCompositeExtract %uint %54 1
         %56 = OpULessThan %bool %52 %53
               OpBranch %50
         %50 = OpLabel
         %57 = OpPhi %bool %false %40 %56 %49
               OpSelectionMerge %59 None
               OpBranchConditional %57 %58 %59
         %58 = OpLabel
         %60 = OpFunctionCall %void %desaturate_vTT %src %dest
               OpBranch %59
         %59 = OpLabel
               OpReturn
               OpFunctionEnd
