### Compilation failed:

error: 10: unsupported intrinsic '$pure uint textureWidth($genTexture2D t)'
    if (sk_GlobalInvocationID.x < textureWidth(src) && sk_GlobalInvocationID.y < textureHeight(src)) {
                                  ^^^^^^^^^^^^^^^^^
error: 10: unsupported intrinsic '$pure uint textureHeight($genTexture2D t)'
    if (sk_GlobalInvocationID.x < textureWidth(src) && sk_GlobalInvocationID.y < textureHeight(src)) {
                                                                                 ^^^^^^^^^^^^^^^^^^
error: 11: unsupported intrinsic '$pure half4 textureRead($readableTexture2D t, uint2 pos)'
        textureWrite(dest, sk_GlobalInvocationID.xy, desaturate(textureRead(src, sk_GlobalInvocationID.xy)));
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: 11: unsupported intrinsic 'void textureWrite($writableTexture2D t, uint2 pos, half4 color)'
        textureWrite(dest, sk_GlobalInvocationID.xy, desaturate(textureRead(src, sk_GlobalInvocationID.xy)));
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4 errors
