               OpCapability ImageQuery
               OpCapability Shader
          %5 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %sk_GlobalInvocationID
               OpExecutionMode %main LocalSize 16 16 1

               ; Debug Information
               OpName %sk_GlobalInvocationID "sk_GlobalInvocationID"    ; id %7
               OpName %src "src"                                        ; id %11
               OpName %dest "dest"                                      ; id %15
               OpName %main "main"                                      ; id %6
               OpName %_0_color "_0_color"                              ; id %42

               ; Annotations
               OpDecorate %sk_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %src Binding 0
               OpDecorate %src DescriptorSet 0
               OpDecorate %dest Binding 1
               OpDecorate %dest DescriptorSet 0
               OpDecorate %28 RelaxedPrecision
               OpDecorate %37 RelaxedPrecision
               OpDecorate %_0_color RelaxedPrecision
               OpDecorate %45 RelaxedPrecision
               OpDecorate %46 RelaxedPrecision
               OpDecorate %49 RelaxedPrecision
               OpDecorate %50 RelaxedPrecision
               OpDecorate %56 RelaxedPrecision
               OpDecorate %57 RelaxedPrecision
               OpDecorate %58 RelaxedPrecision
               OpDecorate %59 RelaxedPrecision

               ; Types, variables and constants
        %int = OpTypeInt 32 1
%_ptr_Input_int = OpTypePointer Input %int
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%sk_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input    ; BuiltIn GlobalInvocationId
      %float = OpTypeFloat 32
         %13 = OpTypeImage %float 2D 0 0 0 1 Unknown
%_ptr_UniformConstant_13 = OpTypePointer UniformConstant %13
        %src = OpVariable %_ptr_UniformConstant_13 UniformConstant  ; Binding 0, DescriptorSet 0
         %16 = OpTypeImage %float 2D 0 0 0 2 Rgba8
%_ptr_UniformConstant_16 = OpTypePointer UniformConstant %16
       %dest = OpVariable %_ptr_UniformConstant_16 UniformConstant  ; Binding 1, DescriptorSet 0
       %void = OpTypeVoid
         %19 = OpTypeFunction %void
       %bool = OpTypeBool
      %false = OpConstantFalse %bool
     %v2uint = OpTypeVector %uint 2
      %int_0 = OpConstant %int 0
    %v4float = OpTypeVector %float 4
%_ptr_Function_v4float = OpTypePointer Function %v4float
    %v3float = OpTypeVector %float 3
%float_0_219999999 = OpConstant %float 0.219999999
%float_0_670000017 = OpConstant %float 0.670000017
%float_0_109999999 = OpConstant %float 0.109999999
         %55 = OpConstantComposite %v3float %float_0_219999999 %float_0_670000017 %float_0_109999999


               ; Function main
       %main = OpFunction %void None %19

         %20 = OpLabel
   %_0_color =   OpVariable %_ptr_Function_v4float Function     ; RelaxedPrecision
         %23 =   OpLoad %v3uint %sk_GlobalInvocationID
         %24 =   OpCompositeExtract %uint %23 0
         %28 =   OpLoad %13 %src                    ; RelaxedPrecision
         %27 =   OpImageQuerySizeLod %v2uint %28 %int_0
         %25 =   OpCompositeExtract %uint %27 0
         %30 =   OpULessThan %bool %24 %25
                 OpSelectionMerge %32 None
                 OpBranchConditional %30 %31 %32

         %31 =     OpLabel
         %33 =       OpLoad %v3uint %sk_GlobalInvocationID
         %34 =       OpCompositeExtract %uint %33 1
         %37 =       OpLoad %13 %src                ; RelaxedPrecision
         %36 =       OpImageQuerySizeLod %v2uint %37 %int_0
         %35 =       OpCompositeExtract %uint %36 1
         %38 =       OpULessThan %bool %34 %35
                     OpBranch %32

         %32 = OpLabel
         %39 =   OpPhi %bool %false %20 %38 %31
                 OpSelectionMerge %41 None
                 OpBranchConditional %39 %40 %41

         %40 =     OpLabel
         %46 =       OpLoad %13 %src                ; RelaxedPrecision
         %47 =       OpLoad %v3uint %sk_GlobalInvocationID
         %48 =       OpVectorShuffle %v2uint %47 %47 0 1
         %45 =       OpImageFetch %v4float %46 %48 Lod %int_0   ; RelaxedPrecision
                     OpStore %_0_color %45
         %50 =       OpVectorShuffle %v3float %45 %45 0 1 2     ; RelaxedPrecision
         %49 =       OpDot %float %50 %55                       ; RelaxedPrecision
         %56 =       OpCompositeConstruct %v3float %49 %49 %49  ; RelaxedPrecision
         %57 =       OpLoad %v4float %_0_color                  ; RelaxedPrecision
         %58 =       OpVectorShuffle %v4float %57 %56 4 5 6 3   ; RelaxedPrecision
                     OpStore %_0_color %58
         %59 =       OpLoad %16 %dest               ; RelaxedPrecision
         %60 =       OpLoad %v3uint %sk_GlobalInvocationID
         %61 =       OpVectorShuffle %v2uint %60 %60 0 1
                     OpImageWrite %59 %61 %58
                     OpBranch %41

         %41 = OpLabel
                 OpReturn
               OpFunctionEnd
