               OpCapability ImageQuery
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %sk_GlobalInvocationID
               OpExecutionMode %main LocalSize 16 16 1

               ; Debug Information
               OpName %sk_GlobalInvocationID "sk_GlobalInvocationID"    ; id %3
               OpName %dest "dest"                                      ; id %7
               OpName %main "main"                                      ; id %2
               OpName %pixel "pixel"                                    ; id %14
               OpName %max_x "max_x"                                    ; id %20
               OpName %max_y "max_y"                                    ; id %23
               OpName %x "x"                                            ; id %24
               OpName %y "y"                                            ; id %40
               OpName %ray_origin "ray_origin"                          ; id %54
               OpName %ray_target "ray_target"                          ; id %59
               OpName %sphere_center "sphere_center"                    ; id %63
               OpName %sphere_radius "sphere_radius"                    ; id %66
               OpName %t_minus_c "t_minus_c"                            ; id %67
               OpName %b "b"                                            ; id %69
               OpName %c "c"                                            ; id %71
               OpName %bsqmc "bsqmc"                                    ; id %75

               ; Annotations
               OpDecorate %sk_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %dest Binding 0
               OpDecorate %dest DescriptorSet 0
               OpDecorate %pixel RelaxedPrecision
               OpDecorate %32 RelaxedPrecision
               OpDecorate %37 RelaxedPrecision
               OpDecorate %46 RelaxedPrecision
               OpDecorate %51 RelaxedPrecision
               OpDecorate %84 RelaxedPrecision
               OpDecorate %87 RelaxedPrecision

               ; Types, variables and constants
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%sk_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input    ; BuiltIn GlobalInvocationId
      %float = OpTypeFloat 32
          %9 = OpTypeImage %float 2D 0 0 0 2 Rgba32f
%_ptr_UniformConstant_9 = OpTypePointer UniformConstant %9
       %dest = OpVariable %_ptr_UniformConstant_9 UniformConstant   ; Binding 0, DescriptorSet 0
       %void = OpTypeVoid
         %12 = OpTypeFunction %void
    %v4float = OpTypeVector %float 4
%_ptr_Function_v4float = OpTypePointer Function %v4float
    %float_0 = OpConstant %float 0
    %float_1 = OpConstant %float 1
         %19 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_1
%_ptr_Function_float = OpTypePointer Function %float
    %float_5 = OpConstant %float 5
     %uint_2 = OpConstant %uint 2
     %v2uint = OpTypeVector %uint 2
    %v3float = OpTypeVector %float 3
%_ptr_Function_v3float = OpTypePointer Function %v3float
   %float_n1 = OpConstant %float -1
         %58 = OpConstantComposite %v3float %float_0 %float_0 %float_n1
  %float_n10 = OpConstant %float -10
         %65 = OpConstantComposite %v3float %float_0 %float_0 %float_n10
       %bool = OpTypeBool
%float_0_400000006 = OpConstant %float 0.400000006
         %83 = OpConstantComposite %v4float %float_0_400000006 %float_0_400000006 %float_1 %float_1


               ; Function main
       %main = OpFunction %void None %12

         %13 = OpLabel
      %pixel =   OpVariable %_ptr_Function_v4float Function     ; RelaxedPrecision
      %max_x =   OpVariable %_ptr_Function_float Function
      %max_y =   OpVariable %_ptr_Function_float Function
          %x =   OpVariable %_ptr_Function_float Function
          %y =   OpVariable %_ptr_Function_float Function
 %ray_origin =   OpVariable %_ptr_Function_v3float Function
 %ray_target =   OpVariable %_ptr_Function_v3float Function
%sphere_center =   OpVariable %_ptr_Function_v3float Function
%sphere_radius =   OpVariable %_ptr_Function_float Function
  %t_minus_c =   OpVariable %_ptr_Function_v3float Function
          %b =   OpVariable %_ptr_Function_float Function
          %c =   OpVariable %_ptr_Function_float Function
      %bsqmc =   OpVariable %_ptr_Function_float Function
                 OpStore %pixel %19
                 OpStore %max_x %float_5
                 OpStore %max_y %float_5
         %25 =   OpLoad %v3uint %sk_GlobalInvocationID
         %26 =   OpCompositeExtract %uint %25 0
         %28 =   OpIMul %uint %26 %uint_2
         %32 =   OpLoad %9 %dest                    ; RelaxedPrecision
         %31 =   OpImageQuerySize %v2uint %32
         %29 =   OpCompositeExtract %uint %31 0
         %33 =   OpISub %uint %28 %29
         %34 =   OpConvertUToF %float %33
         %37 =   OpLoad %9 %dest                    ; RelaxedPrecision
         %36 =   OpImageQuerySize %v2uint %37
         %35 =   OpCompositeExtract %uint %36 0
         %38 =   OpConvertUToF %float %35
         %39 =   OpFDiv %float %34 %38
                 OpStore %x %39
         %41 =   OpLoad %v3uint %sk_GlobalInvocationID
         %42 =   OpCompositeExtract %uint %41 1
         %43 =   OpIMul %uint %42 %uint_2
         %46 =   OpLoad %9 %dest                    ; RelaxedPrecision
         %45 =   OpImageQuerySize %v2uint %46
         %44 =   OpCompositeExtract %uint %45 1
         %47 =   OpISub %uint %43 %44
         %48 =   OpConvertUToF %float %47
         %51 =   OpLoad %9 %dest                    ; RelaxedPrecision
         %50 =   OpImageQuerySize %v2uint %51
         %49 =   OpCompositeExtract %uint %50 1
         %52 =   OpConvertUToF %float %49
         %53 =   OpFDiv %float %48 %52
                 OpStore %y %53
                 OpStore %ray_origin %58
         %60 =   OpFMul %float %39 %float_5
         %61 =   OpFMul %float %53 %float_5
         %62 =   OpCompositeConstruct %v3float %60 %61 %float_0
                 OpStore %ray_target %62
                 OpStore %sphere_center %65
                 OpStore %sphere_radius %float_1
         %68 =   OpFSub %v3float %62 %65
                 OpStore %t_minus_c %68
         %70 =   OpDot %float %58 %68
                 OpStore %b %70
         %72 =   OpDot %float %68 %68
         %73 =   OpFMul %float %float_1 %float_1
         %74 =   OpFSub %float %72 %73
                 OpStore %c %74
         %76 =   OpFMul %float %70 %70
         %77 =   OpFSub %float %76 %74
                 OpStore %bsqmc %77
         %78 =   OpFOrdGreaterThanEqual %bool %77 %float_0
                 OpSelectionMerge %81 None
                 OpBranchConditional %78 %80 %81

         %80 =     OpLabel
                     OpStore %pixel %83
                     OpBranch %81

         %81 = OpLabel
         %84 =   OpLoad %9 %dest                    ; RelaxedPrecision
         %85 =   OpLoad %v3uint %sk_GlobalInvocationID
         %86 =   OpVectorShuffle %v2uint %85 %85 0 1
         %87 =   OpLoad %v4float %pixel             ; RelaxedPrecision
                 OpImageWrite %84 %86 %87
                 OpReturn
               OpFunctionEnd
