               OpCapability Shader
          %5 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %sk_GlobalInvocationID
               OpExecutionMode %main LocalSize 256 1 1

               ; Debug Information
               OpName %inputs "inputs"              ; id %11
               OpMemberName %inputs 0 "in_data"
               OpName %outputs "outputs"            ; id %14
               OpMemberName %outputs 0 "out_data"
               OpName %sk_GlobalInvocationID "sk_GlobalInvocationID"    ; id %16
               OpName %shared_data "shared_data"                        ; id %20
               OpName %store_vIf "store_vIf"                            ; id %6
               OpName %main "main"                                      ; id %7
               OpName %id "id"                                          ; id %37
               OpName %rd_id "rd_id"                                    ; id %40
               OpName %wr_id "wr_id"                                    ; id %41
               OpName %mask "mask"                                      ; id %42
               OpName %step "step"                                      ; id %62

               ; Annotations
               OpDecorate %_runtimearr_float ArrayStride 4
               OpMemberDecorate %inputs 0 Offset 0
               OpDecorate %inputs BufferBlock
               OpDecorate %8 Binding 0
               OpDecorate %8 DescriptorSet 0
               OpMemberDecorate %outputs 0 Offset 0
               OpDecorate %outputs BufferBlock
               OpDecorate %13 Binding 1
               OpDecorate %13 DescriptorSet 0
               OpDecorate %sk_GlobalInvocationID BuiltIn GlobalInvocationId

               ; Types, variables and constants
        %int = OpTypeInt 32 1
%_ptr_Input_int = OpTypePointer Input %int
      %float = OpTypeFloat 32
%_runtimearr_float = OpTypeRuntimeArray %float      ; ArrayStride 4
     %inputs = OpTypeStruct %_runtimearr_float      ; BufferBlock
%_ptr_Uniform_inputs = OpTypePointer Uniform %inputs
          %8 = OpVariable %_ptr_Uniform_inputs Uniform  ; Binding 0, DescriptorSet 0
    %outputs = OpTypeStruct %_runtimearr_float          ; BufferBlock
%_ptr_Uniform_outputs = OpTypePointer Uniform %outputs
         %13 = OpVariable %_ptr_Uniform_outputs Uniform     ; Binding 1, DescriptorSet 0
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%sk_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input    ; BuiltIn GlobalInvocationId
    %int_512 = OpConstant %int 512
%_arr_float_int_512 = OpTypeArray %float %int_512
%_ptr_Workgroup__arr_float_int_512 = OpTypePointer Workgroup %_arr_float_int_512
%shared_data = OpVariable %_ptr_Workgroup__arr_float_int_512 Workgroup
       %void = OpTypeVoid
%_ptr_Function_uint = OpTypePointer Function %uint
%_ptr_Function_float = OpTypePointer Function %float
         %27 = OpTypeFunction %void %_ptr_Function_uint %_ptr_Function_float
%_ptr_Workgroup_float = OpTypePointer Workgroup %float
         %35 = OpTypeFunction %void
      %int_0 = OpConstant %int 0
     %uint_2 = OpConstant %uint 2
%_ptr_Uniform_float = OpTypePointer Uniform %float
     %uint_1 = OpConstant %uint 1
   %uint_264 = OpConstant %uint 264
     %uint_0 = OpConstant %uint 0
     %uint_9 = OpConstant %uint 9
       %bool = OpTypeBool


               ; Function store_vIf
  %store_vIf = OpFunction %void None %27
         %28 = OpFunctionParameter %_ptr_Function_uint
         %29 = OpFunctionParameter %_ptr_Function_float

         %30 = OpLabel
         %31 =   OpLoad %float %29
         %32 =   OpLoad %uint %28
         %33 =   OpAccessChain %_ptr_Workgroup_float %shared_data %32
                 OpStore %33 %31
                 OpReturn
               OpFunctionEnd


               ; Function main
       %main = OpFunction %void None %35

         %36 = OpLabel
         %id =   OpVariable %_ptr_Function_uint Function
      %rd_id =   OpVariable %_ptr_Function_uint Function
      %wr_id =   OpVariable %_ptr_Function_uint Function
       %mask =   OpVariable %_ptr_Function_uint Function
       %step =   OpVariable %_ptr_Function_uint Function
         %87 =   OpVariable %_ptr_Function_uint Function
         %93 =   OpVariable %_ptr_Function_float Function
         %38 =   OpLoad %v3uint %sk_GlobalInvocationID
         %39 =   OpCompositeExtract %uint %38 0
                 OpStore %id %39
         %45 =   OpIMul %uint %39 %uint_2
         %46 =   OpAccessChain %_ptr_Uniform_float %8 %int_0 %45
         %48 =   OpLoad %float %46
         %49 =   OpIMul %uint %39 %uint_2
         %50 =   OpAccessChain %_ptr_Workgroup_float %shared_data %49
                 OpStore %50 %48
         %51 =   OpLoad %uint %id
         %52 =   OpIMul %uint %51 %uint_2
         %54 =   OpIAdd %uint %52 %uint_1
         %55 =   OpAccessChain %_ptr_Uniform_float %8 %int_0 %54
         %56 =   OpLoad %float %55
         %57 =   OpLoad %uint %id
         %58 =   OpIMul %uint %57 %uint_2
         %59 =   OpIAdd %uint %58 %uint_1
         %60 =   OpAccessChain %_ptr_Workgroup_float %shared_data %59
                 OpStore %60 %56
                 OpControlBarrier %uint_2 %uint_2 %uint_264
                 OpStore %step %uint_0
                 OpBranch %64

         %64 = OpLabel
                 OpLoopMerge %68 %67 None
                 OpBranch %65

         %65 =     OpLabel
         %69 =       OpLoad %uint %step
         %71 =       OpULessThan %bool %69 %uint_9
                     OpBranchConditional %71 %66 %68

         %66 =         OpLabel
         %73 =           OpLoad %uint %step
         %74 =           OpShiftLeftLogical %uint %uint_1 %73
         %75 =           OpISub %uint %74 %uint_1
                         OpStore %mask %75
         %76 =           OpLoad %uint %id
         %77 =           OpLoad %uint %step
         %78 =           OpShiftRightLogical %uint %76 %77
         %79 =           OpLoad %uint %step
         %80 =           OpIAdd %uint %79 %uint_1
         %81 =           OpShiftLeftLogical %uint %78 %80
         %82 =           OpIAdd %uint %81 %75
                         OpStore %rd_id %82
         %83 =           OpIAdd %uint %82 %uint_1
         %84 =           OpLoad %uint %id
         %85 =           OpBitwiseAnd %uint %84 %75
         %86 =           OpIAdd %uint %83 %85
                         OpStore %wr_id %86
                         OpStore %87 %86
         %88 =           OpAccessChain %_ptr_Workgroup_float %shared_data %86
         %89 =           OpLoad %float %88
         %90 =           OpAccessChain %_ptr_Workgroup_float %shared_data %82
         %91 =           OpLoad %float %90
         %92 =           OpFAdd %float %89 %91
                         OpStore %93 %92
         %94 =           OpFunctionCall %void %store_vIf %87 %93
                         OpControlBarrier %uint_2 %uint_2 %uint_264
                         OpBranch %67

         %67 =   OpLabel
         %95 =     OpLoad %uint %step
         %96 =     OpIAdd %uint %95 %uint_1
                   OpStore %step %96
                   OpBranch %64

         %68 = OpLabel
         %97 =   OpLoad %uint %id
         %98 =   OpIMul %uint %97 %uint_2
         %99 =   OpAccessChain %_ptr_Workgroup_float %shared_data %98
        %100 =   OpLoad %float %99
        %101 =   OpLoad %uint %id
        %102 =   OpIMul %uint %101 %uint_2
        %103 =   OpAccessChain %_ptr_Uniform_float %13 %int_0 %102
                 OpStore %103 %100
        %104 =   OpLoad %uint %id
        %105 =   OpIMul %uint %104 %uint_2
        %106 =   OpIAdd %uint %105 %uint_1
        %107 =   OpAccessChain %_ptr_Workgroup_float %shared_data %106
        %108 =   OpLoad %float %107
        %109 =   OpLoad %uint %id
        %110 =   OpIMul %uint %109 %uint_2
        %111 =   OpIAdd %uint %110 %uint_1
        %112 =   OpAccessChain %_ptr_Uniform_float %13 %int_0 %111
                 OpStore %112 %108
                 OpReturn
               OpFunctionEnd
