

/**************************************************************************************************
 *** This file was autogenerated from GrDSLFPTest_SwitchStatement.fp; do not modify.
 **************************************************************************************************/
#ifndef GrDSLFPTest_SwitchStatement_DEFINED
#define GrDSLFPTest_SwitchStatement_DEFINED

#include "include/core/SkM44.h"
#include "include/core/SkTypes.h"


#include "src/gpu/GrFragmentProcessor.h"

class GrDSLFPTest_SwitchStatement : public GrFragmentProcessor {
public:
    static std::unique_ptr<GrFragmentProcessor> Make(int32_t ten) {
        return std::unique_ptr<GrFragmentProcessor>(new GrDSLFPTest_SwitchStatement(ten));
    }
    GrDSLFPTest_SwitchStatement(const GrDSLFPTest_SwitchStatement& src);
    std::unique_ptr<GrFragmentProcessor> clone() const override;
    const char* name() const override { return "DSLFPTest_SwitchStatement"; }
    int32_t ten;
private:
    GrDSLFPTest_SwitchStatement(int32_t ten)
    : INHERITED(kGrDSLFPTest_SwitchStatement_ClassID, kNone_OptimizationFlags)
    , ten(ten) {
    }
    std::unique_ptr<GrGLSLFragmentProcessor> onMakeProgramImpl() const override;
    void onGetGLSLProcessorKey(const GrShaderCaps&, GrProcessorKeyBuilder*) const override;
    bool onIsEqual(const GrFragmentProcessor&) const override;
#if GR_TEST_UTILS
    SkString onDumpInfo() const override;
#endif
    GR_DECLARE_FRAGMENT_PROCESSOR_TEST
    using INHERITED = GrFragmentProcessor;
};
#endif
