

/**************************************************************************************************
 *** This file was autogenerated from GrDSLFPTest_Swizzle.fp; do not modify.
 **************************************************************************************************/
/* TODO(skia:11854): DSLCPPCodeGenerator is currently a work in progress. */
#include "GrDSLFPTest_Swizzle.h"

#include "src/core/SkUtils.h"
#include "src/gpu/GrTexture.h"
#include "src/gpu/glsl/GrGLSLFragmentProcessor.h"
#include "src/gpu/glsl/GrGLSLFragmentShaderBuilder.h"
#include "src/gpu/glsl/GrGLSLProgramBuilder.h"
#include "src/sksl/SkSLCPP.h"
#include "src/sksl/SkSLUtil.h"
#include "src/sksl/dsl/priv/DSLFPs.h"
#include "src/sksl/dsl/priv/DSLWriter.h"

#if defined(__clang__)
#pragma clang diagnostic ignored "-Wcomma"
#endif

class GrGLSLDSLFPTest_Swizzle : public GrGLSLFragmentProcessor {
public:
    GrGLSLDSLFPTest_Swizzle() {}
    void emitCode(EmitArgs& args) override {
        const GrDSLFPTest_Swizzle& _outer = args.fFp.cast<GrDSLFPTest_Swizzle>();
        (void) _outer;

        using namespace SkSL::dsl;
        StartFragmentProcessor(this, &args);
Var v(kNo_Modifier, DSLType(kHalf4_Type), "v", Half4(1.0, 2.0, 3.0, 4.0));
Var b(kNo_Modifier, DSLType(kBool4_Type), "b", Bool4(true, true, true, true));
Declare(v);
v = Half4(v.x(), 1.0, 1.0, 1.0);
v = Half4(Swizzle(v, X, Y), 1.0, 1.0);
v = Half4(v.x(), 1.0, 1.0, 1.0);
v = Half4(0.0, v.y(), 1.0, 1.0);
v = Half4(Swizzle(v, X, Y, Z), 1.0);
v = Half4(Swizzle(v, X, Y), 1.0, 1.0);
v = Half4(v.x(), 0.0, v.z(), 1.0);
v = Half4(v.x(), 1.0, 0.0, 1.0);
v = Half4(1.0, Swizzle(v, Y, Z), 1.0);
v = Half4(0.0, v.y(), 1.0, 1.0);
v = Half4(1.0, 1.0, v.z(), 1.0);
v = Half4(Swizzle(v, X, Y, Z), 1.0);
v = Swizzle(v, W, W, W, W);
v = Half4(Swizzle(v, X, Y), 1.0, 0.0);
v = Swizzle(v, X, Z, Z, X);
v = Half4(v.x(), 0.0, v.z(), 1.0);
v = Half4(v.x(), 1.0, 1.0, v.w());
v = Half4(v.x(), 1.0, 0.0, 1.0);
v = Half4(1.0, Swizzle(v, Y, Z, W));
v = Half4(0.0, Swizzle(v, Y, Z), 1.0);
v = Half4(0.0, v.y(), 1.0, v.w());
v = Half4(1.0, v.y(), 1.0, 1.0);
v = Half4(0.0, 0.0, Swizzle(v, Z, W));
v = Half4(0.0, 0.0, v.z(), 1.0);
v = Half4(0.0, 1.0, 1.0, v.w());
v = Half4(0.0, Swizzle(v, Z, Y, X));
v = Half4(0.0, 0.0, Swizzle(v, X, W));
v = Half4(1.0, 1.0, Swizzle(v, W, X));
v = Half4(Swizzle(v, Z, Y), 1.0, 1.0);
v = Half4(Swizzle(v, X, X), 1.0, 1.0);
v = Swizzle(v, W, Z, W, Z);
Declare(b);
b = Bool4(b.x(), true, true, true);
b = Bool4(Swizzle(b, X, Y), false, true);
b = Bool4(b.x(), true, true, false);
b = Bool4(false, b.y(), true, true);
b = Bool4(Swizzle(b, X, Y, Z), true);
b = Bool4(Swizzle(b, X, Y), true, true);
b = Bool4(b.x(), false, b.z(), true);
b = Bool4(b.x(), true, false, false);
b = Bool4(true, Swizzle(b, Y, Z), false);
b = Bool4(false, b.y(), true, false);
b = Bool4(true, true, b.z(), false);
b = Bool4(Swizzle(b, X, Y, Z), true);
b = Swizzle(b, W, W, W, W);
b = Bool4(Swizzle(b, X, Y), true, false);
b = Swizzle(b, X, Z, Z, X);
b = Bool4(b.x(), false, b.z(), true);
b = Bool4(b.x(), true, true, b.w());
b = Bool4(b.x(), true, false, true);
b = Bool4(true, Swizzle(b, Y, Z, W));
b = Bool4(false, Swizzle(b, Y, Z), true);
b = Bool4(false, b.y(), true, b.w());
b = Bool4(true, b.y(), true, true);
b = Bool4(false, false, Swizzle(b, Z, W));
b = Bool4(false, false, b.z(), true);
b = Bool4(false, true, true, b.w());
Return(Half4(Half2(Swizzle(b, X, Y)), 0.0, v.z()));
        EndFragmentProcessor();
    }
private:
    void onSetData(const GrGLSLProgramDataManager& pdman, const GrFragmentProcessor& _proc) override {
    }
};
std::unique_ptr<GrGLSLFragmentProcessor> GrDSLFPTest_Swizzle::onMakeProgramImpl() const {
    return std::make_unique<GrGLSLDSLFPTest_Swizzle>();
}
void GrDSLFPTest_Swizzle::onGetGLSLProcessorKey(const GrShaderCaps& caps, GrProcessorKeyBuilder* b) const {
}
bool GrDSLFPTest_Swizzle::onIsEqual(const GrFragmentProcessor& other) const {
    const GrDSLFPTest_Swizzle& that = other.cast<GrDSLFPTest_Swizzle>();
    (void) that;
    return true;
}
GrDSLFPTest_Swizzle::GrDSLFPTest_Swizzle(const GrDSLFPTest_Swizzle& src)
: INHERITED(kGrDSLFPTest_Swizzle_ClassID, src.optimizationFlags()) {
        this->cloneAndRegisterAllChildProcessors(src);
}
std::unique_ptr<GrFragmentProcessor> GrDSLFPTest_Swizzle::clone() const {
    return std::make_unique<GrDSLFPTest_Swizzle>(*this);
}
#if GR_TEST_UTILS
SkString GrDSLFPTest_Swizzle::onDumpInfo() const {
    return SkString();
}
#endif
