

/**************************************************************************************************
 *** This file was autogenerated from GrDSLFPTest_ForStatement.fp; do not modify.
 **************************************************************************************************/
#ifndef GrDSLFPTest_ForStatement_DEFINED
#define GrDSLFPTest_ForStatement_DEFINED

#include "include/core/SkM44.h"
#include "include/core/SkTypes.h"


#include "src/gpu/GrFragmentProcessor.h"

class GrDSLFPTest_ForStatement : public GrFragmentProcessor {
public:
    static std::unique_ptr<GrFragmentProcessor> Make() {
        return std::unique_ptr<GrFragmentProcessor>(new GrDSLFPTest_ForStatement());
    }
    GrDSLFPTest_ForStatement(const GrDSLFPTest_ForStatement& src);
    std::unique_ptr<GrFragmentProcessor> clone() const override;
    const char* name() const override { return "DSLFPTest_ForStatement"; }
private:
    GrDSLFPTest_ForStatement()
    : INHERITED(kGrDSLFPTest_ForStatement_ClassID, kNone_OptimizationFlags) {
    }
    std::unique_ptr<GrGLSLFragmentProcessor> onMakeProgramImpl() const override;
    void onGetGLSLProcessorKey(const GrShaderCaps&, GrProcessorKeyBuilder*) const override;
    bool onIsEqual(const GrFragmentProcessor&) const override;
#if GR_TEST_UTILS
    SkString onDumpInfo() const override;
#endif
    GR_DECLARE_FRAGMENT_PROCESSOR_TEST
    using INHERITED = GrFragmentProcessor;
};
#endif
