

/**************************************************************************************************
 *** This file was autogenerated from GrDSLForStatement.fp; do not modify.
 **************************************************************************************************/
/* TODO(skia:11854): DSLCPPCodeGenerator is currently a work in progress. */
#include "GrDSLForStatement.h"

#include "src/core/SkUtils.h"
#include "src/gpu/GrTexture.h"
#include "src/gpu/glsl/GrGLSLFragmentProcessor.h"
#include "src/gpu/glsl/GrGLSLFragmentShaderBuilder.h"
#include "src/gpu/glsl/GrGLSLProgramBuilder.h"
#include "src/sksl/SkSLCPP.h"
#include "src/sksl/SkSLUtil.h"
class GrGLSLDSLForStatement : public GrGLSLFragmentProcessor {
public:
    GrGLSLDSLForStatement() {}
    void emitCode(EmitArgs& args) override {
        const GrDSLForStatement& _outer = args.fFp.cast<GrDSLForStatement>();
        (void) _outer;

        using namespace SkSL::dsl;
        StartFragmentProcessor(this, &args);
Var color(DSLModifiers(), DSLType(kHalf4_Type), "color", Half4(1.0));
Var a(DSLModifiers(), DSLType(kHalf_Type), "a", 0.0);
Var r(DSLModifiers(), DSLType(kHalf_Type), "r", -5.0);
Var b(DSLModifiers(), DSLType(kHalf_Type), "b", 5.0);
Declare(color);
For(Declare(a), a <= 1.0, ++a, /*Body:*/ color.w() = a);
For(Declare(r), r < 5.0, r += 1.0, /*Body:*/ Block(color.x() = r, If(color.x() == 0.0, /*Then:*/ Break())));
For(Declare(b), b >= 0.0, b -= 1.0, /*Body:*/ Block(color.z() = b, If(color.w() == 1.0, /*Then:*/ Continue()), color.y() = 0.0));
Return(color);
        EndFragmentProcessor();
    }
private:
    void onSetData(const GrGLSLProgramDataManager& pdman, const GrFragmentProcessor& _proc) override {
    }
};
std::unique_ptr<GrGLSLFragmentProcessor> GrDSLForStatement::onMakeProgramImpl() const {
    return std::make_unique<GrGLSLDSLForStatement>();
}
void GrDSLForStatement::onGetGLSLProcessorKey(const GrShaderCaps& caps, GrProcessorKeyBuilder* b) const {
}
bool GrDSLForStatement::onIsEqual(const GrFragmentProcessor& other) const {
    const GrDSLForStatement& that = other.cast<GrDSLForStatement>();
    (void) that;
    return true;
}
GrDSLForStatement::GrDSLForStatement(const GrDSLForStatement& src)
: INHERITED(kGrDSLForStatement_ClassID, src.optimizationFlags()) {
        this->cloneAndRegisterAllChildProcessors(src);
}
std::unique_ptr<GrFragmentProcessor> GrDSLForStatement::clone() const {
    return std::make_unique<GrDSLForStatement>(*this);
}
#if GR_TEST_UTILS
SkString GrDSLForStatement::onDumpInfo() const {
    return SkString();
}
#endif
