

/**************************************************************************************************
 *** This file was autogenerated from GrDSLTestTernary.fp; do not modify.
 **************************************************************************************************/
/* TODO(skia:11854): DSLCPPCodeGenerator is currently a work in progress. */
#include "GrDSLTestTernary.h"

#include "src/core/SkUtils.h"
#include "src/gpu/GrTexture.h"
#include "src/gpu/glsl/GrGLSLFragmentProcessor.h"
#include "src/gpu/glsl/GrGLSLFragmentShaderBuilder.h"
#include "src/gpu/glsl/GrGLSLProgramBuilder.h"
#include "src/sksl/SkSLCPP.h"
#include "src/sksl/SkSLUtil.h"
#include "src/sksl/dsl/priv/DSLFPs.h"
#include "src/sksl/dsl/priv/DSLWriter.h"

#if defined(__clang__)
#pragma clang diagnostic ignored "-Wcomma"
#endif

class GrGLSLDSLTestTernary : public GrGLSLFragmentProcessor {
public:
    GrGLSLDSLTestTernary() {}
    void emitCode(EmitArgs& args) override {
        const GrDSLTestTernary& _outer = args.fFp.cast<GrDSLTestTernary>();
        (void) _outer;

        using namespace SkSL::dsl;
        StartFragmentProcessor(this, &args);
Var a(DSLModifiers(), DSLType(kFloat4_Type), "a", Float4(1.0, 2.0, 3.0, 4.0));
Var b(DSLModifiers(), DSLType(kFloat4_Type), "b", Float4(5.0, 6.0, 7.0, 8.0));
Var x(DSLModifiers(), DSLType(kInt_Type), "x", Int(Select(a.x() != b.y(), /*If True:*/ 123, /*If False:*/ 456)));
Var y(DSLModifiers(), DSLType(kInt_Type), "y", Int(Select(a.y() <= b.z(), /*If True:*/ 234, /*If False:*/ 567)));
Declare(a);
Declare(b);
Declare(x);
Declare(y);
Return(Select(x == y, /*If True:*/ Half4(1.0), /*If False:*/ Half4(0.0)));
        EndFragmentProcessor();
    }
private:
    void onSetData(const GrGLSLProgramDataManager& pdman, const GrFragmentProcessor& _proc) override {
    }
};
std::unique_ptr<GrGLSLFragmentProcessor> GrDSLTestTernary::onMakeProgramImpl() const {
    return std::make_unique<GrGLSLDSLTestTernary>();
}
void GrDSLTestTernary::onGetGLSLProcessorKey(const GrShaderCaps& caps, GrProcessorKeyBuilder* b) const {
}
bool GrDSLTestTernary::onIsEqual(const GrFragmentProcessor& other) const {
    const GrDSLTestTernary& that = other.cast<GrDSLTestTernary>();
    (void) that;
    return true;
}
GrDSLTestTernary::GrDSLTestTernary(const GrDSLTestTernary& src)
: INHERITED(kGrDSLTestTernary_ClassID, src.optimizationFlags()) {
        this->cloneAndRegisterAllChildProcessors(src);
}
std::unique_ptr<GrFragmentProcessor> GrDSLTestTernary::clone() const {
    return std::make_unique<GrDSLTestTernary>(*this);
}
#if GR_TEST_UTILS
SkString GrDSLTestTernary::onDumpInfo() const {
    return SkString();
}
#endif
