

/**************************************************************************************************
 *** This file was autogenerated from GrDSLTestIfStatement.fp; do not modify.
 **************************************************************************************************/
/* TODO(skia:11854): DSLCPPCodeGenerator is currently a work in progress. */
#include "GrDSLTestIfStatement.h"

#include "src/core/SkUtils.h"
#include "src/gpu/GrTexture.h"
#include "src/gpu/glsl/GrGLSLFragmentProcessor.h"
#include "src/gpu/glsl/GrGLSLFragmentShaderBuilder.h"
#include "src/gpu/glsl/GrGLSLProgramBuilder.h"
#include "src/sksl/SkSLCPP.h"
#include "src/sksl/SkSLUtil.h"
#include "src/sksl/dsl/priv/DSLFPs.h"
#include "src/sksl/dsl/priv/DSLWriter.h"

#if defined(__clang__)
#pragma clang diagnostic ignored "-Wcomma"
#endif

class GrGLSLDSLTestIfStatement : public GrGLSLFragmentProcessor {
public:
    GrGLSLDSLTestIfStatement() {}
    void emitCode(EmitArgs& args) override {
        const GrDSLTestIfStatement& _outer = args.fFp.cast<GrDSLTestIfStatement>();
        (void) _outer;

        using namespace SkSL::dsl;
        StartFragmentProcessor(this, &args);
Var x(DSLModifiers(), DSLType(kInt_Type), "x", 12);
Var y(DSLModifiers(), DSLType(kInt_Type), "y", 34);
(Declare(x), Declare(y));
If(x == y + 1, /*Then:*/ Return(Half4(2.0)));
If(x == y, /*Then:*/ Block(Return(Half4(1.0))));
If(x == y + 2, /*Then:*/ (x = 0 , y = 0));
If(x == y + 3, /*Then:*/ x *= 2, /*Else:*/ y *= 2);
If(x == y + 4, /*Then:*/ Block(x += 1, y -= 1, Return(Half4(2.0))), /*Else:*/ If(x == y + 5, /*Then:*/ Block(y -= 1, Return(Half4(3.0))), /*Else:*/ Block(y += 1)));
If(x == y + 6, /*Then:*/ Block(If(x == 99, /*Then:*/ Block(x *= 2), /*Else:*/ Block(y *= 2))), /*Else:*/ Block(If(x == 99, /*Then:*/ Block(x /= 2), /*Else:*/ Block(y /= 2))));
Return(Half4(0.0));
        EndFragmentProcessor();
    }
private:
    void onSetData(const GrGLSLProgramDataManager& pdman, const GrFragmentProcessor& _proc) override {
    }
};
std::unique_ptr<GrGLSLFragmentProcessor> GrDSLTestIfStatement::onMakeProgramImpl() const {
    return std::make_unique<GrGLSLDSLTestIfStatement>();
}
void GrDSLTestIfStatement::onGetGLSLProcessorKey(const GrShaderCaps& caps, GrProcessorKeyBuilder* b) const {
}
bool GrDSLTestIfStatement::onIsEqual(const GrFragmentProcessor& other) const {
    const GrDSLTestIfStatement& that = other.cast<GrDSLTestIfStatement>();
    (void) that;
    return true;
}
GrDSLTestIfStatement::GrDSLTestIfStatement(const GrDSLTestIfStatement& src)
: INHERITED(kGrDSLTestIfStatement_ClassID, src.optimizationFlags()) {
        this->cloneAndRegisterAllChildProcessors(src);
}
std::unique_ptr<GrFragmentProcessor> GrDSLTestIfStatement::clone() const {
    return std::make_unique<GrDSLTestIfStatement>(*this);
}
#if GR_TEST_UTILS
SkString GrDSLTestIfStatement::onDumpInfo() const {
    return SkString();
}
#endif
