load("//bazel:skia_rules.bzl", "skia_cc_library")

package(
    default_applicable_licenses = ["//:license"],
)

licenses(["notice"])

skia_cc_library(
    name = "graphite_test_context",
    testonly = True,
    srcs = [
        "GraphiteTestContext.cpp",
    ],
    hdrs = [
        "GraphiteTestContext.h",
        "TestOptions.h",
    ],
    visibility = ["//tools/graphite:__subpackages__"],
    deps = [
        "//:core",
        "//tools/gpu:shared_utils",
    ],
)

skia_cc_library(
    name = "graphite_utils",
    testonly = True,
    srcs = [
        "ContextFactory.cpp",
        "ContextFactory.h",
        "GraphiteMemoryPipelineStorage.cpp",
        "GraphiteMemoryPipelineStorage.h",
        "GraphiteToolUtils.cpp",
        "PipelineCallbackHandler.cpp",
        "ProtectedUtils_Graphite.cpp",
        "UniqueKeyUtils.cpp",
        "UniqueKeyUtils.h",
    ],
    hdrs = [
        "ContextFactory.h",
        "GraphiteToolUtils.h",
        "PipelineCallbackHandler.h",
    ],
    visibility = [
        "//bench:__subpackages__",
        "//dm:__pkg__",
        "//modules/skottie:__pkg__",
        "//tools:__subpackages__",
    ],
    deps = [
        ":graphite_test_context",
        "//:core",
        "//src/core:core_priv",
        "//src/gpu/graphite:graphite_TEST_UTIL",
        "//tools/gpu:shared_utils",
    ] + select({
        "@platforms//os:macos": [
            "//tools/graphite/mtl:graphite_metal_test_context",
        ],
        "//conditions:default": [],
    }),
)

skia_cc_library(
    name = "precompile_utils",
    testonly = True,
    srcs = [
        "precompile/PrecompileEffectFactories.cpp",
    ],
    hdrs = [
        "precompile/PrecompileEffectFactories.h",
    ],
    visibility = [
        "//dm:__pkg__",
        "//tools:__subpackages__",
    ],
    deps = [
        "//:core",
        "//src/gpu/graphite/precompile:precompile_TEST_UTIL",
    ],
)
