/*
 * Copyright 2018 Google Inc.
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**************************************************************************************************
 *** This file was autogenerated from GrGLTFLightingFragmentProcessor.fp; do not modify.
 **************************************************************************************************/
#ifndef GrGLTFLightingFragmentProcessor_DEFINED
#define GrGLTFLightingFragmentProcessor_DEFINED
#include "SkTypes.h"
#include "GrFragmentProcessor.h"
#include "GrCoordTransform.h"
class GrGLTFLightingFragmentProcessor : public GrFragmentProcessor {
public:
    SkPoint deviceSize() const { return fDeviceSize; }
    float roughness() const { return fRoughness; }
    float metallicness() const { return fMetallicness; }
    SkRect lightAndViewer() const { return fLightAndViewer; }

    static std::unique_ptr<GrGLTFLightingFragmentProcessor> Make(const SkISize& deviceSize,
                                                                 const SkPoint3& lightPos,
                                                                 const SkScalar& viewerDistance,
                                                                 const SkScalar& roughness,
                                                                 const SkScalar& metallicness) {
        std::unique_ptr<GrGLTFLightingFragmentProcessor> fp(new GrGLTFLightingFragmentProcessor(
                SkPoint::Make(deviceSize.fWidth, deviceSize.fHeight), roughness, metallicness,
                SkRect::MakeLTRB(lightPos.fX, lightPos.fY, lightPos.fZ, viewerDistance),
                SkMatrix::I()));

        fp->addCoordTransform(&(fp->fCoordTransform));
        return fp;
    }
    GrGLTFLightingFragmentProcessor(const GrGLTFLightingFragmentProcessor& src);
    std::unique_ptr<GrFragmentProcessor> clone() const override;
    const char* name() const override { return "GLTFLightingFragmentProcessor"; }

private:
    GrGLTFLightingFragmentProcessor(SkPoint deviceSize, float roughness, float metallicness,
                                    SkRect lightAndViewer, SkMatrix transform)
            : INHERITED(kGrGLTFLightingFragmentProcessor_ClassID, kNone_OptimizationFlags)
            , fCoordTransform(transform)

            , fDeviceSize(deviceSize)
            , fRoughness(roughness)
            , fMetallicness(metallicness)
            , fLightAndViewer(lightAndViewer) {}
    GrGLSLFragmentProcessor* onCreateGLSLInstance() const override;
    void onGetGLSLProcessorKey(const GrShaderCaps&, GrProcessorKeyBuilder*) const override;
    bool onIsEqual(const GrFragmentProcessor&) const override;
    GR_DECLARE_FRAGMENT_PROCESSOR_TEST

    GrCoordTransform fCoordTransform;
    SkPoint fDeviceSize;
    float fRoughness;
    float fMetallicness;
    SkRect fLightAndViewer;
    typedef GrFragmentProcessor INHERITED;
};
#endif
