/*
 * Copyright 2019 Google Inc.
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**************************************************************************************************
 *** This file was autogenerated from GrNullEffect.fp; do not modify.
 **************************************************************************************************/
#include "GrNullEffect.h"
#include "glsl/GrGLSLFragmentProcessor.h"
#include "glsl/GrGLSLFragmentShaderBuilder.h"
#include "glsl/GrGLSLProgramBuilder.h"
#include "GrTexture.h"
#include "SkSLCPP.h"
#include "SkSLUtil.h"
class GrGLSLNullEffect : public GrGLSLFragmentProcessor {
public:
    GrGLSLNullEffect() {}
    void emitCode(EmitArgs& args) override {
        GrGLSLFPFragmentBuilder* fragBuilder = args.fFragBuilder;
        const GrNullEffect& _outer = args.fFp.cast<GrNullEffect>();
        (void)_outer;
        fragBuilder->codeAppendf("%s = %s;\n", args.fOutputColor, args.fInputColor);
    }

private:
    void onSetData(const GrGLSLProgramDataManager& pdman,
                   const GrFragmentProcessor& _proc) override {}
};
GrGLSLFragmentProcessor* GrNullEffect::onCreateGLSLInstance() const {
    return new GrGLSLNullEffect();
}
void GrNullEffect::onGetGLSLProcessorKey(const GrShaderCaps& caps, GrProcessorKeyBuilder* b) const {
}
bool GrNullEffect::onIsEqual(const GrFragmentProcessor& other) const {
    const GrNullEffect& that = other.cast<GrNullEffect>();
    (void)that;
    return true;
}
GrNullEffect::GrNullEffect(const GrNullEffect& src)
        : INHERITED(kGrNullEffect_ClassID, src.optimizationFlags()) {}
std::unique_ptr<GrFragmentProcessor> GrNullEffect::clone() const {
    return std::unique_ptr<GrFragmentProcessor>(new GrNullEffect(*this));
}
