#ifndef EXPERIMENTAL_PDFVIEWER_PDFPARSER_NATIVE_SKNATIVEPARSEDPDF_H_
#define EXPERIMENTAL_PDFVIEWER_PDFPARSER_NATIVE_SKNATIVEPARSEDPDF_H_

#include "base/macros.h"

class SkNativeParsedPDF : public SkParsedPDF {
public:
    SkNativeParsedPDF();
    virtual ~SkNativeParsedPDF();
};

#endif  // EXPERIMENTAL_PDFVIEWER_PDFPARSER_NATIVE_SKNATIVEPARSEDPDF_H_
