/*
 * Copyright 2020 Google LLC
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef SKSL_DSL_EXPRESSION
#define SKSL_DSL_EXPRESSION

#include "src/sksl/SkSLCompiler.h"
#include "src/sksl/SkSLIRGenerator.h"
#include "src/sksl/ir/SkSLBoolLiteral.h"
#include "src/sksl/ir/SkSLFloatLiteral.h"
#include "src/sksl/ir/SkSLIntLiteral.h"

namespace SkSL {

namespace dsl {

class Expression;
class Var;

enum SwizzleComponent : int8_t {
    R,
    G,
    B,
    A,
    X,
    Y,
    Z,
    W,
    ZERO,
    ONE
};

Expression Swizzle(Expression base, SwizzleComponent a);

Expression Swizzle(Expression base, SwizzleComponent a, SwizzleComponent b);

Expression Swizzle(Expression base, SwizzleComponent a, SwizzleComponent b, SwizzleComponent c);

Expression Swizzle(Expression base, SwizzleComponent a, SwizzleComponent b, SwizzleComponent c,
                   SwizzleComponent d);

/**
 * Represents an expression such as 'cos(x)' or 'a + b'.
 */
class Expression {
public:
    Expression(const Expression&) = delete;

    Expression(Expression&&) = default;

    Expression(std::unique_ptr<SkSL::Expression> expression);

    /**
     * Creates an expression representing a literal float.
     */
    Expression(float value);

    /**
     * Creates an expression representing a literal float.
     */
    Expression(double value)
        : Expression((float) value) {}

    /**
     * Creates an expression representing a literal int.
     */
    Expression(int value);

    /**
     * Creates an expression representing a variable reference.
     */
    Expression(const Var& var);

    ~Expression() {
        SkASSERTF(!fExpression, "Expression destroyed without being incorporated into output tree");
    }

    /**
     * Overloads the '=' operator to create an SkSL assignment statement.
     */
    Expression operator=(Expression&& other);

    /**
     * Creates an SkSL array index expression.
     */
    Expression operator[](Expression&& index);

    #define SWIZZLE1(mask, a)                                                                      \
        Expression mask() {                                                                        \
            return Swizzle(this->release(), a);                                                    \
        }

    #define SWIZZLE2(mask, a, b)                                                                   \
        Expression mask() {                                                                        \
            return Swizzle(this->release(), a, b);                                                 \
        }

    #define SWIZZLE3(mask, a, b, c)                                                                \
        Expression mask() {                                                                        \
            return Swizzle(this->release(), a, b, c);                                              \
        }

    #define SWIZZLE4(mask, a, b, c, d)                                                             \
        Expression mask() {                                                                        \
            return Swizzle(this->release(), a, b, c, d);                                           \
        }

    // The list below generates a function for performing every possible swizzle mask, other than
    // those beginning with 0 or 1.
    SWIZZLE1(x, X)
    SWIZZLE1(y, Y)
    SWIZZLE1(z, Z)
    SWIZZLE1(w, W)
    SWIZZLE2(xx, X, X)
    SWIZZLE2(xy, X, Y)
    SWIZZLE2(xz, X, Z)
    SWIZZLE2(xw, X, W)
    SWIZZLE2(x0, X, ZERO)
    SWIZZLE2(x1, X, ONE)
    SWIZZLE2(yx, Y, X)
    SWIZZLE2(yy, Y, Y)
    SWIZZLE2(yz, Y, Z)
    SWIZZLE2(yw, Y, W)
    SWIZZLE2(y0, Y, ZERO)
    SWIZZLE2(y1, Y, ONE)
    SWIZZLE2(zx, Z, X)
    SWIZZLE2(zy, Z, Y)
    SWIZZLE2(zz, Z, Z)
    SWIZZLE2(zw, Z, W)
    SWIZZLE2(z0, Z, ZERO)
    SWIZZLE2(z1, Z, ONE)
    SWIZZLE2(wx, W, X)
    SWIZZLE2(wy, W, Y)
    SWIZZLE2(wz, W, Z)
    SWIZZLE2(ww, W, W)
    SWIZZLE2(w0, W, ZERO)
    SWIZZLE2(w1, W, ONE)
    SWIZZLE3(xxx, X, X, X)
    SWIZZLE3(xxy, X, X, Y)
    SWIZZLE3(xxz, X, X, Z)
    SWIZZLE3(xxw, X, X, W)
    SWIZZLE3(xx0, X, X, ZERO)
    SWIZZLE3(xx1, X, X, ONE)
    SWIZZLE3(xyx, X, Y, X)
    SWIZZLE3(xyy, X, Y, Y)
    SWIZZLE3(xyz, X, Y, Z)
    SWIZZLE3(xyw, X, Y, W)
    SWIZZLE3(xy0, X, Y, ZERO)
    SWIZZLE3(xy1, X, Y, ONE)
    SWIZZLE3(xzx, X, Z, X)
    SWIZZLE3(xzy, X, Z, Y)
    SWIZZLE3(xzz, X, Z, Z)
    SWIZZLE3(xzw, X, Z, W)
    SWIZZLE3(xz0, X, Z, ZERO)
    SWIZZLE3(xz1, X, Z, ONE)
    SWIZZLE3(xwx, X, W, X)
    SWIZZLE3(xwy, X, W, Y)
    SWIZZLE3(xwz, X, W, Z)
    SWIZZLE3(xww, X, W, W)
    SWIZZLE3(xw0, X, W, ZERO)
    SWIZZLE3(xw1, X, W, ONE)
    SWIZZLE3(x0x, X, ZERO, X)
    SWIZZLE3(x0y, X, ZERO, Y)
    SWIZZLE3(x0z, X, ZERO, Z)
    SWIZZLE3(x0w, X, ZERO, W)
    SWIZZLE3(x00, X, ZERO, ZERO)
    SWIZZLE3(x01, X, ZERO, ONE)
    SWIZZLE3(x1x, X, ONE, X)
    SWIZZLE3(x1y, X, ONE, Y)
    SWIZZLE3(x1z, X, ONE, Z)
    SWIZZLE3(x1w, X, ONE, W)
    SWIZZLE3(x10, X, ONE, ZERO)
    SWIZZLE3(x11, X, ONE, ONE)
    SWIZZLE3(yxx, Y, X, X)
    SWIZZLE3(yxy, Y, X, Y)
    SWIZZLE3(yxz, Y, X, Z)
    SWIZZLE3(yxw, Y, X, W)
    SWIZZLE3(yx0, Y, X, ZERO)
    SWIZZLE3(yx1, Y, X, ONE)
    SWIZZLE3(yyx, Y, Y, X)
    SWIZZLE3(yyy, Y, Y, Y)
    SWIZZLE3(yyz, Y, Y, Z)
    SWIZZLE3(yyw, Y, Y, W)
    SWIZZLE3(yy0, Y, Y, ZERO)
    SWIZZLE3(yy1, Y, Y, ONE)
    SWIZZLE3(yzx, Y, Z, X)
    SWIZZLE3(yzy, Y, Z, Y)
    SWIZZLE3(yzz, Y, Z, Z)
    SWIZZLE3(yzw, Y, Z, W)
    SWIZZLE3(yz0, Y, Z, ZERO)
    SWIZZLE3(yz1, Y, Z, ONE)
    SWIZZLE3(ywx, Y, W, X)
    SWIZZLE3(ywy, Y, W, Y)
    SWIZZLE3(ywz, Y, W, Z)
    SWIZZLE3(yww, Y, W, W)
    SWIZZLE3(yw0, Y, W, ZERO)
    SWIZZLE3(yw1, Y, W, ONE)
    SWIZZLE3(y0x, Y, ZERO, X)
    SWIZZLE3(y0y, Y, ZERO, Y)
    SWIZZLE3(y0z, Y, ZERO, Z)
    SWIZZLE3(y0w, Y, ZERO, W)
    SWIZZLE3(y00, Y, ZERO, ZERO)
    SWIZZLE3(y01, Y, ZERO, ONE)
    SWIZZLE3(y1x, Y, ONE, X)
    SWIZZLE3(y1y, Y, ONE, Y)
    SWIZZLE3(y1z, Y, ONE, Z)
    SWIZZLE3(y1w, Y, ONE, W)
    SWIZZLE3(y10, Y, ONE, ZERO)
    SWIZZLE3(y11, Y, ONE, ONE)
    SWIZZLE3(zxx, Z, X, X)
    SWIZZLE3(zxy, Z, X, Y)
    SWIZZLE3(zxz, Z, X, Z)
    SWIZZLE3(zxw, Z, X, W)
    SWIZZLE3(zx0, Z, X, ZERO)
    SWIZZLE3(zx1, Z, X, ONE)
    SWIZZLE3(zyx, Z, Y, X)
    SWIZZLE3(zyy, Z, Y, Y)
    SWIZZLE3(zyz, Z, Y, Z)
    SWIZZLE3(zyw, Z, Y, W)
    SWIZZLE3(zy0, Z, Y, ZERO)
    SWIZZLE3(zy1, Z, Y, ONE)
    SWIZZLE3(zzx, Z, Z, X)
    SWIZZLE3(zzy, Z, Z, Y)
    SWIZZLE3(zzz, Z, Z, Z)
    SWIZZLE3(zzw, Z, Z, W)
    SWIZZLE3(zz0, Z, Z, ZERO)
    SWIZZLE3(zz1, Z, Z, ONE)
    SWIZZLE3(zwx, Z, W, X)
    SWIZZLE3(zwy, Z, W, Y)
    SWIZZLE3(zwz, Z, W, Z)
    SWIZZLE3(zww, Z, W, W)
    SWIZZLE3(zw0, Z, W, ZERO)
    SWIZZLE3(zw1, Z, W, ONE)
    SWIZZLE3(z0x, Z, ZERO, X)
    SWIZZLE3(z0y, Z, ZERO, Y)
    SWIZZLE3(z0z, Z, ZERO, Z)
    SWIZZLE3(z0w, Z, ZERO, W)
    SWIZZLE3(z00, Z, ZERO, ZERO)
    SWIZZLE3(z01, Z, ZERO, ONE)
    SWIZZLE3(z1x, Z, ONE, X)
    SWIZZLE3(z1y, Z, ONE, Y)
    SWIZZLE3(z1z, Z, ONE, Z)
    SWIZZLE3(z1w, Z, ONE, W)
    SWIZZLE3(z10, Z, ONE, ZERO)
    SWIZZLE3(z11, Z, ONE, ONE)
    SWIZZLE3(wxx, W, X, X)
    SWIZZLE3(wxy, W, X, Y)
    SWIZZLE3(wxz, W, X, Z)
    SWIZZLE3(wxw, W, X, W)
    SWIZZLE3(wx0, W, X, ZERO)
    SWIZZLE3(wx1, W, X, ONE)
    SWIZZLE3(wyx, W, Y, X)
    SWIZZLE3(wyy, W, Y, Y)
    SWIZZLE3(wyz, W, Y, Z)
    SWIZZLE3(wyw, W, Y, W)
    SWIZZLE3(wy0, W, Y, ZERO)
    SWIZZLE3(wy1, W, Y, ONE)
    SWIZZLE3(wzx, W, Z, X)
    SWIZZLE3(wzy, W, Z, Y)
    SWIZZLE3(wzz, W, Z, Z)
    SWIZZLE3(wzw, W, Z, W)
    SWIZZLE3(wz0, W, Z, ZERO)
    SWIZZLE3(wz1, W, Z, ONE)
    SWIZZLE3(wwx, W, W, X)
    SWIZZLE3(wwy, W, W, Y)
    SWIZZLE3(wwz, W, W, Z)
    SWIZZLE3(www, W, W, W)
    SWIZZLE3(ww0, W, W, ZERO)
    SWIZZLE3(ww1, W, W, ONE)
    SWIZZLE3(w0x, W, ZERO, X)
    SWIZZLE3(w0y, W, ZERO, Y)
    SWIZZLE3(w0z, W, ZERO, Z)
    SWIZZLE3(w0w, W, ZERO, W)
    SWIZZLE3(w00, W, ZERO, ZERO)
    SWIZZLE3(w01, W, ZERO, ONE)
    SWIZZLE3(w1x, W, ONE, X)
    SWIZZLE3(w1y, W, ONE, Y)
    SWIZZLE3(w1z, W, ONE, Z)
    SWIZZLE3(w1w, W, ONE, W)
    SWIZZLE3(w10, W, ONE, ZERO)
    SWIZZLE3(w11, W, ONE, ONE)
    SWIZZLE4(xxxx, X, X, X, X)
    SWIZZLE4(xxxy, X, X, X, Y)
    SWIZZLE4(xxxz, X, X, X, Z)
    SWIZZLE4(xxxw, X, X, X, W)
    SWIZZLE4(xxx0, X, X, X, ZERO)
    SWIZZLE4(xxx1, X, X, X, ONE)
    SWIZZLE4(xxyx, X, X, Y, X)
    SWIZZLE4(xxyy, X, X, Y, Y)
    SWIZZLE4(xxyz, X, X, Y, Z)
    SWIZZLE4(xxyw, X, X, Y, W)
    SWIZZLE4(xxy0, X, X, Y, ZERO)
    SWIZZLE4(xxy1, X, X, Y, ONE)
    SWIZZLE4(xxzx, X, X, Z, X)
    SWIZZLE4(xxzy, X, X, Z, Y)
    SWIZZLE4(xxzz, X, X, Z, Z)
    SWIZZLE4(xxzw, X, X, Z, W)
    SWIZZLE4(xxz0, X, X, Z, ZERO)
    SWIZZLE4(xxz1, X, X, Z, ONE)
    SWIZZLE4(xxwx, X, X, W, X)
    SWIZZLE4(xxwy, X, X, W, Y)
    SWIZZLE4(xxwz, X, X, W, Z)
    SWIZZLE4(xxww, X, X, W, W)
    SWIZZLE4(xxw0, X, X, W, ZERO)
    SWIZZLE4(xxw1, X, X, W, ONE)
    SWIZZLE4(xx0x, X, X, ZERO, X)
    SWIZZLE4(xx0y, X, X, ZERO, Y)
    SWIZZLE4(xx0z, X, X, ZERO, Z)
    SWIZZLE4(xx0w, X, X, ZERO, W)
    SWIZZLE4(xx00, X, X, ZERO, ZERO)
    SWIZZLE4(xx01, X, X, ZERO, ONE)
    SWIZZLE4(xx1x, X, X, ONE, X)
    SWIZZLE4(xx1y, X, X, ONE, Y)
    SWIZZLE4(xx1z, X, X, ONE, Z)
    SWIZZLE4(xx1w, X, X, ONE, W)
    SWIZZLE4(xx10, X, X, ONE, ZERO)
    SWIZZLE4(xx11, X, X, ONE, ONE)
    SWIZZLE4(xyxx, X, Y, X, X)
    SWIZZLE4(xyxy, X, Y, X, Y)
    SWIZZLE4(xyxz, X, Y, X, Z)
    SWIZZLE4(xyxw, X, Y, X, W)
    SWIZZLE4(xyx0, X, Y, X, ZERO)
    SWIZZLE4(xyx1, X, Y, X, ONE)
    SWIZZLE4(xyyx, X, Y, Y, X)
    SWIZZLE4(xyyy, X, Y, Y, Y)
    SWIZZLE4(xyyz, X, Y, Y, Z)
    SWIZZLE4(xyyw, X, Y, Y, W)
    SWIZZLE4(xyy0, X, Y, Y, ZERO)
    SWIZZLE4(xyy1, X, Y, Y, ONE)
    SWIZZLE4(xyzx, X, Y, Z, X)
    SWIZZLE4(xyzy, X, Y, Z, Y)
    SWIZZLE4(xyzz, X, Y, Z, Z)
    SWIZZLE4(xyzw, X, Y, Z, W)
    SWIZZLE4(xyz0, X, Y, Z, ZERO)
    SWIZZLE4(xyz1, X, Y, Z, ONE)
    SWIZZLE4(xywx, X, Y, W, X)
    SWIZZLE4(xywy, X, Y, W, Y)
    SWIZZLE4(xywz, X, Y, W, Z)
    SWIZZLE4(xyww, X, Y, W, W)
    SWIZZLE4(xyw0, X, Y, W, ZERO)
    SWIZZLE4(xyw1, X, Y, W, ONE)
    SWIZZLE4(xy0x, X, Y, ZERO, X)
    SWIZZLE4(xy0y, X, Y, ZERO, Y)
    SWIZZLE4(xy0z, X, Y, ZERO, Z)
    SWIZZLE4(xy0w, X, Y, ZERO, W)
    SWIZZLE4(xy00, X, Y, ZERO, ZERO)
    SWIZZLE4(xy01, X, Y, ZERO, ONE)
    SWIZZLE4(xy1x, X, Y, ONE, X)
    SWIZZLE4(xy1y, X, Y, ONE, Y)
    SWIZZLE4(xy1z, X, Y, ONE, Z)
    SWIZZLE4(xy1w, X, Y, ONE, W)
    SWIZZLE4(xy10, X, Y, ONE, ZERO)
    SWIZZLE4(xy11, X, Y, ONE, ONE)
    SWIZZLE4(xzxx, X, Z, X, X)
    SWIZZLE4(xzxy, X, Z, X, Y)
    SWIZZLE4(xzxz, X, Z, X, Z)
    SWIZZLE4(xzxw, X, Z, X, W)
    SWIZZLE4(xzx0, X, Z, X, ZERO)
    SWIZZLE4(xzx1, X, Z, X, ONE)
    SWIZZLE4(xzyx, X, Z, Y, X)
    SWIZZLE4(xzyy, X, Z, Y, Y)
    SWIZZLE4(xzyz, X, Z, Y, Z)
    SWIZZLE4(xzyw, X, Z, Y, W)
    SWIZZLE4(xzy0, X, Z, Y, ZERO)
    SWIZZLE4(xzy1, X, Z, Y, ONE)
    SWIZZLE4(xzzx, X, Z, Z, X)
    SWIZZLE4(xzzy, X, Z, Z, Y)
    SWIZZLE4(xzzz, X, Z, Z, Z)
    SWIZZLE4(xzzw, X, Z, Z, W)
    SWIZZLE4(xzz0, X, Z, Z, ZERO)
    SWIZZLE4(xzz1, X, Z, Z, ONE)
    SWIZZLE4(xzwx, X, Z, W, X)
    SWIZZLE4(xzwy, X, Z, W, Y)
    SWIZZLE4(xzwz, X, Z, W, Z)
    SWIZZLE4(xzww, X, Z, W, W)
    SWIZZLE4(xzw0, X, Z, W, ZERO)
    SWIZZLE4(xzw1, X, Z, W, ONE)
    SWIZZLE4(xz0x, X, Z, ZERO, X)
    SWIZZLE4(xz0y, X, Z, ZERO, Y)
    SWIZZLE4(xz0z, X, Z, ZERO, Z)
    SWIZZLE4(xz0w, X, Z, ZERO, W)
    SWIZZLE4(xz00, X, Z, ZERO, ZERO)
    SWIZZLE4(xz01, X, Z, ZERO, ONE)
    SWIZZLE4(xz1x, X, Z, ONE, X)
    SWIZZLE4(xz1y, X, Z, ONE, Y)
    SWIZZLE4(xz1z, X, Z, ONE, Z)
    SWIZZLE4(xz1w, X, Z, ONE, W)
    SWIZZLE4(xz10, X, Z, ONE, ZERO)
    SWIZZLE4(xz11, X, Z, ONE, ONE)
    SWIZZLE4(xwxx, X, W, X, X)
    SWIZZLE4(xwxy, X, W, X, Y)
    SWIZZLE4(xwxz, X, W, X, Z)
    SWIZZLE4(xwxw, X, W, X, W)
    SWIZZLE4(xwx0, X, W, X, ZERO)
    SWIZZLE4(xwx1, X, W, X, ONE)
    SWIZZLE4(xwyx, X, W, Y, X)
    SWIZZLE4(xwyy, X, W, Y, Y)
    SWIZZLE4(xwyz, X, W, Y, Z)
    SWIZZLE4(xwyw, X, W, Y, W)
    SWIZZLE4(xwy0, X, W, Y, ZERO)
    SWIZZLE4(xwy1, X, W, Y, ONE)
    SWIZZLE4(xwzx, X, W, Z, X)
    SWIZZLE4(xwzy, X, W, Z, Y)
    SWIZZLE4(xwzz, X, W, Z, Z)
    SWIZZLE4(xwzw, X, W, Z, W)
    SWIZZLE4(xwz0, X, W, Z, ZERO)
    SWIZZLE4(xwz1, X, W, Z, ONE)
    SWIZZLE4(xwwx, X, W, W, X)
    SWIZZLE4(xwwy, X, W, W, Y)
    SWIZZLE4(xwwz, X, W, W, Z)
    SWIZZLE4(xwww, X, W, W, W)
    SWIZZLE4(xww0, X, W, W, ZERO)
    SWIZZLE4(xww1, X, W, W, ONE)
    SWIZZLE4(xw0x, X, W, ZERO, X)
    SWIZZLE4(xw0y, X, W, ZERO, Y)
    SWIZZLE4(xw0z, X, W, ZERO, Z)
    SWIZZLE4(xw0w, X, W, ZERO, W)
    SWIZZLE4(xw00, X, W, ZERO, ZERO)
    SWIZZLE4(xw01, X, W, ZERO, ONE)
    SWIZZLE4(xw1x, X, W, ONE, X)
    SWIZZLE4(xw1y, X, W, ONE, Y)
    SWIZZLE4(xw1z, X, W, ONE, Z)
    SWIZZLE4(xw1w, X, W, ONE, W)
    SWIZZLE4(xw10, X, W, ONE, ZERO)
    SWIZZLE4(xw11, X, W, ONE, ONE)
    SWIZZLE4(x0xx, X, ZERO, X, X)
    SWIZZLE4(x0xy, X, ZERO, X, Y)
    SWIZZLE4(x0xz, X, ZERO, X, Z)
    SWIZZLE4(x0xw, X, ZERO, X, W)
    SWIZZLE4(x0x0, X, ZERO, X, ZERO)
    SWIZZLE4(x0x1, X, ZERO, X, ONE)
    SWIZZLE4(x0yx, X, ZERO, Y, X)
    SWIZZLE4(x0yy, X, ZERO, Y, Y)
    SWIZZLE4(x0yz, X, ZERO, Y, Z)
    SWIZZLE4(x0yw, X, ZERO, Y, W)
    SWIZZLE4(x0y0, X, ZERO, Y, ZERO)
    SWIZZLE4(x0y1, X, ZERO, Y, ONE)
    SWIZZLE4(x0zx, X, ZERO, Z, X)
    SWIZZLE4(x0zy, X, ZERO, Z, Y)
    SWIZZLE4(x0zz, X, ZERO, Z, Z)
    SWIZZLE4(x0zw, X, ZERO, Z, W)
    SWIZZLE4(x0z0, X, ZERO, Z, ZERO)
    SWIZZLE4(x0z1, X, ZERO, Z, ONE)
    SWIZZLE4(x0wx, X, ZERO, W, X)
    SWIZZLE4(x0wy, X, ZERO, W, Y)
    SWIZZLE4(x0wz, X, ZERO, W, Z)
    SWIZZLE4(x0ww, X, ZERO, W, W)
    SWIZZLE4(x0w0, X, ZERO, W, ZERO)
    SWIZZLE4(x0w1, X, ZERO, W, ONE)
    SWIZZLE4(x00x, X, ZERO, ZERO, X)
    SWIZZLE4(x00y, X, ZERO, ZERO, Y)
    SWIZZLE4(x00z, X, ZERO, ZERO, Z)
    SWIZZLE4(x00w, X, ZERO, ZERO, W)
    SWIZZLE4(x000, X, ZERO, ZERO, ZERO)
    SWIZZLE4(x001, X, ZERO, ZERO, ONE)
    SWIZZLE4(x01x, X, ZERO, ONE, X)
    SWIZZLE4(x01y, X, ZERO, ONE, Y)
    SWIZZLE4(x01z, X, ZERO, ONE, Z)
    SWIZZLE4(x01w, X, ZERO, ONE, W)
    SWIZZLE4(x010, X, ZERO, ONE, ZERO)
    SWIZZLE4(x011, X, ZERO, ONE, ONE)
    SWIZZLE4(x1xx, X, ONE, X, X)
    SWIZZLE4(x1xy, X, ONE, X, Y)
    SWIZZLE4(x1xz, X, ONE, X, Z)
    SWIZZLE4(x1xw, X, ONE, X, W)
    SWIZZLE4(x1x0, X, ONE, X, ZERO)
    SWIZZLE4(x1x1, X, ONE, X, ONE)
    SWIZZLE4(x1yx, X, ONE, Y, X)
    SWIZZLE4(x1yy, X, ONE, Y, Y)
    SWIZZLE4(x1yz, X, ONE, Y, Z)
    SWIZZLE4(x1yw, X, ONE, Y, W)
    SWIZZLE4(x1y0, X, ONE, Y, ZERO)
    SWIZZLE4(x1y1, X, ONE, Y, ONE)
    SWIZZLE4(x1zx, X, ONE, Z, X)
    SWIZZLE4(x1zy, X, ONE, Z, Y)
    SWIZZLE4(x1zz, X, ONE, Z, Z)
    SWIZZLE4(x1zw, X, ONE, Z, W)
    SWIZZLE4(x1z0, X, ONE, Z, ZERO)
    SWIZZLE4(x1z1, X, ONE, Z, ONE)
    SWIZZLE4(x1wx, X, ONE, W, X)
    SWIZZLE4(x1wy, X, ONE, W, Y)
    SWIZZLE4(x1wz, X, ONE, W, Z)
    SWIZZLE4(x1ww, X, ONE, W, W)
    SWIZZLE4(x1w0, X, ONE, W, ZERO)
    SWIZZLE4(x1w1, X, ONE, W, ONE)
    SWIZZLE4(x10x, X, ONE, ZERO, X)
    SWIZZLE4(x10y, X, ONE, ZERO, Y)
    SWIZZLE4(x10z, X, ONE, ZERO, Z)
    SWIZZLE4(x10w, X, ONE, ZERO, W)
    SWIZZLE4(x100, X, ONE, ZERO, ZERO)
    SWIZZLE4(x101, X, ONE, ZERO, ONE)
    SWIZZLE4(x11x, X, ONE, ONE, X)
    SWIZZLE4(x11y, X, ONE, ONE, Y)
    SWIZZLE4(x11z, X, ONE, ONE, Z)
    SWIZZLE4(x11w, X, ONE, ONE, W)
    SWIZZLE4(x110, X, ONE, ONE, ZERO)
    SWIZZLE4(x111, X, ONE, ONE, ONE)
    SWIZZLE4(yxxx, Y, X, X, X)
    SWIZZLE4(yxxy, Y, X, X, Y)
    SWIZZLE4(yxxz, Y, X, X, Z)
    SWIZZLE4(yxxw, Y, X, X, W)
    SWIZZLE4(yxx0, Y, X, X, ZERO)
    SWIZZLE4(yxx1, Y, X, X, ONE)
    SWIZZLE4(yxyx, Y, X, Y, X)
    SWIZZLE4(yxyy, Y, X, Y, Y)
    SWIZZLE4(yxyz, Y, X, Y, Z)
    SWIZZLE4(yxyw, Y, X, Y, W)
    SWIZZLE4(yxy0, Y, X, Y, ZERO)
    SWIZZLE4(yxy1, Y, X, Y, ONE)
    SWIZZLE4(yxzx, Y, X, Z, X)
    SWIZZLE4(yxzy, Y, X, Z, Y)
    SWIZZLE4(yxzz, Y, X, Z, Z)
    SWIZZLE4(yxzw, Y, X, Z, W)
    SWIZZLE4(yxz0, Y, X, Z, ZERO)
    SWIZZLE4(yxz1, Y, X, Z, ONE)
    SWIZZLE4(yxwx, Y, X, W, X)
    SWIZZLE4(yxwy, Y, X, W, Y)
    SWIZZLE4(yxwz, Y, X, W, Z)
    SWIZZLE4(yxww, Y, X, W, W)
    SWIZZLE4(yxw0, Y, X, W, ZERO)
    SWIZZLE4(yxw1, Y, X, W, ONE)
    SWIZZLE4(yx0x, Y, X, ZERO, X)
    SWIZZLE4(yx0y, Y, X, ZERO, Y)
    SWIZZLE4(yx0z, Y, X, ZERO, Z)
    SWIZZLE4(yx0w, Y, X, ZERO, W)
    SWIZZLE4(yx00, Y, X, ZERO, ZERO)
    SWIZZLE4(yx01, Y, X, ZERO, ONE)
    SWIZZLE4(yx1x, Y, X, ONE, X)
    SWIZZLE4(yx1y, Y, X, ONE, Y)
    SWIZZLE4(yx1z, Y, X, ONE, Z)
    SWIZZLE4(yx1w, Y, X, ONE, W)
    SWIZZLE4(yx10, Y, X, ONE, ZERO)
    SWIZZLE4(yx11, Y, X, ONE, ONE)
    SWIZZLE4(yyxx, Y, Y, X, X)
    SWIZZLE4(yyxy, Y, Y, X, Y)
    SWIZZLE4(yyxz, Y, Y, X, Z)
    SWIZZLE4(yyxw, Y, Y, X, W)
    SWIZZLE4(yyx0, Y, Y, X, ZERO)
    SWIZZLE4(yyx1, Y, Y, X, ONE)
    SWIZZLE4(yyyx, Y, Y, Y, X)
    SWIZZLE4(yyyy, Y, Y, Y, Y)
    SWIZZLE4(yyyz, Y, Y, Y, Z)
    SWIZZLE4(yyyw, Y, Y, Y, W)
    SWIZZLE4(yyy0, Y, Y, Y, ZERO)
    SWIZZLE4(yyy1, Y, Y, Y, ONE)
    SWIZZLE4(yyzx, Y, Y, Z, X)
    SWIZZLE4(yyzy, Y, Y, Z, Y)
    SWIZZLE4(yyzz, Y, Y, Z, Z)
    SWIZZLE4(yyzw, Y, Y, Z, W)
    SWIZZLE4(yyz0, Y, Y, Z, ZERO)
    SWIZZLE4(yyz1, Y, Y, Z, ONE)
    SWIZZLE4(yywx, Y, Y, W, X)
    SWIZZLE4(yywy, Y, Y, W, Y)
    SWIZZLE4(yywz, Y, Y, W, Z)
    SWIZZLE4(yyww, Y, Y, W, W)
    SWIZZLE4(yyw0, Y, Y, W, ZERO)
    SWIZZLE4(yyw1, Y, Y, W, ONE)
    SWIZZLE4(yy0x, Y, Y, ZERO, X)
    SWIZZLE4(yy0y, Y, Y, ZERO, Y)
    SWIZZLE4(yy0z, Y, Y, ZERO, Z)
    SWIZZLE4(yy0w, Y, Y, ZERO, W)
    SWIZZLE4(yy00, Y, Y, ZERO, ZERO)
    SWIZZLE4(yy01, Y, Y, ZERO, ONE)
    SWIZZLE4(yy1x, Y, Y, ONE, X)
    SWIZZLE4(yy1y, Y, Y, ONE, Y)
    SWIZZLE4(yy1z, Y, Y, ONE, Z)
    SWIZZLE4(yy1w, Y, Y, ONE, W)
    SWIZZLE4(yy10, Y, Y, ONE, ZERO)
    SWIZZLE4(yy11, Y, Y, ONE, ONE)
    SWIZZLE4(yzxx, Y, Z, X, X)
    SWIZZLE4(yzxy, Y, Z, X, Y)
    SWIZZLE4(yzxz, Y, Z, X, Z)
    SWIZZLE4(yzxw, Y, Z, X, W)
    SWIZZLE4(yzx0, Y, Z, X, ZERO)
    SWIZZLE4(yzx1, Y, Z, X, ONE)
    SWIZZLE4(yzyx, Y, Z, Y, X)
    SWIZZLE4(yzyy, Y, Z, Y, Y)
    SWIZZLE4(yzyz, Y, Z, Y, Z)
    SWIZZLE4(yzyw, Y, Z, Y, W)
    SWIZZLE4(yzy0, Y, Z, Y, ZERO)
    SWIZZLE4(yzy1, Y, Z, Y, ONE)
    SWIZZLE4(yzzx, Y, Z, Z, X)
    SWIZZLE4(yzzy, Y, Z, Z, Y)
    SWIZZLE4(yzzz, Y, Z, Z, Z)
    SWIZZLE4(yzzw, Y, Z, Z, W)
    SWIZZLE4(yzz0, Y, Z, Z, ZERO)
    SWIZZLE4(yzz1, Y, Z, Z, ONE)
    SWIZZLE4(yzwx, Y, Z, W, X)
    SWIZZLE4(yzwy, Y, Z, W, Y)
    SWIZZLE4(yzwz, Y, Z, W, Z)
    SWIZZLE4(yzww, Y, Z, W, W)
    SWIZZLE4(yzw0, Y, Z, W, ZERO)
    SWIZZLE4(yzw1, Y, Z, W, ONE)
    SWIZZLE4(yz0x, Y, Z, ZERO, X)
    SWIZZLE4(yz0y, Y, Z, ZERO, Y)
    SWIZZLE4(yz0z, Y, Z, ZERO, Z)
    SWIZZLE4(yz0w, Y, Z, ZERO, W)
    SWIZZLE4(yz00, Y, Z, ZERO, ZERO)
    SWIZZLE4(yz01, Y, Z, ZERO, ONE)
    SWIZZLE4(yz1x, Y, Z, ONE, X)
    SWIZZLE4(yz1y, Y, Z, ONE, Y)
    SWIZZLE4(yz1z, Y, Z, ONE, Z)
    SWIZZLE4(yz1w, Y, Z, ONE, W)
    SWIZZLE4(yz10, Y, Z, ONE, ZERO)
    SWIZZLE4(yz11, Y, Z, ONE, ONE)
    SWIZZLE4(ywxx, Y, W, X, X)
    SWIZZLE4(ywxy, Y, W, X, Y)
    SWIZZLE4(ywxz, Y, W, X, Z)
    SWIZZLE4(ywxw, Y, W, X, W)
    SWIZZLE4(ywx0, Y, W, X, ZERO)
    SWIZZLE4(ywx1, Y, W, X, ONE)
    SWIZZLE4(ywyx, Y, W, Y, X)
    SWIZZLE4(ywyy, Y, W, Y, Y)
    SWIZZLE4(ywyz, Y, W, Y, Z)
    SWIZZLE4(ywyw, Y, W, Y, W)
    SWIZZLE4(ywy0, Y, W, Y, ZERO)
    SWIZZLE4(ywy1, Y, W, Y, ONE)
    SWIZZLE4(ywzx, Y, W, Z, X)
    SWIZZLE4(ywzy, Y, W, Z, Y)
    SWIZZLE4(ywzz, Y, W, Z, Z)
    SWIZZLE4(ywzw, Y, W, Z, W)
    SWIZZLE4(ywz0, Y, W, Z, ZERO)
    SWIZZLE4(ywz1, Y, W, Z, ONE)
    SWIZZLE4(ywwx, Y, W, W, X)
    SWIZZLE4(ywwy, Y, W, W, Y)
    SWIZZLE4(ywwz, Y, W, W, Z)
    SWIZZLE4(ywww, Y, W, W, W)
    SWIZZLE4(yww0, Y, W, W, ZERO)
    SWIZZLE4(yww1, Y, W, W, ONE)
    SWIZZLE4(yw0x, Y, W, ZERO, X)
    SWIZZLE4(yw0y, Y, W, ZERO, Y)
    SWIZZLE4(yw0z, Y, W, ZERO, Z)
    SWIZZLE4(yw0w, Y, W, ZERO, W)
    SWIZZLE4(yw00, Y, W, ZERO, ZERO)
    SWIZZLE4(yw01, Y, W, ZERO, ONE)
    SWIZZLE4(yw1x, Y, W, ONE, X)
    SWIZZLE4(yw1y, Y, W, ONE, Y)
    SWIZZLE4(yw1z, Y, W, ONE, Z)
    SWIZZLE4(yw1w, Y, W, ONE, W)
    SWIZZLE4(yw10, Y, W, ONE, ZERO)
    SWIZZLE4(yw11, Y, W, ONE, ONE)
    SWIZZLE4(y0xx, Y, ZERO, X, X)
    SWIZZLE4(y0xy, Y, ZERO, X, Y)
    SWIZZLE4(y0xz, Y, ZERO, X, Z)
    SWIZZLE4(y0xw, Y, ZERO, X, W)
    SWIZZLE4(y0x0, Y, ZERO, X, ZERO)
    SWIZZLE4(y0x1, Y, ZERO, X, ONE)
    SWIZZLE4(y0yx, Y, ZERO, Y, X)
    SWIZZLE4(y0yy, Y, ZERO, Y, Y)
    SWIZZLE4(y0yz, Y, ZERO, Y, Z)
    SWIZZLE4(y0yw, Y, ZERO, Y, W)
    SWIZZLE4(y0y0, Y, ZERO, Y, ZERO)
    SWIZZLE4(y0y1, Y, ZERO, Y, ONE)
    SWIZZLE4(y0zx, Y, ZERO, Z, X)
    SWIZZLE4(y0zy, Y, ZERO, Z, Y)
    SWIZZLE4(y0zz, Y, ZERO, Z, Z)
    SWIZZLE4(y0zw, Y, ZERO, Z, W)
    SWIZZLE4(y0z0, Y, ZERO, Z, ZERO)
    SWIZZLE4(y0z1, Y, ZERO, Z, ONE)
    SWIZZLE4(y0wx, Y, ZERO, W, X)
    SWIZZLE4(y0wy, Y, ZERO, W, Y)
    SWIZZLE4(y0wz, Y, ZERO, W, Z)
    SWIZZLE4(y0ww, Y, ZERO, W, W)
    SWIZZLE4(y0w0, Y, ZERO, W, ZERO)
    SWIZZLE4(y0w1, Y, ZERO, W, ONE)
    SWIZZLE4(y00x, Y, ZERO, ZERO, X)
    SWIZZLE4(y00y, Y, ZERO, ZERO, Y)
    SWIZZLE4(y00z, Y, ZERO, ZERO, Z)
    SWIZZLE4(y00w, Y, ZERO, ZERO, W)
    SWIZZLE4(y000, Y, ZERO, ZERO, ZERO)
    SWIZZLE4(y001, Y, ZERO, ZERO, ONE)
    SWIZZLE4(y01x, Y, ZERO, ONE, X)
    SWIZZLE4(y01y, Y, ZERO, ONE, Y)
    SWIZZLE4(y01z, Y, ZERO, ONE, Z)
    SWIZZLE4(y01w, Y, ZERO, ONE, W)
    SWIZZLE4(y010, Y, ZERO, ONE, ZERO)
    SWIZZLE4(y011, Y, ZERO, ONE, ONE)
    SWIZZLE4(y1xx, Y, ONE, X, X)
    SWIZZLE4(y1xy, Y, ONE, X, Y)
    SWIZZLE4(y1xz, Y, ONE, X, Z)
    SWIZZLE4(y1xw, Y, ONE, X, W)
    SWIZZLE4(y1x0, Y, ONE, X, ZERO)
    SWIZZLE4(y1x1, Y, ONE, X, ONE)
    SWIZZLE4(y1yx, Y, ONE, Y, X)
    SWIZZLE4(y1yy, Y, ONE, Y, Y)
    SWIZZLE4(y1yz, Y, ONE, Y, Z)
    SWIZZLE4(y1yw, Y, ONE, Y, W)
    SWIZZLE4(y1y0, Y, ONE, Y, ZERO)
    SWIZZLE4(y1y1, Y, ONE, Y, ONE)
    SWIZZLE4(y1zx, Y, ONE, Z, X)
    SWIZZLE4(y1zy, Y, ONE, Z, Y)
    SWIZZLE4(y1zz, Y, ONE, Z, Z)
    SWIZZLE4(y1zw, Y, ONE, Z, W)
    SWIZZLE4(y1z0, Y, ONE, Z, ZERO)
    SWIZZLE4(y1z1, Y, ONE, Z, ONE)
    SWIZZLE4(y1wx, Y, ONE, W, X)
    SWIZZLE4(y1wy, Y, ONE, W, Y)
    SWIZZLE4(y1wz, Y, ONE, W, Z)
    SWIZZLE4(y1ww, Y, ONE, W, W)
    SWIZZLE4(y1w0, Y, ONE, W, ZERO)
    SWIZZLE4(y1w1, Y, ONE, W, ONE)
    SWIZZLE4(y10x, Y, ONE, ZERO, X)
    SWIZZLE4(y10y, Y, ONE, ZERO, Y)
    SWIZZLE4(y10z, Y, ONE, ZERO, Z)
    SWIZZLE4(y10w, Y, ONE, ZERO, W)
    SWIZZLE4(y100, Y, ONE, ZERO, ZERO)
    SWIZZLE4(y101, Y, ONE, ZERO, ONE)
    SWIZZLE4(y11x, Y, ONE, ONE, X)
    SWIZZLE4(y11y, Y, ONE, ONE, Y)
    SWIZZLE4(y11z, Y, ONE, ONE, Z)
    SWIZZLE4(y11w, Y, ONE, ONE, W)
    SWIZZLE4(y110, Y, ONE, ONE, ZERO)
    SWIZZLE4(y111, Y, ONE, ONE, ONE)
    SWIZZLE4(zxxx, Z, X, X, X)
    SWIZZLE4(zxxy, Z, X, X, Y)
    SWIZZLE4(zxxz, Z, X, X, Z)
    SWIZZLE4(zxxw, Z, X, X, W)
    SWIZZLE4(zxx0, Z, X, X, ZERO)
    SWIZZLE4(zxx1, Z, X, X, ONE)
    SWIZZLE4(zxyx, Z, X, Y, X)
    SWIZZLE4(zxyy, Z, X, Y, Y)
    SWIZZLE4(zxyz, Z, X, Y, Z)
    SWIZZLE4(zxyw, Z, X, Y, W)
    SWIZZLE4(zxy0, Z, X, Y, ZERO)
    SWIZZLE4(zxy1, Z, X, Y, ONE)
    SWIZZLE4(zxzx, Z, X, Z, X)
    SWIZZLE4(zxzy, Z, X, Z, Y)
    SWIZZLE4(zxzz, Z, X, Z, Z)
    SWIZZLE4(zxzw, Z, X, Z, W)
    SWIZZLE4(zxz0, Z, X, Z, ZERO)
    SWIZZLE4(zxz1, Z, X, Z, ONE)
    SWIZZLE4(zxwx, Z, X, W, X)
    SWIZZLE4(zxwy, Z, X, W, Y)
    SWIZZLE4(zxwz, Z, X, W, Z)
    SWIZZLE4(zxww, Z, X, W, W)
    SWIZZLE4(zxw0, Z, X, W, ZERO)
    SWIZZLE4(zxw1, Z, X, W, ONE)
    SWIZZLE4(zx0x, Z, X, ZERO, X)
    SWIZZLE4(zx0y, Z, X, ZERO, Y)
    SWIZZLE4(zx0z, Z, X, ZERO, Z)
    SWIZZLE4(zx0w, Z, X, ZERO, W)
    SWIZZLE4(zx00, Z, X, ZERO, ZERO)
    SWIZZLE4(zx01, Z, X, ZERO, ONE)
    SWIZZLE4(zx1x, Z, X, ONE, X)
    SWIZZLE4(zx1y, Z, X, ONE, Y)
    SWIZZLE4(zx1z, Z, X, ONE, Z)
    SWIZZLE4(zx1w, Z, X, ONE, W)
    SWIZZLE4(zx10, Z, X, ONE, ZERO)
    SWIZZLE4(zx11, Z, X, ONE, ONE)
    SWIZZLE4(zyxx, Z, Y, X, X)
    SWIZZLE4(zyxy, Z, Y, X, Y)
    SWIZZLE4(zyxz, Z, Y, X, Z)
    SWIZZLE4(zyxw, Z, Y, X, W)
    SWIZZLE4(zyx0, Z, Y, X, ZERO)
    SWIZZLE4(zyx1, Z, Y, X, ONE)
    SWIZZLE4(zyyx, Z, Y, Y, X)
    SWIZZLE4(zyyy, Z, Y, Y, Y)
    SWIZZLE4(zyyz, Z, Y, Y, Z)
    SWIZZLE4(zyyw, Z, Y, Y, W)
    SWIZZLE4(zyy0, Z, Y, Y, ZERO)
    SWIZZLE4(zyy1, Z, Y, Y, ONE)
    SWIZZLE4(zyzx, Z, Y, Z, X)
    SWIZZLE4(zyzy, Z, Y, Z, Y)
    SWIZZLE4(zyzz, Z, Y, Z, Z)
    SWIZZLE4(zyzw, Z, Y, Z, W)
    SWIZZLE4(zyz0, Z, Y, Z, ZERO)
    SWIZZLE4(zyz1, Z, Y, Z, ONE)
    SWIZZLE4(zywx, Z, Y, W, X)
    SWIZZLE4(zywy, Z, Y, W, Y)
    SWIZZLE4(zywz, Z, Y, W, Z)
    SWIZZLE4(zyww, Z, Y, W, W)
    SWIZZLE4(zyw0, Z, Y, W, ZERO)
    SWIZZLE4(zyw1, Z, Y, W, ONE)
    SWIZZLE4(zy0x, Z, Y, ZERO, X)
    SWIZZLE4(zy0y, Z, Y, ZERO, Y)
    SWIZZLE4(zy0z, Z, Y, ZERO, Z)
    SWIZZLE4(zy0w, Z, Y, ZERO, W)
    SWIZZLE4(zy00, Z, Y, ZERO, ZERO)
    SWIZZLE4(zy01, Z, Y, ZERO, ONE)
    SWIZZLE4(zy1x, Z, Y, ONE, X)
    SWIZZLE4(zy1y, Z, Y, ONE, Y)
    SWIZZLE4(zy1z, Z, Y, ONE, Z)
    SWIZZLE4(zy1w, Z, Y, ONE, W)
    SWIZZLE4(zy10, Z, Y, ONE, ZERO)
    SWIZZLE4(zy11, Z, Y, ONE, ONE)
    SWIZZLE4(zzxx, Z, Z, X, X)
    SWIZZLE4(zzxy, Z, Z, X, Y)
    SWIZZLE4(zzxz, Z, Z, X, Z)
    SWIZZLE4(zzxw, Z, Z, X, W)
    SWIZZLE4(zzx0, Z, Z, X, ZERO)
    SWIZZLE4(zzx1, Z, Z, X, ONE)
    SWIZZLE4(zzyx, Z, Z, Y, X)
    SWIZZLE4(zzyy, Z, Z, Y, Y)
    SWIZZLE4(zzyz, Z, Z, Y, Z)
    SWIZZLE4(zzyw, Z, Z, Y, W)
    SWIZZLE4(zzy0, Z, Z, Y, ZERO)
    SWIZZLE4(zzy1, Z, Z, Y, ONE)
    SWIZZLE4(zzzx, Z, Z, Z, X)
    SWIZZLE4(zzzy, Z, Z, Z, Y)
    SWIZZLE4(zzzz, Z, Z, Z, Z)
    SWIZZLE4(zzzw, Z, Z, Z, W)
    SWIZZLE4(zzz0, Z, Z, Z, ZERO)
    SWIZZLE4(zzz1, Z, Z, Z, ONE)
    SWIZZLE4(zzwx, Z, Z, W, X)
    SWIZZLE4(zzwy, Z, Z, W, Y)
    SWIZZLE4(zzwz, Z, Z, W, Z)
    SWIZZLE4(zzww, Z, Z, W, W)
    SWIZZLE4(zzw0, Z, Z, W, ZERO)
    SWIZZLE4(zzw1, Z, Z, W, ONE)
    SWIZZLE4(zz0x, Z, Z, ZERO, X)
    SWIZZLE4(zz0y, Z, Z, ZERO, Y)
    SWIZZLE4(zz0z, Z, Z, ZERO, Z)
    SWIZZLE4(zz0w, Z, Z, ZERO, W)
    SWIZZLE4(zz00, Z, Z, ZERO, ZERO)
    SWIZZLE4(zz01, Z, Z, ZERO, ONE)
    SWIZZLE4(zz1x, Z, Z, ONE, X)
    SWIZZLE4(zz1y, Z, Z, ONE, Y)
    SWIZZLE4(zz1z, Z, Z, ONE, Z)
    SWIZZLE4(zz1w, Z, Z, ONE, W)
    SWIZZLE4(zz10, Z, Z, ONE, ZERO)
    SWIZZLE4(zz11, Z, Z, ONE, ONE)
    SWIZZLE4(zwxx, Z, W, X, X)
    SWIZZLE4(zwxy, Z, W, X, Y)
    SWIZZLE4(zwxz, Z, W, X, Z)
    SWIZZLE4(zwxw, Z, W, X, W)
    SWIZZLE4(zwx0, Z, W, X, ZERO)
    SWIZZLE4(zwx1, Z, W, X, ONE)
    SWIZZLE4(zwyx, Z, W, Y, X)
    SWIZZLE4(zwyy, Z, W, Y, Y)
    SWIZZLE4(zwyz, Z, W, Y, Z)
    SWIZZLE4(zwyw, Z, W, Y, W)
    SWIZZLE4(zwy0, Z, W, Y, ZERO)
    SWIZZLE4(zwy1, Z, W, Y, ONE)
    SWIZZLE4(zwzx, Z, W, Z, X)
    SWIZZLE4(zwzy, Z, W, Z, Y)
    SWIZZLE4(zwzz, Z, W, Z, Z)
    SWIZZLE4(zwzw, Z, W, Z, W)
    SWIZZLE4(zwz0, Z, W, Z, ZERO)
    SWIZZLE4(zwz1, Z, W, Z, ONE)
    SWIZZLE4(zwwx, Z, W, W, X)
    SWIZZLE4(zwwy, Z, W, W, Y)
    SWIZZLE4(zwwz, Z, W, W, Z)
    SWIZZLE4(zwww, Z, W, W, W)
    SWIZZLE4(zww0, Z, W, W, ZERO)
    SWIZZLE4(zww1, Z, W, W, ONE)
    SWIZZLE4(zw0x, Z, W, ZERO, X)
    SWIZZLE4(zw0y, Z, W, ZERO, Y)
    SWIZZLE4(zw0z, Z, W, ZERO, Z)
    SWIZZLE4(zw0w, Z, W, ZERO, W)
    SWIZZLE4(zw00, Z, W, ZERO, ZERO)
    SWIZZLE4(zw01, Z, W, ZERO, ONE)
    SWIZZLE4(zw1x, Z, W, ONE, X)
    SWIZZLE4(zw1y, Z, W, ONE, Y)
    SWIZZLE4(zw1z, Z, W, ONE, Z)
    SWIZZLE4(zw1w, Z, W, ONE, W)
    SWIZZLE4(zw10, Z, W, ONE, ZERO)
    SWIZZLE4(zw11, Z, W, ONE, ONE)
    SWIZZLE4(z0xx, Z, ZERO, X, X)
    SWIZZLE4(z0xy, Z, ZERO, X, Y)
    SWIZZLE4(z0xz, Z, ZERO, X, Z)
    SWIZZLE4(z0xw, Z, ZERO, X, W)
    SWIZZLE4(z0x0, Z, ZERO, X, ZERO)
    SWIZZLE4(z0x1, Z, ZERO, X, ONE)
    SWIZZLE4(z0yx, Z, ZERO, Y, X)
    SWIZZLE4(z0yy, Z, ZERO, Y, Y)
    SWIZZLE4(z0yz, Z, ZERO, Y, Z)
    SWIZZLE4(z0yw, Z, ZERO, Y, W)
    SWIZZLE4(z0y0, Z, ZERO, Y, ZERO)
    SWIZZLE4(z0y1, Z, ZERO, Y, ONE)
    SWIZZLE4(z0zx, Z, ZERO, Z, X)
    SWIZZLE4(z0zy, Z, ZERO, Z, Y)
    SWIZZLE4(z0zz, Z, ZERO, Z, Z)
    SWIZZLE4(z0zw, Z, ZERO, Z, W)
    SWIZZLE4(z0z0, Z, ZERO, Z, ZERO)
    SWIZZLE4(z0z1, Z, ZERO, Z, ONE)
    SWIZZLE4(z0wx, Z, ZERO, W, X)
    SWIZZLE4(z0wy, Z, ZERO, W, Y)
    SWIZZLE4(z0wz, Z, ZERO, W, Z)
    SWIZZLE4(z0ww, Z, ZERO, W, W)
    SWIZZLE4(z0w0, Z, ZERO, W, ZERO)
    SWIZZLE4(z0w1, Z, ZERO, W, ONE)
    SWIZZLE4(z00x, Z, ZERO, ZERO, X)
    SWIZZLE4(z00y, Z, ZERO, ZERO, Y)
    SWIZZLE4(z00z, Z, ZERO, ZERO, Z)
    SWIZZLE4(z00w, Z, ZERO, ZERO, W)
    SWIZZLE4(z000, Z, ZERO, ZERO, ZERO)
    SWIZZLE4(z001, Z, ZERO, ZERO, ONE)
    SWIZZLE4(z01x, Z, ZERO, ONE, X)
    SWIZZLE4(z01y, Z, ZERO, ONE, Y)
    SWIZZLE4(z01z, Z, ZERO, ONE, Z)
    SWIZZLE4(z01w, Z, ZERO, ONE, W)
    SWIZZLE4(z010, Z, ZERO, ONE, ZERO)
    SWIZZLE4(z011, Z, ZERO, ONE, ONE)
    SWIZZLE4(z1xx, Z, ONE, X, X)
    SWIZZLE4(z1xy, Z, ONE, X, Y)
    SWIZZLE4(z1xz, Z, ONE, X, Z)
    SWIZZLE4(z1xw, Z, ONE, X, W)
    SWIZZLE4(z1x0, Z, ONE, X, ZERO)
    SWIZZLE4(z1x1, Z, ONE, X, ONE)
    SWIZZLE4(z1yx, Z, ONE, Y, X)
    SWIZZLE4(z1yy, Z, ONE, Y, Y)
    SWIZZLE4(z1yz, Z, ONE, Y, Z)
    SWIZZLE4(z1yw, Z, ONE, Y, W)
    SWIZZLE4(z1y0, Z, ONE, Y, ZERO)
    SWIZZLE4(z1y1, Z, ONE, Y, ONE)
    SWIZZLE4(z1zx, Z, ONE, Z, X)
    SWIZZLE4(z1zy, Z, ONE, Z, Y)
    SWIZZLE4(z1zz, Z, ONE, Z, Z)
    SWIZZLE4(z1zw, Z, ONE, Z, W)
    SWIZZLE4(z1z0, Z, ONE, Z, ZERO)
    SWIZZLE4(z1z1, Z, ONE, Z, ONE)
    SWIZZLE4(z1wx, Z, ONE, W, X)
    SWIZZLE4(z1wy, Z, ONE, W, Y)
    SWIZZLE4(z1wz, Z, ONE, W, Z)
    SWIZZLE4(z1ww, Z, ONE, W, W)
    SWIZZLE4(z1w0, Z, ONE, W, ZERO)
    SWIZZLE4(z1w1, Z, ONE, W, ONE)
    SWIZZLE4(z10x, Z, ONE, ZERO, X)
    SWIZZLE4(z10y, Z, ONE, ZERO, Y)
    SWIZZLE4(z10z, Z, ONE, ZERO, Z)
    SWIZZLE4(z10w, Z, ONE, ZERO, W)
    SWIZZLE4(z100, Z, ONE, ZERO, ZERO)
    SWIZZLE4(z101, Z, ONE, ZERO, ONE)
    SWIZZLE4(z11x, Z, ONE, ONE, X)
    SWIZZLE4(z11y, Z, ONE, ONE, Y)
    SWIZZLE4(z11z, Z, ONE, ONE, Z)
    SWIZZLE4(z11w, Z, ONE, ONE, W)
    SWIZZLE4(z110, Z, ONE, ONE, ZERO)
    SWIZZLE4(z111, Z, ONE, ONE, ONE)
    SWIZZLE4(wxxx, W, X, X, X)
    SWIZZLE4(wxxy, W, X, X, Y)
    SWIZZLE4(wxxz, W, X, X, Z)
    SWIZZLE4(wxxw, W, X, X, W)
    SWIZZLE4(wxx0, W, X, X, ZERO)
    SWIZZLE4(wxx1, W, X, X, ONE)
    SWIZZLE4(wxyx, W, X, Y, X)
    SWIZZLE4(wxyy, W, X, Y, Y)
    SWIZZLE4(wxyz, W, X, Y, Z)
    SWIZZLE4(wxyw, W, X, Y, W)
    SWIZZLE4(wxy0, W, X, Y, ZERO)
    SWIZZLE4(wxy1, W, X, Y, ONE)
    SWIZZLE4(wxzx, W, X, Z, X)
    SWIZZLE4(wxzy, W, X, Z, Y)
    SWIZZLE4(wxzz, W, X, Z, Z)
    SWIZZLE4(wxzw, W, X, Z, W)
    SWIZZLE4(wxz0, W, X, Z, ZERO)
    SWIZZLE4(wxz1, W, X, Z, ONE)
    SWIZZLE4(wxwx, W, X, W, X)
    SWIZZLE4(wxwy, W, X, W, Y)
    SWIZZLE4(wxwz, W, X, W, Z)
    SWIZZLE4(wxww, W, X, W, W)
    SWIZZLE4(wxw0, W, X, W, ZERO)
    SWIZZLE4(wxw1, W, X, W, ONE)
    SWIZZLE4(wx0x, W, X, ZERO, X)
    SWIZZLE4(wx0y, W, X, ZERO, Y)
    SWIZZLE4(wx0z, W, X, ZERO, Z)
    SWIZZLE4(wx0w, W, X, ZERO, W)
    SWIZZLE4(wx00, W, X, ZERO, ZERO)
    SWIZZLE4(wx01, W, X, ZERO, ONE)
    SWIZZLE4(wx1x, W, X, ONE, X)
    SWIZZLE4(wx1y, W, X, ONE, Y)
    SWIZZLE4(wx1z, W, X, ONE, Z)
    SWIZZLE4(wx1w, W, X, ONE, W)
    SWIZZLE4(wx10, W, X, ONE, ZERO)
    SWIZZLE4(wx11, W, X, ONE, ONE)
    SWIZZLE4(wyxx, W, Y, X, X)
    SWIZZLE4(wyxy, W, Y, X, Y)
    SWIZZLE4(wyxz, W, Y, X, Z)
    SWIZZLE4(wyxw, W, Y, X, W)
    SWIZZLE4(wyx0, W, Y, X, ZERO)
    SWIZZLE4(wyx1, W, Y, X, ONE)
    SWIZZLE4(wyyx, W, Y, Y, X)
    SWIZZLE4(wyyy, W, Y, Y, Y)
    SWIZZLE4(wyyz, W, Y, Y, Z)
    SWIZZLE4(wyyw, W, Y, Y, W)
    SWIZZLE4(wyy0, W, Y, Y, ZERO)
    SWIZZLE4(wyy1, W, Y, Y, ONE)
    SWIZZLE4(wyzx, W, Y, Z, X)
    SWIZZLE4(wyzy, W, Y, Z, Y)
    SWIZZLE4(wyzz, W, Y, Z, Z)
    SWIZZLE4(wyzw, W, Y, Z, W)
    SWIZZLE4(wyz0, W, Y, Z, ZERO)
    SWIZZLE4(wyz1, W, Y, Z, ONE)
    SWIZZLE4(wywx, W, Y, W, X)
    SWIZZLE4(wywy, W, Y, W, Y)
    SWIZZLE4(wywz, W, Y, W, Z)
    SWIZZLE4(wyww, W, Y, W, W)
    SWIZZLE4(wyw0, W, Y, W, ZERO)
    SWIZZLE4(wyw1, W, Y, W, ONE)
    SWIZZLE4(wy0x, W, Y, ZERO, X)
    SWIZZLE4(wy0y, W, Y, ZERO, Y)
    SWIZZLE4(wy0z, W, Y, ZERO, Z)
    SWIZZLE4(wy0w, W, Y, ZERO, W)
    SWIZZLE4(wy00, W, Y, ZERO, ZERO)
    SWIZZLE4(wy01, W, Y, ZERO, ONE)
    SWIZZLE4(wy1x, W, Y, ONE, X)
    SWIZZLE4(wy1y, W, Y, ONE, Y)
    SWIZZLE4(wy1z, W, Y, ONE, Z)
    SWIZZLE4(wy1w, W, Y, ONE, W)
    SWIZZLE4(wy10, W, Y, ONE, ZERO)
    SWIZZLE4(wy11, W, Y, ONE, ONE)
    SWIZZLE4(wzxx, W, Z, X, X)
    SWIZZLE4(wzxy, W, Z, X, Y)
    SWIZZLE4(wzxz, W, Z, X, Z)
    SWIZZLE4(wzxw, W, Z, X, W)
    SWIZZLE4(wzx0, W, Z, X, ZERO)
    SWIZZLE4(wzx1, W, Z, X, ONE)
    SWIZZLE4(wzyx, W, Z, Y, X)
    SWIZZLE4(wzyy, W, Z, Y, Y)
    SWIZZLE4(wzyz, W, Z, Y, Z)
    SWIZZLE4(wzyw, W, Z, Y, W)
    SWIZZLE4(wzy0, W, Z, Y, ZERO)
    SWIZZLE4(wzy1, W, Z, Y, ONE)
    SWIZZLE4(wzzx, W, Z, Z, X)
    SWIZZLE4(wzzy, W, Z, Z, Y)
    SWIZZLE4(wzzz, W, Z, Z, Z)
    SWIZZLE4(wzzw, W, Z, Z, W)
    SWIZZLE4(wzz0, W, Z, Z, ZERO)
    SWIZZLE4(wzz1, W, Z, Z, ONE)
    SWIZZLE4(wzwx, W, Z, W, X)
    SWIZZLE4(wzwy, W, Z, W, Y)
    SWIZZLE4(wzwz, W, Z, W, Z)
    SWIZZLE4(wzww, W, Z, W, W)
    SWIZZLE4(wzw0, W, Z, W, ZERO)
    SWIZZLE4(wzw1, W, Z, W, ONE)
    SWIZZLE4(wz0x, W, Z, ZERO, X)
    SWIZZLE4(wz0y, W, Z, ZERO, Y)
    SWIZZLE4(wz0z, W, Z, ZERO, Z)
    SWIZZLE4(wz0w, W, Z, ZERO, W)
    SWIZZLE4(wz00, W, Z, ZERO, ZERO)
    SWIZZLE4(wz01, W, Z, ZERO, ONE)
    SWIZZLE4(wz1x, W, Z, ONE, X)
    SWIZZLE4(wz1y, W, Z, ONE, Y)
    SWIZZLE4(wz1z, W, Z, ONE, Z)
    SWIZZLE4(wz1w, W, Z, ONE, W)
    SWIZZLE4(wz10, W, Z, ONE, ZERO)
    SWIZZLE4(wz11, W, Z, ONE, ONE)
    SWIZZLE4(wwxx, W, W, X, X)
    SWIZZLE4(wwxy, W, W, X, Y)
    SWIZZLE4(wwxz, W, W, X, Z)
    SWIZZLE4(wwxw, W, W, X, W)
    SWIZZLE4(wwx0, W, W, X, ZERO)
    SWIZZLE4(wwx1, W, W, X, ONE)
    SWIZZLE4(wwyx, W, W, Y, X)
    SWIZZLE4(wwyy, W, W, Y, Y)
    SWIZZLE4(wwyz, W, W, Y, Z)
    SWIZZLE4(wwyw, W, W, Y, W)
    SWIZZLE4(wwy0, W, W, Y, ZERO)
    SWIZZLE4(wwy1, W, W, Y, ONE)
    SWIZZLE4(wwzx, W, W, Z, X)
    SWIZZLE4(wwzy, W, W, Z, Y)
    SWIZZLE4(wwzz, W, W, Z, Z)
    SWIZZLE4(wwzw, W, W, Z, W)
    SWIZZLE4(wwz0, W, W, Z, ZERO)
    SWIZZLE4(wwz1, W, W, Z, ONE)
    SWIZZLE4(wwwx, W, W, W, X)
    SWIZZLE4(wwwy, W, W, W, Y)
    SWIZZLE4(wwwz, W, W, W, Z)
    SWIZZLE4(wwww, W, W, W, W)
    SWIZZLE4(www0, W, W, W, ZERO)
    SWIZZLE4(www1, W, W, W, ONE)
    SWIZZLE4(ww0x, W, W, ZERO, X)
    SWIZZLE4(ww0y, W, W, ZERO, Y)
    SWIZZLE4(ww0z, W, W, ZERO, Z)
    SWIZZLE4(ww0w, W, W, ZERO, W)
    SWIZZLE4(ww00, W, W, ZERO, ZERO)
    SWIZZLE4(ww01, W, W, ZERO, ONE)
    SWIZZLE4(ww1x, W, W, ONE, X)
    SWIZZLE4(ww1y, W, W, ONE, Y)
    SWIZZLE4(ww1z, W, W, ONE, Z)
    SWIZZLE4(ww1w, W, W, ONE, W)
    SWIZZLE4(ww10, W, W, ONE, ZERO)
    SWIZZLE4(ww11, W, W, ONE, ONE)
    SWIZZLE4(w0xx, W, ZERO, X, X)
    SWIZZLE4(w0xy, W, ZERO, X, Y)
    SWIZZLE4(w0xz, W, ZERO, X, Z)
    SWIZZLE4(w0xw, W, ZERO, X, W)
    SWIZZLE4(w0x0, W, ZERO, X, ZERO)
    SWIZZLE4(w0x1, W, ZERO, X, ONE)
    SWIZZLE4(w0yx, W, ZERO, Y, X)
    SWIZZLE4(w0yy, W, ZERO, Y, Y)
    SWIZZLE4(w0yz, W, ZERO, Y, Z)
    SWIZZLE4(w0yw, W, ZERO, Y, W)
    SWIZZLE4(w0y0, W, ZERO, Y, ZERO)
    SWIZZLE4(w0y1, W, ZERO, Y, ONE)
    SWIZZLE4(w0zx, W, ZERO, Z, X)
    SWIZZLE4(w0zy, W, ZERO, Z, Y)
    SWIZZLE4(w0zz, W, ZERO, Z, Z)
    SWIZZLE4(w0zw, W, ZERO, Z, W)
    SWIZZLE4(w0z0, W, ZERO, Z, ZERO)
    SWIZZLE4(w0z1, W, ZERO, Z, ONE)
    SWIZZLE4(w0wx, W, ZERO, W, X)
    SWIZZLE4(w0wy, W, ZERO, W, Y)
    SWIZZLE4(w0wz, W, ZERO, W, Z)
    SWIZZLE4(w0ww, W, ZERO, W, W)
    SWIZZLE4(w0w0, W, ZERO, W, ZERO)
    SWIZZLE4(w0w1, W, ZERO, W, ONE)
    SWIZZLE4(w00x, W, ZERO, ZERO, X)
    SWIZZLE4(w00y, W, ZERO, ZERO, Y)
    SWIZZLE4(w00z, W, ZERO, ZERO, Z)
    SWIZZLE4(w00w, W, ZERO, ZERO, W)
    SWIZZLE4(w000, W, ZERO, ZERO, ZERO)
    SWIZZLE4(w001, W, ZERO, ZERO, ONE)
    SWIZZLE4(w01x, W, ZERO, ONE, X)
    SWIZZLE4(w01y, W, ZERO, ONE, Y)
    SWIZZLE4(w01z, W, ZERO, ONE, Z)
    SWIZZLE4(w01w, W, ZERO, ONE, W)
    SWIZZLE4(w010, W, ZERO, ONE, ZERO)
    SWIZZLE4(w011, W, ZERO, ONE, ONE)
    SWIZZLE4(w1xx, W, ONE, X, X)
    SWIZZLE4(w1xy, W, ONE, X, Y)
    SWIZZLE4(w1xz, W, ONE, X, Z)
    SWIZZLE4(w1xw, W, ONE, X, W)
    SWIZZLE4(w1x0, W, ONE, X, ZERO)
    SWIZZLE4(w1x1, W, ONE, X, ONE)
    SWIZZLE4(w1yx, W, ONE, Y, X)
    SWIZZLE4(w1yy, W, ONE, Y, Y)
    SWIZZLE4(w1yz, W, ONE, Y, Z)
    SWIZZLE4(w1yw, W, ONE, Y, W)
    SWIZZLE4(w1y0, W, ONE, Y, ZERO)
    SWIZZLE4(w1y1, W, ONE, Y, ONE)
    SWIZZLE4(w1zx, W, ONE, Z, X)
    SWIZZLE4(w1zy, W, ONE, Z, Y)
    SWIZZLE4(w1zz, W, ONE, Z, Z)
    SWIZZLE4(w1zw, W, ONE, Z, W)
    SWIZZLE4(w1z0, W, ONE, Z, ZERO)
    SWIZZLE4(w1z1, W, ONE, Z, ONE)
    SWIZZLE4(w1wx, W, ONE, W, X)
    SWIZZLE4(w1wy, W, ONE, W, Y)
    SWIZZLE4(w1wz, W, ONE, W, Z)
    SWIZZLE4(w1ww, W, ONE, W, W)
    SWIZZLE4(w1w0, W, ONE, W, ZERO)
    SWIZZLE4(w1w1, W, ONE, W, ONE)
    SWIZZLE4(w10x, W, ONE, ZERO, X)
    SWIZZLE4(w10y, W, ONE, ZERO, Y)
    SWIZZLE4(w10z, W, ONE, ZERO, Z)
    SWIZZLE4(w10w, W, ONE, ZERO, W)
    SWIZZLE4(w100, W, ONE, ZERO, ZERO)
    SWIZZLE4(w101, W, ONE, ZERO, ONE)
    SWIZZLE4(w11x, W, ONE, ONE, X)
    SWIZZLE4(w11y, W, ONE, ONE, Y)
    SWIZZLE4(w11z, W, ONE, ONE, Z)
    SWIZZLE4(w11w, W, ONE, ONE, W)
    SWIZZLE4(w110, W, ONE, ONE, ZERO)
    SWIZZLE4(w111, W, ONE, ONE, ONE)
    SWIZZLE1(r, R)
    SWIZZLE1(g, G)
    SWIZZLE1(b, B)
    SWIZZLE1(a, A)
    SWIZZLE2(rr, R, R)
    SWIZZLE2(rg, R, G)
    SWIZZLE2(rb, R, B)
    SWIZZLE2(ra, R, A)
    SWIZZLE2(r0, R, ZERO)
    SWIZZLE2(r1, R, ONE)
    SWIZZLE2(gr, G, R)
    SWIZZLE2(gg, G, G)
    SWIZZLE2(gb, G, B)
    SWIZZLE2(ga, G, A)
    SWIZZLE2(g0, G, ZERO)
    SWIZZLE2(g1, G, ONE)
    SWIZZLE2(br, B, R)
    SWIZZLE2(bg, B, G)
    SWIZZLE2(bb, B, B)
    SWIZZLE2(ba, B, A)
    SWIZZLE2(b0, B, ZERO)
    SWIZZLE2(b1, B, ONE)
    SWIZZLE2(ar, A, R)
    SWIZZLE2(ag, A, G)
    SWIZZLE2(ab, A, B)
    SWIZZLE2(aa, A, A)
    SWIZZLE2(a0, A, ZERO)
    SWIZZLE2(a1, A, ONE)
    SWIZZLE3(rrr, R, R, R)
    SWIZZLE3(rrg, R, R, G)
    SWIZZLE3(rrb, R, R, B)
    SWIZZLE3(rra, R, R, A)
    SWIZZLE3(rr0, R, R, ZERO)
    SWIZZLE3(rr1, R, R, ONE)
    SWIZZLE3(rgr, R, G, R)
    SWIZZLE3(rgg, R, G, G)
    SWIZZLE3(rgb, R, G, B)
    SWIZZLE3(rga, R, G, A)
    SWIZZLE3(rg0, R, G, ZERO)
    SWIZZLE3(rg1, R, G, ONE)
    SWIZZLE3(rbr, R, B, R)
    SWIZZLE3(rbg, R, B, G)
    SWIZZLE3(rbb, R, B, B)
    SWIZZLE3(rba, R, B, A)
    SWIZZLE3(rb0, R, B, ZERO)
    SWIZZLE3(rb1, R, B, ONE)
    SWIZZLE3(rar, R, A, R)
    SWIZZLE3(rag, R, A, G)
    SWIZZLE3(rab, R, A, B)
    SWIZZLE3(raa, R, A, A)
    SWIZZLE3(ra0, R, A, ZERO)
    SWIZZLE3(ra1, R, A, ONE)
    SWIZZLE3(r0r, R, ZERO, R)
    SWIZZLE3(r0g, R, ZERO, G)
    SWIZZLE3(r0b, R, ZERO, B)
    SWIZZLE3(r0a, R, ZERO, A)
    SWIZZLE3(r00, R, ZERO, ZERO)
    SWIZZLE3(r01, R, ZERO, ONE)
    SWIZZLE3(r1r, R, ONE, R)
    SWIZZLE3(r1g, R, ONE, G)
    SWIZZLE3(r1b, R, ONE, B)
    SWIZZLE3(r1a, R, ONE, A)
    SWIZZLE3(r10, R, ONE, ZERO)
    SWIZZLE3(r11, R, ONE, ONE)
    SWIZZLE3(grr, G, R, R)
    SWIZZLE3(grg, G, R, G)
    SWIZZLE3(grb, G, R, B)
    SWIZZLE3(gra, G, R, A)
    SWIZZLE3(gr0, G, R, ZERO)
    SWIZZLE3(gr1, G, R, ONE)
    SWIZZLE3(ggr, G, G, R)
    SWIZZLE3(ggg, G, G, G)
    SWIZZLE3(ggb, G, G, B)
    SWIZZLE3(gga, G, G, A)
    SWIZZLE3(gg0, G, G, ZERO)
    SWIZZLE3(gg1, G, G, ONE)
    SWIZZLE3(gbr, G, B, R)
    SWIZZLE3(gbg, G, B, G)
    SWIZZLE3(gbb, G, B, B)
    SWIZZLE3(gba, G, B, A)
    SWIZZLE3(gb0, G, B, ZERO)
    SWIZZLE3(gb1, G, B, ONE)
    SWIZZLE3(gar, G, A, R)
    SWIZZLE3(gag, G, A, G)
    SWIZZLE3(gab, G, A, B)
    SWIZZLE3(gaa, G, A, A)
    SWIZZLE3(ga0, G, A, ZERO)
    SWIZZLE3(ga1, G, A, ONE)
    SWIZZLE3(g0r, G, ZERO, R)
    SWIZZLE3(g0g, G, ZERO, G)
    SWIZZLE3(g0b, G, ZERO, B)
    SWIZZLE3(g0a, G, ZERO, A)
    SWIZZLE3(g00, G, ZERO, ZERO)
    SWIZZLE3(g01, G, ZERO, ONE)
    SWIZZLE3(g1r, G, ONE, R)
    SWIZZLE3(g1g, G, ONE, G)
    SWIZZLE3(g1b, G, ONE, B)
    SWIZZLE3(g1a, G, ONE, A)
    SWIZZLE3(g10, G, ONE, ZERO)
    SWIZZLE3(g11, G, ONE, ONE)
    SWIZZLE3(brr, B, R, R)
    SWIZZLE3(brg, B, R, G)
    SWIZZLE3(brb, B, R, B)
    SWIZZLE3(bra, B, R, A)
    SWIZZLE3(br0, B, R, ZERO)
    SWIZZLE3(br1, B, R, ONE)
    SWIZZLE3(bgr, B, G, R)
    SWIZZLE3(bgg, B, G, G)
    SWIZZLE3(bgb, B, G, B)
    SWIZZLE3(bga, B, G, A)
    SWIZZLE3(bg0, B, G, ZERO)
    SWIZZLE3(bg1, B, G, ONE)
    SWIZZLE3(bbr, B, B, R)
    SWIZZLE3(bbg, B, B, G)
    SWIZZLE3(bbb, B, B, B)
    SWIZZLE3(bba, B, B, A)
    SWIZZLE3(bb0, B, B, ZERO)
    SWIZZLE3(bb1, B, B, ONE)
    SWIZZLE3(bar, B, A, R)
    SWIZZLE3(bag, B, A, G)
    SWIZZLE3(bab, B, A, B)
    SWIZZLE3(baa, B, A, A)
    SWIZZLE3(ba0, B, A, ZERO)
    SWIZZLE3(ba1, B, A, ONE)
    SWIZZLE3(b0r, B, ZERO, R)
    SWIZZLE3(b0g, B, ZERO, G)
    SWIZZLE3(b0b, B, ZERO, B)
    SWIZZLE3(b0a, B, ZERO, A)
    SWIZZLE3(b00, B, ZERO, ZERO)
    SWIZZLE3(b01, B, ZERO, ONE)
    SWIZZLE3(b1r, B, ONE, R)
    SWIZZLE3(b1g, B, ONE, G)
    SWIZZLE3(b1b, B, ONE, B)
    SWIZZLE3(b1a, B, ONE, A)
    SWIZZLE3(b10, B, ONE, ZERO)
    SWIZZLE3(b11, B, ONE, ONE)
    SWIZZLE3(arr, A, R, R)
    SWIZZLE3(arg, A, R, G)
    SWIZZLE3(arb, A, R, B)
    SWIZZLE3(ara, A, R, A)
    SWIZZLE3(ar0, A, R, ZERO)
    SWIZZLE3(ar1, A, R, ONE)
    SWIZZLE3(agr, A, G, R)
    SWIZZLE3(agg, A, G, G)
    SWIZZLE3(agb, A, G, B)
    SWIZZLE3(aga, A, G, A)
    SWIZZLE3(ag0, A, G, ZERO)
    SWIZZLE3(ag1, A, G, ONE)
    SWIZZLE3(abr, A, B, R)
    SWIZZLE3(abg, A, B, G)
    SWIZZLE3(abb, A, B, B)
    SWIZZLE3(aba, A, B, A)
    SWIZZLE3(ab0, A, B, ZERO)
    SWIZZLE3(ab1, A, B, ONE)
    SWIZZLE3(aar, A, A, R)
    SWIZZLE3(aag, A, A, G)
    SWIZZLE3(aab, A, A, B)
    SWIZZLE3(aaa, A, A, A)
    SWIZZLE3(aa0, A, A, ZERO)
    SWIZZLE3(aa1, A, A, ONE)
    SWIZZLE3(a0r, A, ZERO, R)
    SWIZZLE3(a0g, A, ZERO, G)
    SWIZZLE3(a0b, A, ZERO, B)
    SWIZZLE3(a0a, A, ZERO, A)
    SWIZZLE3(a00, A, ZERO, ZERO)
    SWIZZLE3(a01, A, ZERO, ONE)
    SWIZZLE3(a1r, A, ONE, R)
    SWIZZLE3(a1g, A, ONE, G)
    SWIZZLE3(a1b, A, ONE, B)
    SWIZZLE3(a1a, A, ONE, A)
    SWIZZLE3(a10, A, ONE, ZERO)
    SWIZZLE3(a11, A, ONE, ONE)
    SWIZZLE4(rrrr, R, R, R, R)
    SWIZZLE4(rrrg, R, R, R, G)
    SWIZZLE4(rrrb, R, R, R, B)
    SWIZZLE4(rrra, R, R, R, A)
    SWIZZLE4(rrr0, R, R, R, ZERO)
    SWIZZLE4(rrr1, R, R, R, ONE)
    SWIZZLE4(rrgr, R, R, G, R)
    SWIZZLE4(rrgg, R, R, G, G)
    SWIZZLE4(rrgb, R, R, G, B)
    SWIZZLE4(rrga, R, R, G, A)
    SWIZZLE4(rrg0, R, R, G, ZERO)
    SWIZZLE4(rrg1, R, R, G, ONE)
    SWIZZLE4(rrbr, R, R, B, R)
    SWIZZLE4(rrbg, R, R, B, G)
    SWIZZLE4(rrbb, R, R, B, B)
    SWIZZLE4(rrba, R, R, B, A)
    SWIZZLE4(rrb0, R, R, B, ZERO)
    SWIZZLE4(rrb1, R, R, B, ONE)
    SWIZZLE4(rrar, R, R, A, R)
    SWIZZLE4(rrag, R, R, A, G)
    SWIZZLE4(rrab, R, R, A, B)
    SWIZZLE4(rraa, R, R, A, A)
    SWIZZLE4(rra0, R, R, A, ZERO)
    SWIZZLE4(rra1, R, R, A, ONE)
    SWIZZLE4(rr0r, R, R, ZERO, R)
    SWIZZLE4(rr0g, R, R, ZERO, G)
    SWIZZLE4(rr0b, R, R, ZERO, B)
    SWIZZLE4(rr0a, R, R, ZERO, A)
    SWIZZLE4(rr00, R, R, ZERO, ZERO)
    SWIZZLE4(rr01, R, R, ZERO, ONE)
    SWIZZLE4(rr1r, R, R, ONE, R)
    SWIZZLE4(rr1g, R, R, ONE, G)
    SWIZZLE4(rr1b, R, R, ONE, B)
    SWIZZLE4(rr1a, R, R, ONE, A)
    SWIZZLE4(rr10, R, R, ONE, ZERO)
    SWIZZLE4(rr11, R, R, ONE, ONE)
    SWIZZLE4(rgrr, R, G, R, R)
    SWIZZLE4(rgrg, R, G, R, G)
    SWIZZLE4(rgrb, R, G, R, B)
    SWIZZLE4(rgra, R, G, R, A)
    SWIZZLE4(rgr0, R, G, R, ZERO)
    SWIZZLE4(rgr1, R, G, R, ONE)
    SWIZZLE4(rggr, R, G, G, R)
    SWIZZLE4(rggg, R, G, G, G)
    SWIZZLE4(rggb, R, G, G, B)
    SWIZZLE4(rgga, R, G, G, A)
    SWIZZLE4(rgg0, R, G, G, ZERO)
    SWIZZLE4(rgg1, R, G, G, ONE)
    SWIZZLE4(rgbr, R, G, B, R)
    SWIZZLE4(rgbg, R, G, B, G)
    SWIZZLE4(rgbb, R, G, B, B)
    SWIZZLE4(rgba, R, G, B, A)
    SWIZZLE4(rgb0, R, G, B, ZERO)
    SWIZZLE4(rgb1, R, G, B, ONE)
    SWIZZLE4(rgar, R, G, A, R)
    SWIZZLE4(rgag, R, G, A, G)
    SWIZZLE4(rgab, R, G, A, B)
    SWIZZLE4(rgaa, R, G, A, A)
    SWIZZLE4(rga0, R, G, A, ZERO)
    SWIZZLE4(rga1, R, G, A, ONE)
    SWIZZLE4(rg0r, R, G, ZERO, R)
    SWIZZLE4(rg0g, R, G, ZERO, G)
    SWIZZLE4(rg0b, R, G, ZERO, B)
    SWIZZLE4(rg0a, R, G, ZERO, A)
    SWIZZLE4(rg00, R, G, ZERO, ZERO)
    SWIZZLE4(rg01, R, G, ZERO, ONE)
    SWIZZLE4(rg1r, R, G, ONE, R)
    SWIZZLE4(rg1g, R, G, ONE, G)
    SWIZZLE4(rg1b, R, G, ONE, B)
    SWIZZLE4(rg1a, R, G, ONE, A)
    SWIZZLE4(rg10, R, G, ONE, ZERO)
    SWIZZLE4(rg11, R, G, ONE, ONE)
    SWIZZLE4(rbrr, R, B, R, R)
    SWIZZLE4(rbrg, R, B, R, G)
    SWIZZLE4(rbrb, R, B, R, B)
    SWIZZLE4(rbra, R, B, R, A)
    SWIZZLE4(rbr0, R, B, R, ZERO)
    SWIZZLE4(rbr1, R, B, R, ONE)
    SWIZZLE4(rbgr, R, B, G, R)
    SWIZZLE4(rbgg, R, B, G, G)
    SWIZZLE4(rbgb, R, B, G, B)
    SWIZZLE4(rbga, R, B, G, A)
    SWIZZLE4(rbg0, R, B, G, ZERO)
    SWIZZLE4(rbg1, R, B, G, ONE)
    SWIZZLE4(rbbr, R, B, B, R)
    SWIZZLE4(rbbg, R, B, B, G)
    SWIZZLE4(rbbb, R, B, B, B)
    SWIZZLE4(rbba, R, B, B, A)
    SWIZZLE4(rbb0, R, B, B, ZERO)
    SWIZZLE4(rbb1, R, B, B, ONE)
    SWIZZLE4(rbar, R, B, A, R)
    SWIZZLE4(rbag, R, B, A, G)
    SWIZZLE4(rbab, R, B, A, B)
    SWIZZLE4(rbaa, R, B, A, A)
    SWIZZLE4(rba0, R, B, A, ZERO)
    SWIZZLE4(rba1, R, B, A, ONE)
    SWIZZLE4(rb0r, R, B, ZERO, R)
    SWIZZLE4(rb0g, R, B, ZERO, G)
    SWIZZLE4(rb0b, R, B, ZERO, B)
    SWIZZLE4(rb0a, R, B, ZERO, A)
    SWIZZLE4(rb00, R, B, ZERO, ZERO)
    SWIZZLE4(rb01, R, B, ZERO, ONE)
    SWIZZLE4(rb1r, R, B, ONE, R)
    SWIZZLE4(rb1g, R, B, ONE, G)
    SWIZZLE4(rb1b, R, B, ONE, B)
    SWIZZLE4(rb1a, R, B, ONE, A)
    SWIZZLE4(rb10, R, B, ONE, ZERO)
    SWIZZLE4(rb11, R, B, ONE, ONE)
    SWIZZLE4(rarr, R, A, R, R)
    SWIZZLE4(rarg, R, A, R, G)
    SWIZZLE4(rarb, R, A, R, B)
    SWIZZLE4(rara, R, A, R, A)
    SWIZZLE4(rar0, R, A, R, ZERO)
    SWIZZLE4(rar1, R, A, R, ONE)
    SWIZZLE4(ragr, R, A, G, R)
    SWIZZLE4(ragg, R, A, G, G)
    SWIZZLE4(ragb, R, A, G, B)
    SWIZZLE4(raga, R, A, G, A)
    SWIZZLE4(rag0, R, A, G, ZERO)
    SWIZZLE4(rag1, R, A, G, ONE)
    SWIZZLE4(rabr, R, A, B, R)
    SWIZZLE4(rabg, R, A, B, G)
    SWIZZLE4(rabb, R, A, B, B)
    SWIZZLE4(raba, R, A, B, A)
    SWIZZLE4(rab0, R, A, B, ZERO)
    SWIZZLE4(rab1, R, A, B, ONE)
    SWIZZLE4(raar, R, A, A, R)
    SWIZZLE4(raag, R, A, A, G)
    SWIZZLE4(raab, R, A, A, B)
    SWIZZLE4(raaa, R, A, A, A)
    SWIZZLE4(raa0, R, A, A, ZERO)
    SWIZZLE4(raa1, R, A, A, ONE)
    SWIZZLE4(ra0r, R, A, ZERO, R)
    SWIZZLE4(ra0g, R, A, ZERO, G)
    SWIZZLE4(ra0b, R, A, ZERO, B)
    SWIZZLE4(ra0a, R, A, ZERO, A)
    SWIZZLE4(ra00, R, A, ZERO, ZERO)
    SWIZZLE4(ra01, R, A, ZERO, ONE)
    SWIZZLE4(ra1r, R, A, ONE, R)
    SWIZZLE4(ra1g, R, A, ONE, G)
    SWIZZLE4(ra1b, R, A, ONE, B)
    SWIZZLE4(ra1a, R, A, ONE, A)
    SWIZZLE4(ra10, R, A, ONE, ZERO)
    SWIZZLE4(ra11, R, A, ONE, ONE)
    SWIZZLE4(r0rr, R, ZERO, R, R)
    SWIZZLE4(r0rg, R, ZERO, R, G)
    SWIZZLE4(r0rb, R, ZERO, R, B)
    SWIZZLE4(r0ra, R, ZERO, R, A)
    SWIZZLE4(r0r0, R, ZERO, R, ZERO)
    SWIZZLE4(r0r1, R, ZERO, R, ONE)
    SWIZZLE4(r0gr, R, ZERO, G, R)
    SWIZZLE4(r0gg, R, ZERO, G, G)
    SWIZZLE4(r0gb, R, ZERO, G, B)
    SWIZZLE4(r0ga, R, ZERO, G, A)
    SWIZZLE4(r0g0, R, ZERO, G, ZERO)
    SWIZZLE4(r0g1, R, ZERO, G, ONE)
    SWIZZLE4(r0br, R, ZERO, B, R)
    SWIZZLE4(r0bg, R, ZERO, B, G)
    SWIZZLE4(r0bb, R, ZERO, B, B)
    SWIZZLE4(r0ba, R, ZERO, B, A)
    SWIZZLE4(r0b0, R, ZERO, B, ZERO)
    SWIZZLE4(r0b1, R, ZERO, B, ONE)
    SWIZZLE4(r0ar, R, ZERO, A, R)
    SWIZZLE4(r0ag, R, ZERO, A, G)
    SWIZZLE4(r0ab, R, ZERO, A, B)
    SWIZZLE4(r0aa, R, ZERO, A, A)
    SWIZZLE4(r0a0, R, ZERO, A, ZERO)
    SWIZZLE4(r0a1, R, ZERO, A, ONE)
    SWIZZLE4(r00r, R, ZERO, ZERO, R)
    SWIZZLE4(r00g, R, ZERO, ZERO, G)
    SWIZZLE4(r00b, R, ZERO, ZERO, B)
    SWIZZLE4(r00a, R, ZERO, ZERO, A)
    SWIZZLE4(r000, R, ZERO, ZERO, ZERO)
    SWIZZLE4(r001, R, ZERO, ZERO, ONE)
    SWIZZLE4(r01r, R, ZERO, ONE, R)
    SWIZZLE4(r01g, R, ZERO, ONE, G)
    SWIZZLE4(r01b, R, ZERO, ONE, B)
    SWIZZLE4(r01a, R, ZERO, ONE, A)
    SWIZZLE4(r010, R, ZERO, ONE, ZERO)
    SWIZZLE4(r011, R, ZERO, ONE, ONE)
    SWIZZLE4(r1rr, R, ONE, R, R)
    SWIZZLE4(r1rg, R, ONE, R, G)
    SWIZZLE4(r1rb, R, ONE, R, B)
    SWIZZLE4(r1ra, R, ONE, R, A)
    SWIZZLE4(r1r0, R, ONE, R, ZERO)
    SWIZZLE4(r1r1, R, ONE, R, ONE)
    SWIZZLE4(r1gr, R, ONE, G, R)
    SWIZZLE4(r1gg, R, ONE, G, G)
    SWIZZLE4(r1gb, R, ONE, G, B)
    SWIZZLE4(r1ga, R, ONE, G, A)
    SWIZZLE4(r1g0, R, ONE, G, ZERO)
    SWIZZLE4(r1g1, R, ONE, G, ONE)
    SWIZZLE4(r1br, R, ONE, B, R)
    SWIZZLE4(r1bg, R, ONE, B, G)
    SWIZZLE4(r1bb, R, ONE, B, B)
    SWIZZLE4(r1ba, R, ONE, B, A)
    SWIZZLE4(r1b0, R, ONE, B, ZERO)
    SWIZZLE4(r1b1, R, ONE, B, ONE)
    SWIZZLE4(r1ar, R, ONE, A, R)
    SWIZZLE4(r1ag, R, ONE, A, G)
    SWIZZLE4(r1ab, R, ONE, A, B)
    SWIZZLE4(r1aa, R, ONE, A, A)
    SWIZZLE4(r1a0, R, ONE, A, ZERO)
    SWIZZLE4(r1a1, R, ONE, A, ONE)
    SWIZZLE4(r10r, R, ONE, ZERO, R)
    SWIZZLE4(r10g, R, ONE, ZERO, G)
    SWIZZLE4(r10b, R, ONE, ZERO, B)
    SWIZZLE4(r10a, R, ONE, ZERO, A)
    SWIZZLE4(r100, R, ONE, ZERO, ZERO)
    SWIZZLE4(r101, R, ONE, ZERO, ONE)
    SWIZZLE4(r11r, R, ONE, ONE, R)
    SWIZZLE4(r11g, R, ONE, ONE, G)
    SWIZZLE4(r11b, R, ONE, ONE, B)
    SWIZZLE4(r11a, R, ONE, ONE, A)
    SWIZZLE4(r110, R, ONE, ONE, ZERO)
    SWIZZLE4(r111, R, ONE, ONE, ONE)
    SWIZZLE4(grrr, G, R, R, R)
    SWIZZLE4(grrg, G, R, R, G)
    SWIZZLE4(grrb, G, R, R, B)
    SWIZZLE4(grra, G, R, R, A)
    SWIZZLE4(grr0, G, R, R, ZERO)
    SWIZZLE4(grr1, G, R, R, ONE)
    SWIZZLE4(grgr, G, R, G, R)
    SWIZZLE4(grgg, G, R, G, G)
    SWIZZLE4(grgb, G, R, G, B)
    SWIZZLE4(grga, G, R, G, A)
    SWIZZLE4(grg0, G, R, G, ZERO)
    SWIZZLE4(grg1, G, R, G, ONE)
    SWIZZLE4(grbr, G, R, B, R)
    SWIZZLE4(grbg, G, R, B, G)
    SWIZZLE4(grbb, G, R, B, B)
    SWIZZLE4(grba, G, R, B, A)
    SWIZZLE4(grb0, G, R, B, ZERO)
    SWIZZLE4(grb1, G, R, B, ONE)
    SWIZZLE4(grar, G, R, A, R)
    SWIZZLE4(grag, G, R, A, G)
    SWIZZLE4(grab, G, R, A, B)
    SWIZZLE4(graa, G, R, A, A)
    SWIZZLE4(gra0, G, R, A, ZERO)
    SWIZZLE4(gra1, G, R, A, ONE)
    SWIZZLE4(gr0r, G, R, ZERO, R)
    SWIZZLE4(gr0g, G, R, ZERO, G)
    SWIZZLE4(gr0b, G, R, ZERO, B)
    SWIZZLE4(gr0a, G, R, ZERO, A)
    SWIZZLE4(gr00, G, R, ZERO, ZERO)
    SWIZZLE4(gr01, G, R, ZERO, ONE)
    SWIZZLE4(gr1r, G, R, ONE, R)
    SWIZZLE4(gr1g, G, R, ONE, G)
    SWIZZLE4(gr1b, G, R, ONE, B)
    SWIZZLE4(gr1a, G, R, ONE, A)
    SWIZZLE4(gr10, G, R, ONE, ZERO)
    SWIZZLE4(gr11, G, R, ONE, ONE)
    SWIZZLE4(ggrr, G, G, R, R)
    SWIZZLE4(ggrg, G, G, R, G)
    SWIZZLE4(ggrb, G, G, R, B)
    SWIZZLE4(ggra, G, G, R, A)
    SWIZZLE4(ggr0, G, G, R, ZERO)
    SWIZZLE4(ggr1, G, G, R, ONE)
    SWIZZLE4(gggr, G, G, G, R)
    SWIZZLE4(gggg, G, G, G, G)
    SWIZZLE4(gggb, G, G, G, B)
    SWIZZLE4(ggga, G, G, G, A)
    SWIZZLE4(ggg0, G, G, G, ZERO)
    SWIZZLE4(ggg1, G, G, G, ONE)
    SWIZZLE4(ggbr, G, G, B, R)
    SWIZZLE4(ggbg, G, G, B, G)
    SWIZZLE4(ggbb, G, G, B, B)
    SWIZZLE4(ggba, G, G, B, A)
    SWIZZLE4(ggb0, G, G, B, ZERO)
    SWIZZLE4(ggb1, G, G, B, ONE)
    SWIZZLE4(ggar, G, G, A, R)
    SWIZZLE4(ggag, G, G, A, G)
    SWIZZLE4(ggab, G, G, A, B)
    SWIZZLE4(ggaa, G, G, A, A)
    SWIZZLE4(gga0, G, G, A, ZERO)
    SWIZZLE4(gga1, G, G, A, ONE)
    SWIZZLE4(gg0r, G, G, ZERO, R)
    SWIZZLE4(gg0g, G, G, ZERO, G)
    SWIZZLE4(gg0b, G, G, ZERO, B)
    SWIZZLE4(gg0a, G, G, ZERO, A)
    SWIZZLE4(gg00, G, G, ZERO, ZERO)
    SWIZZLE4(gg01, G, G, ZERO, ONE)
    SWIZZLE4(gg1r, G, G, ONE, R)
    SWIZZLE4(gg1g, G, G, ONE, G)
    SWIZZLE4(gg1b, G, G, ONE, B)
    SWIZZLE4(gg1a, G, G, ONE, A)
    SWIZZLE4(gg10, G, G, ONE, ZERO)
    SWIZZLE4(gg11, G, G, ONE, ONE)
    SWIZZLE4(gbrr, G, B, R, R)
    SWIZZLE4(gbrg, G, B, R, G)
    SWIZZLE4(gbrb, G, B, R, B)
    SWIZZLE4(gbra, G, B, R, A)
    SWIZZLE4(gbr0, G, B, R, ZERO)
    SWIZZLE4(gbr1, G, B, R, ONE)
    SWIZZLE4(gbgr, G, B, G, R)
    SWIZZLE4(gbgg, G, B, G, G)
    SWIZZLE4(gbgb, G, B, G, B)
    SWIZZLE4(gbga, G, B, G, A)
    SWIZZLE4(gbg0, G, B, G, ZERO)
    SWIZZLE4(gbg1, G, B, G, ONE)
    SWIZZLE4(gbbr, G, B, B, R)
    SWIZZLE4(gbbg, G, B, B, G)
    SWIZZLE4(gbbb, G, B, B, B)
    SWIZZLE4(gbba, G, B, B, A)
    SWIZZLE4(gbb0, G, B, B, ZERO)
    SWIZZLE4(gbb1, G, B, B, ONE)
    SWIZZLE4(gbar, G, B, A, R)
    SWIZZLE4(gbag, G, B, A, G)
    SWIZZLE4(gbab, G, B, A, B)
    SWIZZLE4(gbaa, G, B, A, A)
    SWIZZLE4(gba0, G, B, A, ZERO)
    SWIZZLE4(gba1, G, B, A, ONE)
    SWIZZLE4(gb0r, G, B, ZERO, R)
    SWIZZLE4(gb0g, G, B, ZERO, G)
    SWIZZLE4(gb0b, G, B, ZERO, B)
    SWIZZLE4(gb0a, G, B, ZERO, A)
    SWIZZLE4(gb00, G, B, ZERO, ZERO)
    SWIZZLE4(gb01, G, B, ZERO, ONE)
    SWIZZLE4(gb1r, G, B, ONE, R)
    SWIZZLE4(gb1g, G, B, ONE, G)
    SWIZZLE4(gb1b, G, B, ONE, B)
    SWIZZLE4(gb1a, G, B, ONE, A)
    SWIZZLE4(gb10, G, B, ONE, ZERO)
    SWIZZLE4(gb11, G, B, ONE, ONE)
    SWIZZLE4(garr, G, A, R, R)
    SWIZZLE4(garg, G, A, R, G)
    SWIZZLE4(garb, G, A, R, B)
    SWIZZLE4(gara, G, A, R, A)
    SWIZZLE4(gar0, G, A, R, ZERO)
    SWIZZLE4(gar1, G, A, R, ONE)
    SWIZZLE4(gagr, G, A, G, R)
    SWIZZLE4(gagg, G, A, G, G)
    SWIZZLE4(gagb, G, A, G, B)
    SWIZZLE4(gaga, G, A, G, A)
    SWIZZLE4(gag0, G, A, G, ZERO)
    SWIZZLE4(gag1, G, A, G, ONE)
    SWIZZLE4(gabr, G, A, B, R)
    SWIZZLE4(gabg, G, A, B, G)
    SWIZZLE4(gabb, G, A, B, B)
    SWIZZLE4(gaba, G, A, B, A)
    SWIZZLE4(gab0, G, A, B, ZERO)
    SWIZZLE4(gab1, G, A, B, ONE)
    SWIZZLE4(gaar, G, A, A, R)
    SWIZZLE4(gaag, G, A, A, G)
    SWIZZLE4(gaab, G, A, A, B)
    SWIZZLE4(gaaa, G, A, A, A)
    SWIZZLE4(gaa0, G, A, A, ZERO)
    SWIZZLE4(gaa1, G, A, A, ONE)
    SWIZZLE4(ga0r, G, A, ZERO, R)
    SWIZZLE4(ga0g, G, A, ZERO, G)
    SWIZZLE4(ga0b, G, A, ZERO, B)
    SWIZZLE4(ga0a, G, A, ZERO, A)
    SWIZZLE4(ga00, G, A, ZERO, ZERO)
    SWIZZLE4(ga01, G, A, ZERO, ONE)
    SWIZZLE4(ga1r, G, A, ONE, R)
    SWIZZLE4(ga1g, G, A, ONE, G)
    SWIZZLE4(ga1b, G, A, ONE, B)
    SWIZZLE4(ga1a, G, A, ONE, A)
    SWIZZLE4(ga10, G, A, ONE, ZERO)
    SWIZZLE4(ga11, G, A, ONE, ONE)
    SWIZZLE4(g0rr, G, ZERO, R, R)
    SWIZZLE4(g0rg, G, ZERO, R, G)
    SWIZZLE4(g0rb, G, ZERO, R, B)
    SWIZZLE4(g0ra, G, ZERO, R, A)
    SWIZZLE4(g0r0, G, ZERO, R, ZERO)
    SWIZZLE4(g0r1, G, ZERO, R, ONE)
    SWIZZLE4(g0gr, G, ZERO, G, R)
    SWIZZLE4(g0gg, G, ZERO, G, G)
    SWIZZLE4(g0gb, G, ZERO, G, B)
    SWIZZLE4(g0ga, G, ZERO, G, A)
    SWIZZLE4(g0g0, G, ZERO, G, ZERO)
    SWIZZLE4(g0g1, G, ZERO, G, ONE)
    SWIZZLE4(g0br, G, ZERO, B, R)
    SWIZZLE4(g0bg, G, ZERO, B, G)
    SWIZZLE4(g0bb, G, ZERO, B, B)
    SWIZZLE4(g0ba, G, ZERO, B, A)
    SWIZZLE4(g0b0, G, ZERO, B, ZERO)
    SWIZZLE4(g0b1, G, ZERO, B, ONE)
    SWIZZLE4(g0ar, G, ZERO, A, R)
    SWIZZLE4(g0ag, G, ZERO, A, G)
    SWIZZLE4(g0ab, G, ZERO, A, B)
    SWIZZLE4(g0aa, G, ZERO, A, A)
    SWIZZLE4(g0a0, G, ZERO, A, ZERO)
    SWIZZLE4(g0a1, G, ZERO, A, ONE)
    SWIZZLE4(g00r, G, ZERO, ZERO, R)
    SWIZZLE4(g00g, G, ZERO, ZERO, G)
    SWIZZLE4(g00b, G, ZERO, ZERO, B)
    SWIZZLE4(g00a, G, ZERO, ZERO, A)
    SWIZZLE4(g000, G, ZERO, ZERO, ZERO)
    SWIZZLE4(g001, G, ZERO, ZERO, ONE)
    SWIZZLE4(g01r, G, ZERO, ONE, R)
    SWIZZLE4(g01g, G, ZERO, ONE, G)
    SWIZZLE4(g01b, G, ZERO, ONE, B)
    SWIZZLE4(g01a, G, ZERO, ONE, A)
    SWIZZLE4(g010, G, ZERO, ONE, ZERO)
    SWIZZLE4(g011, G, ZERO, ONE, ONE)
    SWIZZLE4(g1rr, G, ONE, R, R)
    SWIZZLE4(g1rg, G, ONE, R, G)
    SWIZZLE4(g1rb, G, ONE, R, B)
    SWIZZLE4(g1ra, G, ONE, R, A)
    SWIZZLE4(g1r0, G, ONE, R, ZERO)
    SWIZZLE4(g1r1, G, ONE, R, ONE)
    SWIZZLE4(g1gr, G, ONE, G, R)
    SWIZZLE4(g1gg, G, ONE, G, G)
    SWIZZLE4(g1gb, G, ONE, G, B)
    SWIZZLE4(g1ga, G, ONE, G, A)
    SWIZZLE4(g1g0, G, ONE, G, ZERO)
    SWIZZLE4(g1g1, G, ONE, G, ONE)
    SWIZZLE4(g1br, G, ONE, B, R)
    SWIZZLE4(g1bg, G, ONE, B, G)
    SWIZZLE4(g1bb, G, ONE, B, B)
    SWIZZLE4(g1ba, G, ONE, B, A)
    SWIZZLE4(g1b0, G, ONE, B, ZERO)
    SWIZZLE4(g1b1, G, ONE, B, ONE)
    SWIZZLE4(g1ar, G, ONE, A, R)
    SWIZZLE4(g1ag, G, ONE, A, G)
    SWIZZLE4(g1ab, G, ONE, A, B)
    SWIZZLE4(g1aa, G, ONE, A, A)
    SWIZZLE4(g1a0, G, ONE, A, ZERO)
    SWIZZLE4(g1a1, G, ONE, A, ONE)
    SWIZZLE4(g10r, G, ONE, ZERO, R)
    SWIZZLE4(g10g, G, ONE, ZERO, G)
    SWIZZLE4(g10b, G, ONE, ZERO, B)
    SWIZZLE4(g10a, G, ONE, ZERO, A)
    SWIZZLE4(g100, G, ONE, ZERO, ZERO)
    SWIZZLE4(g101, G, ONE, ZERO, ONE)
    SWIZZLE4(g11r, G, ONE, ONE, R)
    SWIZZLE4(g11g, G, ONE, ONE, G)
    SWIZZLE4(g11b, G, ONE, ONE, B)
    SWIZZLE4(g11a, G, ONE, ONE, A)
    SWIZZLE4(g110, G, ONE, ONE, ZERO)
    SWIZZLE4(g111, G, ONE, ONE, ONE)
    SWIZZLE4(brrr, B, R, R, R)
    SWIZZLE4(brrg, B, R, R, G)
    SWIZZLE4(brrb, B, R, R, B)
    SWIZZLE4(brra, B, R, R, A)
    SWIZZLE4(brr0, B, R, R, ZERO)
    SWIZZLE4(brr1, B, R, R, ONE)
    SWIZZLE4(brgr, B, R, G, R)
    SWIZZLE4(brgg, B, R, G, G)
    SWIZZLE4(brgb, B, R, G, B)
    SWIZZLE4(brga, B, R, G, A)
    SWIZZLE4(brg0, B, R, G, ZERO)
    SWIZZLE4(brg1, B, R, G, ONE)
    SWIZZLE4(brbr, B, R, B, R)
    SWIZZLE4(brbg, B, R, B, G)
    SWIZZLE4(brbb, B, R, B, B)
    SWIZZLE4(brba, B, R, B, A)
    SWIZZLE4(brb0, B, R, B, ZERO)
    SWIZZLE4(brb1, B, R, B, ONE)
    SWIZZLE4(brar, B, R, A, R)
    SWIZZLE4(brag, B, R, A, G)
    SWIZZLE4(brab, B, R, A, B)
    SWIZZLE4(braa, B, R, A, A)
    SWIZZLE4(bra0, B, R, A, ZERO)
    SWIZZLE4(bra1, B, R, A, ONE)
    SWIZZLE4(br0r, B, R, ZERO, R)
    SWIZZLE4(br0g, B, R, ZERO, G)
    SWIZZLE4(br0b, B, R, ZERO, B)
    SWIZZLE4(br0a, B, R, ZERO, A)
    SWIZZLE4(br00, B, R, ZERO, ZERO)
    SWIZZLE4(br01, B, R, ZERO, ONE)
    SWIZZLE4(br1r, B, R, ONE, R)
    SWIZZLE4(br1g, B, R, ONE, G)
    SWIZZLE4(br1b, B, R, ONE, B)
    SWIZZLE4(br1a, B, R, ONE, A)
    SWIZZLE4(br10, B, R, ONE, ZERO)
    SWIZZLE4(br11, B, R, ONE, ONE)
    SWIZZLE4(bgrr, B, G, R, R)
    SWIZZLE4(bgrg, B, G, R, G)
    SWIZZLE4(bgrb, B, G, R, B)
    SWIZZLE4(bgra, B, G, R, A)
    SWIZZLE4(bgr0, B, G, R, ZERO)
    SWIZZLE4(bgr1, B, G, R, ONE)
    SWIZZLE4(bggr, B, G, G, R)
    SWIZZLE4(bggg, B, G, G, G)
    SWIZZLE4(bggb, B, G, G, B)
    SWIZZLE4(bgga, B, G, G, A)
    SWIZZLE4(bgg0, B, G, G, ZERO)
    SWIZZLE4(bgg1, B, G, G, ONE)
    SWIZZLE4(bgbr, B, G, B, R)
    SWIZZLE4(bgbg, B, G, B, G)
    SWIZZLE4(bgbb, B, G, B, B)
    SWIZZLE4(bgba, B, G, B, A)
    SWIZZLE4(bgb0, B, G, B, ZERO)
    SWIZZLE4(bgb1, B, G, B, ONE)
    SWIZZLE4(bgar, B, G, A, R)
    SWIZZLE4(bgag, B, G, A, G)
    SWIZZLE4(bgab, B, G, A, B)
    SWIZZLE4(bgaa, B, G, A, A)
    SWIZZLE4(bga0, B, G, A, ZERO)
    SWIZZLE4(bga1, B, G, A, ONE)
    SWIZZLE4(bg0r, B, G, ZERO, R)
    SWIZZLE4(bg0g, B, G, ZERO, G)
    SWIZZLE4(bg0b, B, G, ZERO, B)
    SWIZZLE4(bg0a, B, G, ZERO, A)
    SWIZZLE4(bg00, B, G, ZERO, ZERO)
    SWIZZLE4(bg01, B, G, ZERO, ONE)
    SWIZZLE4(bg1r, B, G, ONE, R)
    SWIZZLE4(bg1g, B, G, ONE, G)
    SWIZZLE4(bg1b, B, G, ONE, B)
    SWIZZLE4(bg1a, B, G, ONE, A)
    SWIZZLE4(bg10, B, G, ONE, ZERO)
    SWIZZLE4(bg11, B, G, ONE, ONE)
    SWIZZLE4(bbrr, B, B, R, R)
    SWIZZLE4(bbrg, B, B, R, G)
    SWIZZLE4(bbrb, B, B, R, B)
    SWIZZLE4(bbra, B, B, R, A)
    SWIZZLE4(bbr0, B, B, R, ZERO)
    SWIZZLE4(bbr1, B, B, R, ONE)
    SWIZZLE4(bbgr, B, B, G, R)
    SWIZZLE4(bbgg, B, B, G, G)
    SWIZZLE4(bbgb, B, B, G, B)
    SWIZZLE4(bbga, B, B, G, A)
    SWIZZLE4(bbg0, B, B, G, ZERO)
    SWIZZLE4(bbg1, B, B, G, ONE)
    SWIZZLE4(bbbr, B, B, B, R)
    SWIZZLE4(bbbg, B, B, B, G)
    SWIZZLE4(bbbb, B, B, B, B)
    SWIZZLE4(bbba, B, B, B, A)
    SWIZZLE4(bbb0, B, B, B, ZERO)
    SWIZZLE4(bbb1, B, B, B, ONE)
    SWIZZLE4(bbar, B, B, A, R)
    SWIZZLE4(bbag, B, B, A, G)
    SWIZZLE4(bbab, B, B, A, B)
    SWIZZLE4(bbaa, B, B, A, A)
    SWIZZLE4(bba0, B, B, A, ZERO)
    SWIZZLE4(bba1, B, B, A, ONE)
    SWIZZLE4(bb0r, B, B, ZERO, R)
    SWIZZLE4(bb0g, B, B, ZERO, G)
    SWIZZLE4(bb0b, B, B, ZERO, B)
    SWIZZLE4(bb0a, B, B, ZERO, A)
    SWIZZLE4(bb00, B, B, ZERO, ZERO)
    SWIZZLE4(bb01, B, B, ZERO, ONE)
    SWIZZLE4(bb1r, B, B, ONE, R)
    SWIZZLE4(bb1g, B, B, ONE, G)
    SWIZZLE4(bb1b, B, B, ONE, B)
    SWIZZLE4(bb1a, B, B, ONE, A)
    SWIZZLE4(bb10, B, B, ONE, ZERO)
    SWIZZLE4(bb11, B, B, ONE, ONE)
    SWIZZLE4(barr, B, A, R, R)
    SWIZZLE4(barg, B, A, R, G)
    SWIZZLE4(barb, B, A, R, B)
    SWIZZLE4(bara, B, A, R, A)
    SWIZZLE4(bar0, B, A, R, ZERO)
    SWIZZLE4(bar1, B, A, R, ONE)
    SWIZZLE4(bagr, B, A, G, R)
    SWIZZLE4(bagg, B, A, G, G)
    SWIZZLE4(bagb, B, A, G, B)
    SWIZZLE4(baga, B, A, G, A)
    SWIZZLE4(bag0, B, A, G, ZERO)
    SWIZZLE4(bag1, B, A, G, ONE)
    SWIZZLE4(babr, B, A, B, R)
    SWIZZLE4(babg, B, A, B, G)
    SWIZZLE4(babb, B, A, B, B)
    SWIZZLE4(baba, B, A, B, A)
    SWIZZLE4(bab0, B, A, B, ZERO)
    SWIZZLE4(bab1, B, A, B, ONE)
    SWIZZLE4(baar, B, A, A, R)
    SWIZZLE4(baag, B, A, A, G)
    SWIZZLE4(baab, B, A, A, B)
    SWIZZLE4(baaa, B, A, A, A)
    SWIZZLE4(baa0, B, A, A, ZERO)
    SWIZZLE4(baa1, B, A, A, ONE)
    SWIZZLE4(ba0r, B, A, ZERO, R)
    SWIZZLE4(ba0g, B, A, ZERO, G)
    SWIZZLE4(ba0b, B, A, ZERO, B)
    SWIZZLE4(ba0a, B, A, ZERO, A)
    SWIZZLE4(ba00, B, A, ZERO, ZERO)
    SWIZZLE4(ba01, B, A, ZERO, ONE)
    SWIZZLE4(ba1r, B, A, ONE, R)
    SWIZZLE4(ba1g, B, A, ONE, G)
    SWIZZLE4(ba1b, B, A, ONE, B)
    SWIZZLE4(ba1a, B, A, ONE, A)
    SWIZZLE4(ba10, B, A, ONE, ZERO)
    SWIZZLE4(ba11, B, A, ONE, ONE)
    SWIZZLE4(b0rr, B, ZERO, R, R)
    SWIZZLE4(b0rg, B, ZERO, R, G)
    SWIZZLE4(b0rb, B, ZERO, R, B)
    SWIZZLE4(b0ra, B, ZERO, R, A)
    SWIZZLE4(b0r0, B, ZERO, R, ZERO)
    SWIZZLE4(b0r1, B, ZERO, R, ONE)
    SWIZZLE4(b0gr, B, ZERO, G, R)
    SWIZZLE4(b0gg, B, ZERO, G, G)
    SWIZZLE4(b0gb, B, ZERO, G, B)
    SWIZZLE4(b0ga, B, ZERO, G, A)
    SWIZZLE4(b0g0, B, ZERO, G, ZERO)
    SWIZZLE4(b0g1, B, ZERO, G, ONE)
    SWIZZLE4(b0br, B, ZERO, B, R)
    SWIZZLE4(b0bg, B, ZERO, B, G)
    SWIZZLE4(b0bb, B, ZERO, B, B)
    SWIZZLE4(b0ba, B, ZERO, B, A)
    SWIZZLE4(b0b0, B, ZERO, B, ZERO)
    SWIZZLE4(b0b1, B, ZERO, B, ONE)
    SWIZZLE4(b0ar, B, ZERO, A, R)
    SWIZZLE4(b0ag, B, ZERO, A, G)
    SWIZZLE4(b0ab, B, ZERO, A, B)
    SWIZZLE4(b0aa, B, ZERO, A, A)
    SWIZZLE4(b0a0, B, ZERO, A, ZERO)
    SWIZZLE4(b0a1, B, ZERO, A, ONE)
    SWIZZLE4(b00r, B, ZERO, ZERO, R)
    SWIZZLE4(b00g, B, ZERO, ZERO, G)
    SWIZZLE4(b00b, B, ZERO, ZERO, B)
    SWIZZLE4(b00a, B, ZERO, ZERO, A)
    SWIZZLE4(b000, B, ZERO, ZERO, ZERO)
    SWIZZLE4(b001, B, ZERO, ZERO, ONE)
    SWIZZLE4(b01r, B, ZERO, ONE, R)
    SWIZZLE4(b01g, B, ZERO, ONE, G)
    SWIZZLE4(b01b, B, ZERO, ONE, B)
    SWIZZLE4(b01a, B, ZERO, ONE, A)
    SWIZZLE4(b010, B, ZERO, ONE, ZERO)
    SWIZZLE4(b011, B, ZERO, ONE, ONE)
    SWIZZLE4(b1rr, B, ONE, R, R)
    SWIZZLE4(b1rg, B, ONE, R, G)
    SWIZZLE4(b1rb, B, ONE, R, B)
    SWIZZLE4(b1ra, B, ONE, R, A)
    SWIZZLE4(b1r0, B, ONE, R, ZERO)
    SWIZZLE4(b1r1, B, ONE, R, ONE)
    SWIZZLE4(b1gr, B, ONE, G, R)
    SWIZZLE4(b1gg, B, ONE, G, G)
    SWIZZLE4(b1gb, B, ONE, G, B)
    SWIZZLE4(b1ga, B, ONE, G, A)
    SWIZZLE4(b1g0, B, ONE, G, ZERO)
    SWIZZLE4(b1g1, B, ONE, G, ONE)
    SWIZZLE4(b1br, B, ONE, B, R)
    SWIZZLE4(b1bg, B, ONE, B, G)
    SWIZZLE4(b1bb, B, ONE, B, B)
    SWIZZLE4(b1ba, B, ONE, B, A)
    SWIZZLE4(b1b0, B, ONE, B, ZERO)
    SWIZZLE4(b1b1, B, ONE, B, ONE)
    SWIZZLE4(b1ar, B, ONE, A, R)
    SWIZZLE4(b1ag, B, ONE, A, G)
    SWIZZLE4(b1ab, B, ONE, A, B)
    SWIZZLE4(b1aa, B, ONE, A, A)
    SWIZZLE4(b1a0, B, ONE, A, ZERO)
    SWIZZLE4(b1a1, B, ONE, A, ONE)
    SWIZZLE4(b10r, B, ONE, ZERO, R)
    SWIZZLE4(b10g, B, ONE, ZERO, G)
    SWIZZLE4(b10b, B, ONE, ZERO, B)
    SWIZZLE4(b10a, B, ONE, ZERO, A)
    SWIZZLE4(b100, B, ONE, ZERO, ZERO)
    SWIZZLE4(b101, B, ONE, ZERO, ONE)
    SWIZZLE4(b11r, B, ONE, ONE, R)
    SWIZZLE4(b11g, B, ONE, ONE, G)
    SWIZZLE4(b11b, B, ONE, ONE, B)
    SWIZZLE4(b11a, B, ONE, ONE, A)
    SWIZZLE4(b110, B, ONE, ONE, ZERO)
    SWIZZLE4(b111, B, ONE, ONE, ONE)
    SWIZZLE4(arrr, A, R, R, R)
    SWIZZLE4(arrg, A, R, R, G)
    SWIZZLE4(arrb, A, R, R, B)
    SWIZZLE4(arra, A, R, R, A)
    SWIZZLE4(arr0, A, R, R, ZERO)
    SWIZZLE4(arr1, A, R, R, ONE)
    SWIZZLE4(argr, A, R, G, R)
    SWIZZLE4(argg, A, R, G, G)
    SWIZZLE4(argb, A, R, G, B)
    SWIZZLE4(arga, A, R, G, A)
    SWIZZLE4(arg0, A, R, G, ZERO)
    SWIZZLE4(arg1, A, R, G, ONE)
    SWIZZLE4(arbr, A, R, B, R)
    SWIZZLE4(arbg, A, R, B, G)
    SWIZZLE4(arbb, A, R, B, B)
    SWIZZLE4(arba, A, R, B, A)
    SWIZZLE4(arb0, A, R, B, ZERO)
    SWIZZLE4(arb1, A, R, B, ONE)
    SWIZZLE4(arar, A, R, A, R)
    SWIZZLE4(arag, A, R, A, G)
    SWIZZLE4(arab, A, R, A, B)
    SWIZZLE4(araa, A, R, A, A)
    SWIZZLE4(ara0, A, R, A, ZERO)
    SWIZZLE4(ara1, A, R, A, ONE)
    SWIZZLE4(ar0r, A, R, ZERO, R)
    SWIZZLE4(ar0g, A, R, ZERO, G)
    SWIZZLE4(ar0b, A, R, ZERO, B)
    SWIZZLE4(ar0a, A, R, ZERO, A)
    SWIZZLE4(ar00, A, R, ZERO, ZERO)
    SWIZZLE4(ar01, A, R, ZERO, ONE)
    SWIZZLE4(ar1r, A, R, ONE, R)
    SWIZZLE4(ar1g, A, R, ONE, G)
    SWIZZLE4(ar1b, A, R, ONE, B)
    SWIZZLE4(ar1a, A, R, ONE, A)
    SWIZZLE4(ar10, A, R, ONE, ZERO)
    SWIZZLE4(ar11, A, R, ONE, ONE)
    SWIZZLE4(agrr, A, G, R, R)
    SWIZZLE4(agrg, A, G, R, G)
    SWIZZLE4(agrb, A, G, R, B)
    SWIZZLE4(agra, A, G, R, A)
    SWIZZLE4(agr0, A, G, R, ZERO)
    SWIZZLE4(agr1, A, G, R, ONE)
    SWIZZLE4(aggr, A, G, G, R)
    SWIZZLE4(aggg, A, G, G, G)
    SWIZZLE4(aggb, A, G, G, B)
    SWIZZLE4(agga, A, G, G, A)
    SWIZZLE4(agg0, A, G, G, ZERO)
    SWIZZLE4(agg1, A, G, G, ONE)
    SWIZZLE4(agbr, A, G, B, R)
    SWIZZLE4(agbg, A, G, B, G)
    SWIZZLE4(agbb, A, G, B, B)
    SWIZZLE4(agba, A, G, B, A)
    SWIZZLE4(agb0, A, G, B, ZERO)
    SWIZZLE4(agb1, A, G, B, ONE)
    SWIZZLE4(agar, A, G, A, R)
    SWIZZLE4(agag, A, G, A, G)
    SWIZZLE4(agab, A, G, A, B)
    SWIZZLE4(agaa, A, G, A, A)
    SWIZZLE4(aga0, A, G, A, ZERO)
    SWIZZLE4(aga1, A, G, A, ONE)
    SWIZZLE4(ag0r, A, G, ZERO, R)
    SWIZZLE4(ag0g, A, G, ZERO, G)
    SWIZZLE4(ag0b, A, G, ZERO, B)
    SWIZZLE4(ag0a, A, G, ZERO, A)
    SWIZZLE4(ag00, A, G, ZERO, ZERO)
    SWIZZLE4(ag01, A, G, ZERO, ONE)
    SWIZZLE4(ag1r, A, G, ONE, R)
    SWIZZLE4(ag1g, A, G, ONE, G)
    SWIZZLE4(ag1b, A, G, ONE, B)
    SWIZZLE4(ag1a, A, G, ONE, A)
    SWIZZLE4(ag10, A, G, ONE, ZERO)
    SWIZZLE4(ag11, A, G, ONE, ONE)
    SWIZZLE4(abrr, A, B, R, R)
    SWIZZLE4(abrg, A, B, R, G)
    SWIZZLE4(abrb, A, B, R, B)
    SWIZZLE4(abra, A, B, R, A)
    SWIZZLE4(abr0, A, B, R, ZERO)
    SWIZZLE4(abr1, A, B, R, ONE)
    SWIZZLE4(abgr, A, B, G, R)
    SWIZZLE4(abgg, A, B, G, G)
    SWIZZLE4(abgb, A, B, G, B)
    SWIZZLE4(abga, A, B, G, A)
    SWIZZLE4(abg0, A, B, G, ZERO)
    SWIZZLE4(abg1, A, B, G, ONE)
    SWIZZLE4(abbr, A, B, B, R)
    SWIZZLE4(abbg, A, B, B, G)
    SWIZZLE4(abbb, A, B, B, B)
    SWIZZLE4(abba, A, B, B, A)
    SWIZZLE4(abb0, A, B, B, ZERO)
    SWIZZLE4(abb1, A, B, B, ONE)
    SWIZZLE4(abar, A, B, A, R)
    SWIZZLE4(abag, A, B, A, G)
    SWIZZLE4(abab, A, B, A, B)
    SWIZZLE4(abaa, A, B, A, A)
    SWIZZLE4(aba0, A, B, A, ZERO)
    SWIZZLE4(aba1, A, B, A, ONE)
    SWIZZLE4(ab0r, A, B, ZERO, R)
    SWIZZLE4(ab0g, A, B, ZERO, G)
    SWIZZLE4(ab0b, A, B, ZERO, B)
    SWIZZLE4(ab0a, A, B, ZERO, A)
    SWIZZLE4(ab00, A, B, ZERO, ZERO)
    SWIZZLE4(ab01, A, B, ZERO, ONE)
    SWIZZLE4(ab1r, A, B, ONE, R)
    SWIZZLE4(ab1g, A, B, ONE, G)
    SWIZZLE4(ab1b, A, B, ONE, B)
    SWIZZLE4(ab1a, A, B, ONE, A)
    SWIZZLE4(ab10, A, B, ONE, ZERO)
    SWIZZLE4(ab11, A, B, ONE, ONE)
    SWIZZLE4(aarr, A, A, R, R)
    SWIZZLE4(aarg, A, A, R, G)
    SWIZZLE4(aarb, A, A, R, B)
    SWIZZLE4(aara, A, A, R, A)
    SWIZZLE4(aar0, A, A, R, ZERO)
    SWIZZLE4(aar1, A, A, R, ONE)
    SWIZZLE4(aagr, A, A, G, R)
    SWIZZLE4(aagg, A, A, G, G)
    SWIZZLE4(aagb, A, A, G, B)
    SWIZZLE4(aaga, A, A, G, A)
    SWIZZLE4(aag0, A, A, G, ZERO)
    SWIZZLE4(aag1, A, A, G, ONE)
    SWIZZLE4(aabr, A, A, B, R)
    SWIZZLE4(aabg, A, A, B, G)
    SWIZZLE4(aabb, A, A, B, B)
    SWIZZLE4(aaba, A, A, B, A)
    SWIZZLE4(aab0, A, A, B, ZERO)
    SWIZZLE4(aab1, A, A, B, ONE)
    SWIZZLE4(aaar, A, A, A, R)
    SWIZZLE4(aaag, A, A, A, G)
    SWIZZLE4(aaab, A, A, A, B)
    SWIZZLE4(aaaa, A, A, A, A)
    SWIZZLE4(aaa0, A, A, A, ZERO)
    SWIZZLE4(aaa1, A, A, A, ONE)
    SWIZZLE4(aa0r, A, A, ZERO, R)
    SWIZZLE4(aa0g, A, A, ZERO, G)
    SWIZZLE4(aa0b, A, A, ZERO, B)
    SWIZZLE4(aa0a, A, A, ZERO, A)
    SWIZZLE4(aa00, A, A, ZERO, ZERO)
    SWIZZLE4(aa01, A, A, ZERO, ONE)
    SWIZZLE4(aa1r, A, A, ONE, R)
    SWIZZLE4(aa1g, A, A, ONE, G)
    SWIZZLE4(aa1b, A, A, ONE, B)
    SWIZZLE4(aa1a, A, A, ONE, A)
    SWIZZLE4(aa10, A, A, ONE, ZERO)
    SWIZZLE4(aa11, A, A, ONE, ONE)
    SWIZZLE4(a0rr, A, ZERO, R, R)
    SWIZZLE4(a0rg, A, ZERO, R, G)
    SWIZZLE4(a0rb, A, ZERO, R, B)
    SWIZZLE4(a0ra, A, ZERO, R, A)
    SWIZZLE4(a0r0, A, ZERO, R, ZERO)
    SWIZZLE4(a0r1, A, ZERO, R, ONE)
    SWIZZLE4(a0gr, A, ZERO, G, R)
    SWIZZLE4(a0gg, A, ZERO, G, G)
    SWIZZLE4(a0gb, A, ZERO, G, B)
    SWIZZLE4(a0ga, A, ZERO, G, A)
    SWIZZLE4(a0g0, A, ZERO, G, ZERO)
    SWIZZLE4(a0g1, A, ZERO, G, ONE)
    SWIZZLE4(a0br, A, ZERO, B, R)
    SWIZZLE4(a0bg, A, ZERO, B, G)
    SWIZZLE4(a0bb, A, ZERO, B, B)
    SWIZZLE4(a0ba, A, ZERO, B, A)
    SWIZZLE4(a0b0, A, ZERO, B, ZERO)
    SWIZZLE4(a0b1, A, ZERO, B, ONE)
    SWIZZLE4(a0ar, A, ZERO, A, R)
    SWIZZLE4(a0ag, A, ZERO, A, G)
    SWIZZLE4(a0ab, A, ZERO, A, B)
    SWIZZLE4(a0aa, A, ZERO, A, A)
    SWIZZLE4(a0a0, A, ZERO, A, ZERO)
    SWIZZLE4(a0a1, A, ZERO, A, ONE)
    SWIZZLE4(a00r, A, ZERO, ZERO, R)
    SWIZZLE4(a00g, A, ZERO, ZERO, G)
    SWIZZLE4(a00b, A, ZERO, ZERO, B)
    SWIZZLE4(a00a, A, ZERO, ZERO, A)
    SWIZZLE4(a000, A, ZERO, ZERO, ZERO)
    SWIZZLE4(a001, A, ZERO, ZERO, ONE)
    SWIZZLE4(a01r, A, ZERO, ONE, R)
    SWIZZLE4(a01g, A, ZERO, ONE, G)
    SWIZZLE4(a01b, A, ZERO, ONE, B)
    SWIZZLE4(a01a, A, ZERO, ONE, A)
    SWIZZLE4(a010, A, ZERO, ONE, ZERO)
    SWIZZLE4(a011, A, ZERO, ONE, ONE)
    SWIZZLE4(a1rr, A, ONE, R, R)
    SWIZZLE4(a1rg, A, ONE, R, G)
    SWIZZLE4(a1rb, A, ONE, R, B)
    SWIZZLE4(a1ra, A, ONE, R, A)
    SWIZZLE4(a1r0, A, ONE, R, ZERO)
    SWIZZLE4(a1r1, A, ONE, R, ONE)
    SWIZZLE4(a1gr, A, ONE, G, R)
    SWIZZLE4(a1gg, A, ONE, G, G)
    SWIZZLE4(a1gb, A, ONE, G, B)
    SWIZZLE4(a1ga, A, ONE, G, A)
    SWIZZLE4(a1g0, A, ONE, G, ZERO)
    SWIZZLE4(a1g1, A, ONE, G, ONE)
    SWIZZLE4(a1br, A, ONE, B, R)
    SWIZZLE4(a1bg, A, ONE, B, G)
    SWIZZLE4(a1bb, A, ONE, B, B)
    SWIZZLE4(a1ba, A, ONE, B, A)
    SWIZZLE4(a1b0, A, ONE, B, ZERO)
    SWIZZLE4(a1b1, A, ONE, B, ONE)
    SWIZZLE4(a1ar, A, ONE, A, R)
    SWIZZLE4(a1ag, A, ONE, A, G)
    SWIZZLE4(a1ab, A, ONE, A, B)
    SWIZZLE4(a1aa, A, ONE, A, A)
    SWIZZLE4(a1a0, A, ONE, A, ZERO)
    SWIZZLE4(a1a1, A, ONE, A, ONE)
    SWIZZLE4(a10r, A, ONE, ZERO, R)
    SWIZZLE4(a10g, A, ONE, ZERO, G)
    SWIZZLE4(a10b, A, ONE, ZERO, B)
    SWIZZLE4(a10a, A, ONE, ZERO, A)
    SWIZZLE4(a100, A, ONE, ZERO, ZERO)
    SWIZZLE4(a101, A, ONE, ZERO, ONE)
    SWIZZLE4(a11r, A, ONE, ONE, R)
    SWIZZLE4(a11g, A, ONE, ONE, G)
    SWIZZLE4(a11b, A, ONE, ONE, B)
    SWIZZLE4(a11a, A, ONE, ONE, A)
    SWIZZLE4(a110, A, ONE, ONE, ZERO)
    SWIZZLE4(a111, A, ONE, ONE, ONE)

    #undef SWIZZLE1
    #undef SWIZZLE2
    #undef SWIZZLE3
    #undef SWIZZLE4

    /**
     * Invalidates this object and returns the SkSL expression it represents.
     */
    std::unique_ptr<SkSL::Expression> release() {
        return std::move(fExpression);
    }

    /**
     * Invalidates this object and returns the SkSL expression it represents coerced to the
     * specified type. If the expression cannot be coerced, reports an error and returns null.
     */
    std::unique_ptr<SkSL::Expression> coerceAndRelease(const SkSL::Type& type);

private:
    // for use in the SWIZZLE macros
    enum class SwizzleMap {
        x = SwizzleComponent::X,
        y = SwizzleComponent::Y,
        z = SwizzleComponent::Z,
        w = SwizzleComponent::W,
        r = SwizzleComponent::R,
        g = SwizzleComponent::G,
        b = SwizzleComponent::B,
        a = SwizzleComponent::A
    };

    Expression() {}

    std::unique_ptr<SkSL::Expression> fExpression;

    friend class Var;
};

Expression operator+(Expression left, Expression right);
Expression operator+=(Expression left, Expression right);
Expression operator+=(Var& left, Expression right);
Expression operator-(Expression left, Expression right);
Expression operator-=(Expression left, Expression right);
Expression operator-=(Var& left, Expression right);
Expression operator*(Expression left, Expression right);
Expression operator*=(Expression left, Expression right);
Expression operator*=(Var& left, Expression right);
Expression operator/(Expression left, Expression right);
Expression operator/=(Expression left, Expression right);
Expression operator/=(Var& left, Expression right);
Expression operator%(Expression left, Expression right);
Expression operator%=(Expression left, Expression right);
Expression operator%=(Var& left, Expression right);
Expression operator<<(Expression left, Expression right);
Expression operator<<=(Expression left, Expression right);
Expression operator<<=(Var& left, Expression right);
Expression operator>>(Expression left, Expression right);
Expression operator>>=(Expression left, Expression right);
Expression operator>>=(Var& left, Expression right);
Expression operator&&(Expression left, Expression right);
Expression operator||(Expression left, Expression right);
Expression operator&(Expression left, Expression right);
Expression operator&=(Expression left, Expression right);
Expression operator&=(Var& left, Expression right);
Expression operator|(Expression left, Expression right);
Expression operator|=(Expression left, Expression right);
Expression operator|=(Var& left, Expression right);
Expression operator^(Expression left, Expression right);
Expression operator^=(Expression left, Expression right);
Expression operator^=(Var& left, Expression right);
Expression operator,(Expression left, Expression right);
Expression operator==(Expression left, Expression right);
Expression operator!=(Expression left, Expression right);
Expression operator>(Expression left, Expression right);
Expression operator<(Expression left, Expression right);
Expression operator>=(Expression left, Expression right);
Expression operator<=(Expression left, Expression right);
Expression operator!(Expression expr);
Expression operator~(Expression expr);
Expression operator++(Expression expr);
Expression operator++(Expression expr, int);
Expression operator--(Expression expr);
Expression operator--(Expression expr, int);

} // namespace dsl

} // namespace SkSL

#endif
